### ISSUE TITLE
application definition `definition` should be the name of the NXDL

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#1001]
In nexusformat/definitions#1046, it was asked:
> Is it a rule that an appdef/entry/definition must be the name of the given appdef? 

Add such a statement to the Schema documentation:
https://github.com/nexusformat/definitions/blob/61c2b2a6e9666a48c0ea3afc391b0d01d6bbd404/nxdl.xsd#L174-L198

**Comment by prjemian** [comment]
example: https://github.com/nexusformat/definitions/blob/61c2b2a6e9666a48c0ea3afc391b0d01d6bbd404/applications/NXarchive.nxdl.xml#L24

The `NXarchive.nxdl.xml` file has `<definitions name="NXarchive"` ...

**Comment by RussBerg** [comment]
making the assumption that cnxvalidate is the driver, it requires that the name appearing in the **definition** attribute be _exactly_ (case sensitive) the name of the definition file so the statement should probably indicate that it must be the exact definition file name prefix. We ran into an issue last code camp with the NXspe definition which specified an enumeration for the **definition.** attribute with the list **NXSPE** and **NXspe** with NXSPE failing to validate, the solution was just to remove NXSPE.
