### ISSUE TITLE
CI on the main branch only

### ISSUE THREAD

**Issue by woutdenolf** [nexusformat/definitions#1017]
Currently syntax checks and docs deployment workflows run on each push.

I propose to:

1. trigger github workflows only for events from the `main` branch
2. trigger the syntax workflow for pull request to the the `main` branch

This allows us to check whether all tests of a PR pass before merging it into the main branch.

**Comment by prjemian** [comment]
What is the motivation for this change?

**Comment by woutdenolf** [comment]
> What is the motivation for this change?

As said in the description: you want to make sure all tests pass **before** merging a pull request, not afterward (which is the current situation).

**Comment by woutdenolf** [comment]
I split this issue in two separate issues:  #1023 #1025
