### ISSUE TITLE
Execute syntax checks on pull requests

### ISSUE THREAD

**Issue by woutdenolf** [nexusformat/definitions#1023]
For a PR you will only see CI passing/failing **after** you already merged the PR. You want to see it **before** you merge the PR.

**Comment by prjemian** [comment]
Actions https://github.com/nexusformat/definitions/actions/runs/1923801265 and https://github.com/nexusformat/definitions/actions/runs/1923718922 (both for #999) are examples of CI workflows failure before the PR was merged.

**Comment by woutdenolf** [comment]
Yes but these are push events on non-main branches. You don't see this in the pull request do you?
