### ISSUE TITLE
Deploy documentation on pushing a tag is error prone

### ISSUE THREAD

**Issue by woutdenolf** [nexusformat/definitions#1029]
One can always make mistakes when pushing [tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging) (typo, wrong tag, etc.). Tags could also be pushed to any branch. 

For these reasons I think deploying documentation upon pushing a tag is rather dangerous. I would advocate to limit the `publish-sphinx` workflow to the `main` branch and in addition use an environment variable (e.g. called `DEPLOY`) which is `False` by default. In that way the only way to deploy documentation is by running the `publish-sphinx` workflow manually from [the actions tab](https://github.com/nexusformat/definitions/actions) while setting `DEPLOY=True`.

https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow

https://docs.github.com/en/actions/learn-github-actions/environment-variables

**Comment by prjemian** [comment]
No work on this issue at 2022-06 Code Camp. Is it necessary to resolve this for release of NXDL now?

**Comment by woutdenolf** [comment]
We can keep it for the next release
