### ISSUE TITLE
BUG: "temperature" declared twice in NXsample

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#1037]
In the NXsample base class, the name `temperature` is declared for a field: https://github.com/nexusformat/definitions/blob/1ef4d81c330402bfb40aee3a7d7e337e060ceba1/base_classes/NXsample.nxdl.xml#L73-L78

and a group: https://github.com/nexusformat/definitions/blob/1ef4d81c330402bfb40aee3a7d7e337e060ceba1/base_classes/NXsample.nxdl.xml#L334-L336

The second declaration was due to #816, as requested by the [2018 NIAC](https://www.nexusformat.org/NIAC2018Minutes.html).

This decision created a conflict in NXsample.

**Comment by zjttoefs** [comment]
Replacing fields with `NXlog` groups is something that is allowed in general for time series data recording. @mkoennecke will confirm.
The NIAC decision was to deprecate the `_log` groups and direct people to the `temperature:NXlog` option. Which could have been done in the `<doc>` for the `_log`. Now that the `_log` is gone, maybe the easiest is to remove the duplication.
