### ISSUE TITLE
NXdata: errors on auxiliary signals

### ISSUE THREAD

**Issue by woutdenolf** [nexusformat/definitions#1044]
We have the `VARIABLE_errors` fields to specify the errors on all axes but we only have one `errors` field to specify the errors on the signal. I would propose `DATA_errors` to specify errors on all signals (auxiliary and default).

```
data:NXdata
   @axes=["x"]
   @signal="data1"
   @auxiliary_signals=["data2", "data3"]
   x: [1024]
   data1: [1024]
   data2: [1024]
   data3: [1024]
   x_errors: [1024]
   data1_errors: [1024]
   data2_errors: [1024]
   data3_errors: [1024]
```

`data1_errors` is `errors` in the current definition and `data2_errors`, `data3_errors` do not exist in the current definition.

**Comment by woutdenolf** [comment]
Looking very closely at the definition it seems that `VARIABLE_errors` can refer to any field

```
<field name="VARIABLE_errors" type="NX_NUMBER" nameType="any">
```

But we also have 

```
<field name="VARIABLE" type="NX_NUMBER" nameType="any">
```

which is for axes only. So probably we should just rename `VARIABLE_errors` to `FIELD_errors` and in the comments say it applies to any field, whether it is an axis, signal or auxiliary signal.

**Comment by woutdenolf** [comment]
Hmm its more complicated. It says

```
"Errors" (actually *uncertainties*) associated with axis ``VARIABLE``. 
```
and then
```
This pattern of using ``VARIABLE_errors`` can be used ... to associate uncertainties with a dataset named ``VARIABLE``.
```

https://github.com/nexusformat/definitions/blob/a10bd5e8323ea57a03ee01e49f16eb645b999bb8/base_classes/NXdata.nxdl.xml#L302-L313

I'll propose a better doc.

**Comment by woutdenolf** [comment]
To summarize: currently [`NXdata`](https://manual.nexusformat.org/classes/base_classes/NXdata.html) does not allow errors on auxiliary signals.

Proposal:
* renaming the `VARIABLE` field to `AXISNAME`
* updating the doc of `VARIABLE_errors` to say it applies to axes, signal or auxiliary signals: this is the actual change, although it is already somewhat support by NeXus as described [here](https://manual.nexusformat.org/datarules.html?highlight=errors).
* when both `errors` and `VARIABLE_errors` are present for the signal field, `errors` will be ignored

**Comment by benajamin** [comment]
NIAC agrees that this is just a documentation bug that should be fixed. Also the errors field was already decided to be deprecated in 2018.
