### ISSUE TITLE
NXgeometry in NXaperture

### ISSUE THREAD

**Issue by uwehergenhahn** [nexusformat/definitions#1050]
I understand NXgeometry is depreceated to describe the geometry of an experiment, and NXtransformations is supposed to be used. However, this does not carry through the whole documentation, e.g. in NXaperture an NXgeometry group is suggested to describe the geometry of the aperture. In this place, I find NXgeometry much more appropriate than NXtransformations. Was this thought through when NXgeometry fell out of favour, or is this rather an unintended consequence?

**Comment by zjttoefs** [comment]
https://manual.nexusformat.org/classes/base_classes/NXoff_geometry.html would be the class to take the shape.
We could not dig out an example of NXgeometry defined shape being used in practice when that decision was made.

**Comment by uwehergenhahn** [comment]
Thanks for the comment. I would like to describe a round object in some distance and in some direction of the interaction region. NXoff_geometry does not seem particularly handy to do that. Moreover: 'The origin of the coordinates is the position of the parent component, for example the NXdetector which the geometry describes.' NXaperture does not have any means to describe its position, if there is no NXgeometry group.
