### ISSUE TITLE
Is 'default' attribute value an absolute reference or a relative one?

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#1063]
is it allowed for the attribute 'default' to contain absolute references or only a relative one? Shall the relative reference point to one of the subgroups or can it point to a subgroup of a subgroup of a ...?

**Comment by benajamin** [comment]
This topic was discussed at the code camp and we worded the manual towards saying that the default attribute should be a relative reference to a child group (strict writer), but a reader might find an absolute path.

**Comment by prjemian** [comment]
Essentially a duplicate of #1003
