### ISSUE TITLE
How to require (in NXDL) a data item from a predefined set?

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#1064]
Is there a way in NXDL to require the presence of a data item (e.g. axis in NXdata) from a predefined set (either kx, or ky, or both)? E.g. NXdata.axes should be a list and we may want to specify that a given element of the list (e.g. the first axis) must come from an enum list. 

 Similarly, if we specify multiple optional fields/groups, how can we enforce that at least one of them shall be present?

**Comment by benajamin** [comment]
further: https://www.w3schools.com/xml/el_choice.asp

**Comment by benajamin** [comment]
@prjemian Does this issue belong in the milestone if there is no specific action to be taken?

**Comment by prjemian** [comment]
@benajamin You are right.  Issue #1002 was created for any action.  Then the question here is resolved.
