### ISSUE TITLE
Second section for Python example

### ISSUE THREAD

**Issue by BalazsBago** [nexusformat/definitions#1070]
https://manual.nexusformat.org/examples/index.html#examples-of-writing-and-reading-nexus-data-files

The 2.1.5. EPICS Area Detector Examples is a Python example. It would be better to move under the Python examples (https://manual.nexusformat.org/examples/h5py/index.html#python-examples-using-h5py) as a real life use case.

**Comment by woutdenolf** [comment]
Closed by https://github.com/nexusformat/definitions/pull/1060
