### ISSUE TITLE
Clean up unreferenced files from the manual source

### ISSUE THREAD

**Issue by benajamin** [nexusformat/definitions#1092]
In reviewing a pull request, I looked at [manual/source/examples/array-dimensions.xml.txt](https://github.com/nexusformat/definitions/blob/main/manual/source/examples/array-dimensions.xml.txt) and it seems to not be used in building the manual. We have probably got a bunch of old files that are no longer used and it would be good to clean them up. Is there a sensible way to check for unused files in the source tree?

**Comment by PeterC-DLS** [comment]
I think the following files in `manual/source/examples` can be removed:
```
abbreviated-nexus-file.xml.txt
array-dimensions1.xml.txt
array-dimensions2.xml.txt
array-dimensions3.xml.txt
array-dimensions.xml.txt
data-linking.xml.txt
napi-java-datarw3.java
nxdl-doc-fragment-simple.xml
nxdl-trac6-ex1.xml.txt
nxdl-trac6-ex2.xml.txt
```
but I'm not sure about these files, @prjemian:
 ```
h5py/TestReader.py
h5py/TestWriter.py
```

**Comment by woutdenolf** [comment]
I also noticed that TestReader.py and TestWriter.py were not actually used in the docs.

**Comment by prjemian** [comment]
I agree, I cannot find those files in the documentation or in a search using `git grep`.
