### ISSUE TITLE
Adding `nexusformat` examples to the manual

### ISSUE THREAD

**Issue by rayosborn** [nexusformat/definitions#1117]
I plan to create a PR, in which all the `h5py` examples are displayed alongside `nexusformat` versions as tabs. I think this will be less confusing to a new user looking for Python options and help them decide which to use. The changes to the docs will require adding the `sphinx-tabs` package as a Sphinx extension. The separate `nexusformat` page can then be removed, since there will be links to both the `nexusformat` and `h5py` documentation.

I already have a branch with the suggested modifications, which I will debug over the next few days before submitting the PR.

**Comment by prjemian** [comment]
@rayosborn : A commit (ed6f9fef29a1) in another branch shows you the places to add a new (package) requirement to build the documentation.  Any new packages (required to build the documentation) should be added to **_both_** of these files:

* `.github/env-workflow.yml`
* `requirements.txt`
