### ISSUE TITLE
CI fails when making the CNAME file

### ISSUE THREAD

**Issue by woutdenolf** [nexusformat/definitions#1154]
https://github.com/nexusformat/definitions/runs/7137146695?check_suite_focus=true

**Comment by woutdenolf** [comment]
@peterfpeterson Is CI still not building the documentation as it is done locally?

**Comment by prjemian** [comment]
In my local build (`make local`):

```bash
(bluesky_2022_3) prjemian@zap:~/.../NeXus/definitions$ ls ./build/manual/build/html/CNAME
./build/manual/build/html/CNAME
```

**Comment by prjemian** [comment]
That was for the `dev_tools` branch., Checking with main branch now.

**Comment by prjemian** [comment]
On main branch, with `make local`:

```bash
(bluesky_2022_3) prjemian@zap:~/.../NeXus/definitions$ ls ./build/manual/build/html/CNAME
ls: cannot access './build/manual/build/html/CNAME': No such file or directory
```

**Comment by prjemian** [comment]
Also note the default branch of [sphinx-notes/pages](https://github.com/sphinx-notes/pages) Actions is `v2`.

**Comment by woutdenolf** [comment]
Yes, so the point is that CNAME needs to be added to the result of an HTML build. In other words it needs to be copied afterward the sphinx.

**Comment by woutdenolf** [comment]
I have two potential fixes: https://github.com/nexusformat/definitions/pull/1158 and https://github.com/nexusformat/definitions/pull/1157

**Comment by woutdenolf** [comment]
Of course we need to run the publishing CI to check which one works. I propose to merge #1158 first and wait for CI.

**Comment by prjemian** [comment]
Either that or suspend the rules, temporarily.  This time, merge.

**Comment by woutdenolf** [comment]
Ok so https://github.com/nexusformat/definitions/pull/1158 doesn't work, probably because `sphinx-notes/pages` is not building in the normal directory. I see this

```
The HTML pages are in ../../../../../tmp/pages-gVzbCR6Kc2.
```

But I'm not sure the build is actually done in there are the build is just copied there.

**Comment by woutdenolf** [comment]
Maybe https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_extra_path is also an option. I'll investigate ...

**Comment by prjemian** [comment]
From the workflow log, steps 198-201

```
Setting up git repository
  Setting up git configure
  No local changes to save
  Setting up branch gh-pages
  Branch exists, checkout to it
  Switched to a new branch 'gh-pages'
  branch 'gh-pages' set up to track 'origin/gh-pages'.
  Removing build/
  Removing utils/
 Committing HTML documentation
  Deleting all file in repository
  removed 'CNAME'
```

**Comment by prjemian** [comment]
From raw logs:

```
2022-06-30T19:11:10.8519755Z removed 'utilities.html'
2022-06-30T19:11:10.8519991Z removed 'validation.html'
2022-06-30T19:11:10.8520229Z Copying HTML documentation to repository
2022-06-30T19:11:10.8520826Z '/tmp/pages-oW788h6erK/./.doctrees/applying-nexus.doctree' -> '././.doctrees/applying-nexus.doctree'
2022-06-30T19:11:10.8521367Z '/tmp/pages-oW788h6erK/./.doctrees/authorgroup.doctree' -> '././.doctrees/authorgroup.doctree'

...

2022-06-30T19:11:10.9211990Z '/tmp/pages-oW788h6erK/./_static/sphinxdoc.css' -> '././_static/sphinxdoc.css'
2022-06-30T19:11:10.9212227Z '/tmp/pages-oW788h6erK/./_static/navigation.png' -> '././_static/navigation.png'
2022-06-30T19:11:10.9212484Z '/tmp/pages-oW788h6erK/./_static/nxdl_vocabulary.html' -> '././_static/nxdl_vocabulary.html'
2022-06-30T19:11:10.9212830Z '/tmp/pages-oW788h6erK/./_static/NeXusIntern.pdf' -> '././_static/NeXusIntern.pdf'
2022-06-30T19:11:10.9213087Z '/tmp/pages-oW788h6erK/./_static/nxdl_vocabulary.yml' -> '././_static/nxdl_vocabulary.yml'
```

So instead of 

```yaml
echo manual.nexusformat.org > ./build/manual/build/html/CNAME
```

then perhaps this will work:

```yaml
echo manual.nexusformat.org > ./CNAME
```

**Comment by woutdenolf** [comment]
[html_extra_path](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_extra_path) works locally (PR #1159) so hopefully CI will like it as well.

**Comment by woutdenolf** [comment]
Indeed. Seems ok now:

https://github.com/nexusformat/definitions/runs/7138369879?check_suite_focus=true

**Comment by woutdenolf** [comment]
I will do the same on the `dev_tools` branch.
