### ISSUE TITLE
Another contributions bug in the main branch

### ISSUE THREAD

**Issue by woutdenolf** [nexusformat/definitions#1162]
@prjemian @PeterC-DLS What should the "status" of a contributed definition be? At this point I'm using `dev_tools` to verify the main branch.

Current documentation

![image](https://user-images.githubusercontent.com/7264703/176772394-87646754-a924-4340-8330-f0cb00ae37da.png)

`main` branch

![image](https://user-images.githubusercontent.com/7264703/176772494-52cddaa4-f142-40b0-859f-7e0560ff67fc.png)

`dev_tools` branch

![image](https://user-images.githubusercontent.com/7264703/176772585-e9285f10-0012-45a2-bc0d-a2531c1af5a4.png)

**Comment by prjemian** [comment]
I like that it shows the category (base or app def) but feel that since contributed are in some probationary status, that seems like an additional part of the status.

- base class (contributed), extends [NXobject]
- application definition (contributed), extends [NXobject]

**Comment by woutdenolf** [comment]
I let @prjemian suggestion but propose first to do https://github.com/nexusformat/definitions/pull/1163 which put things back the way they were.

**Comment by prjemian** [comment]
My suggestion can wait until the next release.  It joins many such _nice things to have_ that will add delay to an immediate release.

**Comment by PeterC-DLS** [comment]
So revert to just category for time being?

**Comment by PeterC-DLS** [comment]
Ok, reassign to next milestone.
