### ISSUE TITLE
update CHANGES.rst for release v2022.06

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#1165]
- [x] update `/CHANGES.rst`
- [x] update [wiki release page](https://github.com/nexusformat/definitions/wiki/releasenotes__v2022.06)

**Comment by prjemian** [comment]
Revise the wiki page after the release.  It will include the final tag.

**Comment by prjemian** [comment]
@PeterC-DLS @benajamin @woutdenolf Anything we should highlight for this release?  Including 130 PRs, 101 Issues, 250 commits, summarizing is a challenge.  Perhaps mention it is the product of two Code Camps and ... ?

**Comment by prjemian** [comment]
See a machine-generated listing of changes: https://github.com/nexusformat/definitions/wiki/releasenotes__v2022.06

**Comment by prjemian** [comment]
FYI, here's the [command](https://github.com/prjemian/condatools/blob/main/create_release_notes.py) to generate that wiki page:

```bash
/home/prjemian/Documents/projects/prjemian/condatools/create_release_notes.py --head main v2020.10 "NXDL 2022.06" ${MY_OAUTH_KEY} | tee /tmp/notes.md
```

**Comment by prjemian** [comment]
Audience is NeXus community.

**Comment by prjemian** [comment]
wiki page is detailed summary, CHANGES.rst is high-level summary

**Comment by PeterC-DLS** [comment]
I think it's fair to add summary statistics of the changes.

**Comment by prjemian** [comment]
I'm thinking that Contributors includes names of those who are not NIAC members (since that is implied already).

**Comment by PeterC-DLS** [comment]
FAIRmat people?

**Comment by prjemian** [comment]
@sanbrock Can you provide a list of the contributors from the FAIRmat team?

**Comment by PeterC-DLS** [comment]
Diamond:
Tim Snow

**Comment by prjemian** [comment]
Another other additions?  I combed through the PRs, as [listed](https://github.com/nexusformat/definitions/wiki/releasenotes__v2022.06#pull-requests), and also through the contributors

**Comment by PeterC-DLS** [comment]
Don't see any changes from M Jones.
