### ISSUE TITLE
incident_polarisation_stokes should be optional

### ISSUE THREAD

**Issue by phyy-nx** [nexusformat/definitions#1173]
#858 makes "incident_polarisation_stokes" required (see [here](https://nexusformat.github.io/definitions/classes/applications/NXmx.html#nxmx-entry-instrument-beam-incident-polarisation-stokes-field)). I guess it should have been changed to `optional="true"`.

_Originally posted by @soph-dec in https://github.com/nexusformat/definitions/pull/858#discussion_r908271132_

**Comment by yayahjb** [comment]
Looks garbled., with stokes in twice, once required and deprecated and once
recommended.  Needs to be redone.
For any synchrotron some polarization should be required, but until more
people are willing to provide the full
set of Stokes parameters, I think we need to only require some form of
polarization and only recommend the
full set of 4 Stokes parameters.
