### ISSUE TITLE
Add H5Web to list of tools to view NeXus files

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#1186]
Note [H5Web](https://h5web.panosc.eu), a new extension for [Microsoft VisualStudio Code Editor](https://code.visualstudio.com/) to browse and visualize HDF5 files

Add it to this page and section:
https://manual.nexusformat.org/utilities.html#hdf-tools

**Comment by prjemian** [comment]
Note also [h5wasm](https://h5web.panosc.eu/h5wasm) which is a web site allowing one to view HDF5 content from a URL such as the [`simple_example_basic.nexus.hdf5` example](https://h5web.panosc.eu/h5wasm?url=https%3A%2F%2Fmanual.nexusformat.org%2F_downloads%2Fb9b76d34af0f606d0e0958a234054608%2Fsimple_example_basic.nexus.hdf5) from the [NeXus manual](https://manual.nexusformat.org/examples/h5py/simple_example_basic/index.html).

https://h5web.panosc.eu/h5wasm?url=https%3A%2F%2Fmanual.nexusformat.org%2F_downloads%2Fb9b76d34af0f606d0e0958a234054608%2Fsimple_example_basic.nexus.hdf5

**Comment by axelboc** [comment]
Hi @prjemian, I just came across #1189 and, as a core developer of H5Web, I wanted to clarify that H5Web and `h5wasm` are two distinct projects.

[H5Web](https://github.com/silx-kit/h5web) is a web toolkit for exploring and visualising HDF5 files and, more generally, for visualizing data. It is based on React and WebGL.

H5Web's viewer component (available via npm package `@h5web/app`) indeed supports some NeXus features including plotting `NXdata` groups (signal, axis, errors, etc.) and finding a `default` plot. It can pull hierarchical data from various sources, including:

- back-end solutions for serving HDF5 files through the web, like [h5grove](https://github.com/silx-kit/h5grove/) or [HSDS](https://github.com/HDFGroup/hsds);
- [h5wasm](https://github.com/usnistgov/h5wasm), a WebAssembly port of the HDF5 C library, which allows reading and writing HDF5 files from JavaScript (i.e. no need for a back-end server at all).

H5Web's [demo site](https://h5web.panosc.eu/), including the [`H5WasmProvider` demo](https://h5web.panosc.eu/h5wasm), is just to show these three "data providers" in action. I recommend you instead point to the following projects that make use of H5Web:

- the [VSCode extension](https://github.com/silx-kit/vscode-h5web), which you already point to, and which uses `h5wasm` under the hood;
- the [JupyterLab extension](https://github.com/silx-kit/jupyterlab-h5web).

For your information, we're currently working on a stand-alone web application similar to https://h5web.panosc.eu/h5wasm, but with more features, and a more stable, production-grade deployment environment. I'll report back here when it's ready for prime-time.

**Comment by prjemian** [comment]
@axelboc This is great!  Thanks for the contribution and thanks for the new tools!

**Comment by prjemian** [comment]
Here's a screen view of how that would appear:

![view1](https://user-images.githubusercontent.com/2279984/190213604-ee41e109-08cd-48ad-b914-348dac75b329.png)

**Comment by axelboc** [comment]
Nice, yeah this is great! I would maybe just either condense or reorder/reword the last two bullet points:

- [H5Web demonstration site](https://h5web.panosc.eu/)
- `h5wasm` demo with a NeXus file: [simple_example_basic.nexus.hdf5](https://h5web.panosc.eu/h5wasm?url=https%3A%2F%2Fmanual.nexusformat.org%2F_downloads%2Fb9b76d34af0f606d0e0958a234054608%2Fsimple_example_basic.nexus.hdf5)

**Comment by loichuder** [comment]
Thanks for the ping :ping_pong: 

Looks good to me except for the `h5wasm` bullet point in the list. I would skip it as it feels wrong to me to say that `h5wasm` makes use of `H5Web` (it is rather the other way round: `H5Web` makes use of `h5wasm` for several things like the VSCode extension).

Other than that, great summary :+1:

**Comment by axelboc** [comment]
Yeah `h5wasm` probably deserves its own section. @prjemian, you can maybe put it before the H5Web section so you can still mention `h5wasm` in the bullet point with the NeXus file demo?

**Comment by prjemian** [comment]
h5wasm first, then H5Web.  Also, the on-line visualization demo should be grouped with `h5wasm`, which is separated from H5Web?  How about this?

![screen](https://user-images.githubusercontent.com/2279984/190396105-9a70909d-da34-4b7a-9656-b78b5a832fe7.png)

**Comment by prjemian** [comment]
Note that I inserted h5wasm into the description of H5Web.

```
It is based on h5wasm, React, and WebGL.
               ^^^^^^^^
```

**Comment by prjemian** [comment]
WebAssembly: https://webassembly.org/ ?

**Comment by loichuder** [comment]
Looks better with a separate section for `h5wasm` !

Here are my suggestions:
- The on-line visualization demo is made with H5Web (with `h5wasm` under the hood) so I think it is best to leave it in H5Web. `h5wasm` simply needs to be mentioned. Something like:
> On-line visualization with NeXus file (using `h5wasm): _link_
----
> Note that I inserted h5wasm into the description of H5Web.

- I don't think this is right. `h5wasm` is not _per se_ a building block of the project as is React or WebGL. Having
> It is based on React, and WebGL.

is fine

----
Note that there is a typo in `vscode-h5web`

---
> WebAssembly: https://webassembly.org/ ?

Yep !

Thanks for bearing with this :wink:

**Comment by prjemian** [comment]
I like this much better.  Thanks for the contributions!

**Comment by axelboc** [comment]
Thank you for adding H5Web to the list!
