### ISSUE TITLE
Inconsistency in using of "on-page" content and links

### ISSUE THREAD

**Issue by BalazsBago** [nexusformat/definitions#1191]
https://manual.nexusformat.org/examples/h5py/index.html#python-examples-using-h5py
The 2.1.2.1. uses links to the examples, however other sections on this page explain the examples on this page.

**Comment by benajamin** [comment]
This is pointing out messy documentation and doesn't need a decision from the NIAC.

**Comment by woutdenolf** [comment]
This part of the documentation has been completely refactored. I believe https://github.com/nexusformat/definitions/pull/1060 solved this.

**Comment by prjemian** [comment]
I also agree with this.  Closing now.
