### ISSUE TITLE
Missing closing parentheses in rendering of suggested target of linkType

### ISSUE THREAD

**Issue by PeterC-DLS** [nexusformat/definitions#1192]
See for example, [NXdata/energy](https://manual.nexusformat.org/classes/applications/NXxas.html#nxxas-entry-data-energy-link) and [NXdata/absorbed_beam](https://manual.nexusformat.org/classes/applications/NXxas.html#nxxas-entry-data-absorbed-beam-link)

**Comment by prjemian** [comment]
```bash
(bluesky_2022_3) prjemian@zap:~/.../NeXus/definitions$ git grep "suggested target"
dev_tools/docs/nxdl.py:                f"(suggested target: ``{node.get('target')}``"
```

**Comment by prjemian** [comment]
@PeterC-DLS Good catch!
