### ISSUE TITLE
Invalid units

### ISSUE THREAD

**Issue by TLCFEM** [nexusformat/definitions#1204]
https://github.com/nexusformat/definitions/blob/ea89964a412206b31e0b754bf95fad8e53f9650e/contributed_definitions/NXxpcs.nxdl.xml#L195

`units=NX_INT` is not  a valid token for dimensionality. Guess it shall be `NX_COUNT` or something else.

**Comment by prjemian** [comment]
Thanks for reporting this!  Yes, that's an oversight.  Probably `NX_NUMBER` to allow for int or float.

**Comment by PeterC-DLS** [comment]
Also `G2_unnormalized` on [L180](https://github.com/nexusformat/definitions/blob/ea89964a412206b31e0b754bf95fad8e53f9650e/contributed_definitions/NXxpcs.nxdl.xml#L180) should not be dimensionless but `NX_ANY`

**Comment by prjemian** [comment]
@PeterC-DLS I agree.  Without the denominator, the units no longer cancel.
