### ISSUE TITLE
NXdata - @signal doc confusing

### ISSUE THREAD

**Issue by woutdenolf** [nexusformat/definitions#1209]
https://github.com/nexusformat/definitions/blob/6015a47a1afe792926c4c011f3a089d4e110bb8a/base_classes/NXdata.nxdl.xml#L65-L74

1. So the sentence `The value names an existing child of this group.` means that `The value is equal to the name of field which is the direct child of this group.`? (The fact that this child must exist is clear enough imo)
2. This also applies to @auxiliary_signals and @axes?
3. What does `The child group must itself be a NeXus group` mean?

I'm asking because some people interpret the docs as allowing `@signal` to contain a relative path to a field. We had an h5web [bug report](https://github.com/silx-kit/h5web/issues/1212) because of it. As far as I understand, this is not allowed:

```
data:NXdata
  @signal = "mygroup/mydata"
  mygroup
    mydata: float[100]
```

I suspect `The child group must itself be a NeXus group` may cause the confusion.

**Comment by woutdenolf** [comment]
It seems this sentence was introduced a few months ago: https://github.com/nexusformat/definitions/pull/1022/files

@prjemian this seems like a copy&paste error right?

**Comment by PeterC-DLS** [comment]
> It seems `The child group must itself be a NeXus group` was introduced a few months ago: https://github.com/nexusformat/definitions/pull/1022/files

This was https://github.com/nexusformat/definitions/pull/1022/commits/4c5d50e1ff1295c542e02e933a24be40042fd88c and replaced:
> A field of this name *must* exist (either as a NeXus field or as a link to a NeXus field).
	The value must match the :ref:`regular expression pattern for NXDL
	group and field names &lt;validItemName>`.

**Comment by PeterC-DLS** [comment]
So I suggest you need to mention a link to a field is permitted and that field must be (why?) in a NeXus group.

**Comment by woutdenolf** [comment]
Indeed I don't see why the link destination should be inside a NeXus group. It would prevent the use of [external](https://docs.h5py.org/en/stable/high/dataset.html#h5py.Dataset.external) data for no good reason.
