### ISSUE TITLE
NXdetector readout orientation

### ISSUE THREAD

**Issue by wakonig** [nexusformat/definitions#1211]
Hi all,
Depending on the software used for the detector readout, the data within NXdetector is saved with a specific orientation. 
To document the orientation I'm just using a separate group "orientation" for now:
```xml
<group name="orientation">
  <dataset name="transpose" value="1" />
  <dataset name="rot90" value="3" />
  <attribute name="description" value="Orientation defines the number of counterclockwise rotations by 90 deg followed by a transposition to reach the 'cameraman orientation', that is looking towards the beam." />
</group>
```
Is there a standardised way of documenting the readout orientation? If not, would this be something one could standardise in the future?

**Comment by zjttoefs** [comment]
The detector x and y coordinates are the fast and slow readout dimensions. I don't think this is needed, but it can be covered by the standard geometry placement, unless I am mistaken.

**Comment by PeterC-DLS** [comment]
By row-major storage and NeXus coordinate frame conventions, an area detector data field should have a shape of `(slow, fast)` where the `fast` dimension is along a row (i.e. X) of pixels on the detector. Usually, the (0,0) pixel is at the upper left corner when viewing the detector face from the sample. If the detector is not in this orientation then use `NXdetector_module` and its `fast/slow_pixel_direction` fields to specify it.

**Comment by wakonig** [comment]
Thanks a lot for the info! I'll have a closer look at the `NXdetector_module` then.
