### ISSUE TITLE
Apparent advice loop: NXaperture and NXslit

### ISSUE THREAD

**Issue by paulmillar** [nexusformat/definitions#1231]
I noted that the definition of `NXaperture` says:
> A beamline aperture. This group is deprecated, use NXslit instead

while the definition of `NXslit` says:
> A simple slit. For more complex geometries, `NXaperture` should be used.

This appears (to me) to be a loop, leaving it unclear how to represent "complex" geometries.

**Comment by benajamin** [comment]
I suspect that this is a mistake and it `NXslit` that was meant to be deprecated.

**Comment by phyy-nx** [comment]
See b5ed52b1edac60b4e8ccddcb376d569f0e52cdfb

**Comment by phyy-nx** [comment]
From Telco Jan 17 2024

- Undeprecate NXaperture and clarify the reason why (it was probably documented as deprecated by mistake, and it remains in common usage in various NXbase classes and application definitions) (this is a documentation bug but vote anyway, @phyy-nx)
- Add a field SHAPE of class NXoff_geometry (addition to base class needs a vote, @phyy-nx)
- Fix typo, extra "*" at the end of the NOTE field (@prjemian)
