### ISSUE TITLE
units= vs. units=

### ISSUE THREAD

**Issue by sanbrock** [nexusformat/definitions#1237]
As an xml tag, units= is used by NXDL to specify unit categories for Fields. units= on the other hand can be used by application definitions to specify enumeration for the dataset attribute @units which specify the actual unit of the data.  
It is at least confusing in NeXus that both a unit category specification and a specific unit in a data file use the same plural form “units”.  
Was it ever discussed?  
Should not it be made clear: “units” for unit categories, and “unit” for the actual unit?

**Comment by prjemian** [comment]
There was a decision to use the plural form: `units`.  Such a distinction between when to use one or the other form contributes to complexity in the standard. This decision might predate any meeting notes.
