### ISSUE TITLE
Make list of maintainers for application definitions

### ISSUE THREAD

**Issue by phyy-nx** [nexusformat/definitions#1254]
One of the ideas that came out of the April 2023 telco ([minutes](https://www.nexusformat.org/Telco_20230419.html)), during discussion of #1011, was that it would be a good idea to add "maintainers" to application definitions.  These would be people who are most interested in guiding the maintenance and development of a given definition, or have an interest in it as a community member, or were long time contributors to it and can guide new users in its use or answer questions.  Critically, they wouldn't need to be NIAC members.

I'm happy to set this up, my question is, where should it live?

Proposals:

1. Add lists of application definitions to NIAC members on the [NIAC](https://www.nexusformat.org/NIAC.html#current-members) web page.
2. Add contact information (github handles?) to the [list of application definitions](https://manual.nexusformat.org/classes/applications/index.html)
3. Add contact information (github handles?) to individual definitions.  Perhaps in the the form of a new attribute or field?  Or in the doc string?

Or some combination of the above.  Thoughts on this?  Thanks!

**Comment by zjttoefs** [comment]
I'm opposed to that idea. 
* The interest of people often follows their facility lifecycle. But taking over someone's baby will always be seen as somewhat hostile, even if that baby has been a little neglected.
* What would being a "maintainer" mean in practice? Can you make changes without review by NIAC?
* In practice you can check the gitlogs to see who has been editing a file last, if you need a second opinion on something.

**Comment by rayosborn** [comment]
@zjttoefs, it's possible that "maintainer" is the wrong word, but I think it is essential that there is a point-of-contact for each active application definition, one who is aware of its history and current status and can respond to questions. There are several ADs that were thrown together a long time ago (I'm sure I contributed to at least one) but have never been properly validated by the community and sometimes never used. However, a newcomer would assume that use of this definition is mandatory, even if it is inadequate to their needs. It is like coming across a PyPI package that hasn't been updated in ten years or more, whose original author is unreachable. Would you use it?

**Comment by phyy-nx** [comment]
I can see nervousness around scope here and I agree I'm not quite sold on the word maintainer.  "Helpful explainer" is more the vibe I was going for.  But one additional point for @zjttoefs is that for probably most users of NeXus not related to this committee, the github page for eg [NXmx](https://github.com/nexusformat/definitions/blob/main/applications/NXmx.nxdl.xml), which has 11 contributors, is completely hidden compared to the [manual page](https://manual.nexusformat.org/classes/applications/NXmx.html#nxmx), which has no point of contact listed.

**Comment by prjemian** [comment]
I'm thinking `contact` might convey the meaning we want. Could modify it
such as `NeXus contact` and `science contact` to identify different roles.

**Comment by phyy-nx** [comment]
Compromises discussed in Code Camp: take advantage of the side bar space on the right hand of the page and add one or more of the following under the "This Page" heading

- "Ask for help": links to open a new issue (https://github.com/nexusformat/definitions/issues/new)
- Add 'microcredits' (thanks @mkuehbach), e. g. a list of github handles that have contributed, like this:

![image](https://github.com/nexusformat/definitions/assets/13471434/9c7c2848-9fc3-4398-a9ef-81c9df2ff3f0)

Thoughts?

**Comment by prjemian** [comment]
> side bar space on the right hand of the page

Which page?  Can you give an example?

**Comment by phyy-nx** [comment]
Ya, here's a screenshot of where I mean:

![image](https://github.com/nexusformat/definitions/assets/13471434/4d01807a-c642-4d53-b5f4-4ba649ac8666)
