### ISSUE TITLE
Impatient guide is not accessible via https://manual.nexusformat.org/impatient/

### ISSUE THREAD

**Issue by PeterC-DLS** [nexusformat/definitions#1257]
The impatient guide "NeXus for the Impatient" is linked from https://manual.nexusformat.org/index.html is not accesible and, also, hasn't had its release/version year updated since 2016.

**Comment by woutdenolf** [comment]
If you want to deploy, you need to trigger a workflow manually with `deploy=true`.

**Comment by woutdenolf** [comment]
Check the deploy box here: 

![image](https://github.com/nexusformat/definitions/assets/7264703/3e0620be-8466-4ace-b31a-c69473fff618)

**Comment by PeterC-DLS** [comment]
Works with #1294
