### ISSUE TITLE
incident_wavelength_spectrum group(???) in NXmx

### ISSUE THREAD

**Issue by Gigarrum** [nexusformat/definitions#1264]
There is a group inside [NXmx](https://manual.nexusformat.org/classes/applications/NXmx.html#nxmx) application definition called **incident_wavelength_spectrum** which, according to the docs is a [NXdata](https://manual.nexusformat.org/classes/base_classes/NXdata.html#nxdata) group. The following topics are regards about it:

1. A documentation for it is missing
2. Should it really be a [NXData](https://manual.nexusformat.org/classes/base_classes/NXdata.html#nxdata) group? I am really confused on why it is a NXdata group and not a field instead. 
3. That group is inside [NXBeam](https://manual.nexusformat.org/classes/base_classes/NXbeam.html#nxbeam) scope in the appplication definition but there is no definition for it inside [NXBeam](https://manual.nexusformat.org/classes/base_classes/NXbeam.html#nxbeam). Should it be part of [NXBeam](https://manual.nexusformat.org/classes/base_classes/NXbeam.html#nxbeam) class definition or it is only a [NXmx](https://manual.nexusformat.org/classes/applications/NXmx.html#nxmx)  specific requirement?

**Comment by phyy-nx** [comment]
Discussion from Code Camp:

- Proposed documentation: "this group is intended for use cases that do not fit the incident_wavelength and incident_wavelength_weights fields above, perhaps for example a 2D spectrometer."
- Do a fix of `shot- to-shot` spacing while we are at it
- Regarding specific questions, it's an NXdata group to allow a variety of use cases and at present is only specified for NXmx.
