### ISSUE TITLE
Bug when clicking on "Quick search" text box 

### ISSUE THREAD

**Issue by Gigarrum** [nexusformat/definitions#1301]
User is being redirected to the contributor Github profile page when clicking the "Quick search" text box in a base class, application definition or contributed definition documentation page.

**Comment by PeterC-DLS** [comment]
It may be an off-by-one error. In [NXaperture](https://manual.nexusformat.org/classes/base_classes/NXaperture.html#nxaperture), the link points to the last contributor.
