### ISSUE TITLE
Recommended class to store Beam Visualization System (BVS)

### ISSUE THREAD

**Issue by Gigarrum** [nexusformat/definitions#1302]
Recently I was talking with one developer from one of our beamline here and he told me they collected some data from some BVS and store it. NeXus currently don't have a specific class for this type of device and I was wondering which is the recommended class to use for this type of device at the moment. Additionally, do you think it would be useful to create a new contributed definition for it or there is no need for such a specific class and a more generic can handle this?

**Comment by yayahjb** [comment]
I agree with Pete.  A beam monitor and a beam visualization system each
would fit nicely as an application definition built on the NXdetector base
class

.

**Comment by Gigarrum** [comment]
Totally agree with you @prjemian and @yayahjb! I was being too close minded about the detector class... In my head I was translating NXdetector as an Area Detector, which is totally wrong by my part! 

Closing the issue.

Thank you both!
