### ISSUE TITLE
Make countrate_correction_lookup_table optional in NXmx?

### ISSUE THREAD

**Issue by phyy-nx** [nexusformat/definitions#1310]
As pointed out to me by @biochem-fan, [`countrate_correction_lookup_table`](https://manual.nexusformat.org/classes/applications/NXmx.html#nxmx-entry-instrument-detector-countrate-correction-lookup-table-field) is not applicable to CCDs so it doesn't make sense to make it a required attribute.  I suppose this similarly applies to [`countrate_correction_applied`](https://manual.nexusformat.org/classes/applications/NXmx.html#nxmx-entry-instrument-detector-countrate-correction-applied-field).  These NXdetector fields were added as required to NXmx in #975.

**Comment by soph-dec** [comment]
I think the fact that the `countrate_correction_lookup_table` is required was a simple oversight by me (in NXdetector, not specifying makes a field optional, while in NXmx, it defaults to required). It does not make much sense to have it required since `countrate_correction_applied` is optional.
