### ISSUE TITLE
What does it mean to have an `maxOccurs=unbounded` `nameType=specified`?

### ISSUE THREAD

**Issue by ndevenish** [nexusformat/definitions#1401]
e.g.
https://github.com/nexusformat/definitions/blob/69f92a320f15effe29e11237fcf2cad6674f55c3/base_classes/NXparameters.nxdl.xml#L30-L34

This reads as - the field must be named `term`, but there can be several of them?

Similarly, there are fields with `maxOccurs=1` and `nameType=any`, e.g.
https://github.com/nexusformat/definitions/blob/69f92a320f15effe29e11237fcf2cad6674f55c3/base_classes/NXtransformations.nxdl.xml#L187

although I think I sort of see what is being gone for here - that the name is technically specified, because it's intended to be based off the name of another parameter. Except it seems more technically correct to say that there can be multiple instances of this field (otherwise, you seem to be saying "you can have many AXIS but only one of them can have an AXISNAME_end").

**Comment by ndevenish** [comment]
That'd make the documentation consistent but Isn't it still inconsistent in the programmatic model without `nameType="any"` (which I believe most other CAPS-names are).

And, with the `AXISNAME_end` example, possibly `maxOccurs="unbounded"` was intended but is missing?

**Comment by prjemian** [comment]
@ndevenish - How does this look now?

@woutdenolf - Thanks for the review.  There were additional changes so I recycled your approval.

**Comment by ndevenish** [comment]
Actually, I think that I'm remembering the group-rules and mentally applying them to fields. It probably makes sense to do this, but I'm not sure it's a consistent "rule" to follow.

So, I think it makes sense for consistently to use it here.

It looks like there has been some attempt to use these in the pase. The _fields_ in base_definitions with CAPS are:
```
NXdata.AXISNAME
NXdata.DATA
NXdata.FIELDNAME_errors
NXtransformations.AXISNAME
NXtransformations.AXISNAME_end
NXtransformations.AXISNAME_increment_set

# And these, which look not to apply to this discussion)
NXsample.external_DAC
NXuser.ORCID
```
These have `nameType="any"`:
```
NXdata.AXISNAME
NXdata.DATA
NXdata.FIELDNAME_errors
NXtransformations.AXISNAME
NXtransformations.AXISNAME_end
NXtransformations.AXISNAME_increment_set
```
And actually only the following are marked "unbounded":
```
NXparameters.term
NXtransformations.AXISNAME
```

Perhaps everything else should be made explicit, but the "consistent rule" seems to be "assume nameType=any implies unbounded.

So, `term` is the only one in the base_definitions with `nameType=specific` and `maxOccurs=unbounded`.

Thus, `nameType="any"` is probably the change for consistency (but perhaps something should note that this implies unbounded, somewhere).
