### ISSUE TITLE
support for multi-format files

### ISSUE THREAD

**Issue by jkotan** [nexusformat/definitions#1429]
I would like to ask if NeXus standard allows to create multi-format files i.e. an HDF5 file which contains e.g. two data format  where one is a NeXus file ?  
That would allow to  create one file  without duplication of the data which can be read by various format views.
In principle one could do it by denoting the other format metadata group as NXcollection bellow NXroot level to be unvalidated  by NeXus validators. 
However, the NXcollection is often use to describe beamline components not defined in NeXus and in some facilities it is used only for those purpose. 
Therefore, I would like to ask if there is another "unvalidated" NX_class where external format could be stored or one need to store such information in a group below  NXroot without any class.

**Comment by prjemian** [comment]
NeXus adds an attribute `NX_class` to each group in a "NeXus" file.  This attribute states the name of the NeXus class that standardizes its contents.  NeXus also controls the naming of such classes, as described in the ["datarules"](https://manual.nexusformat.org/datarules.html).

That said, I'm not aware of a rule that states a file cannot contain non-NeXus groups (data exchange, some other schema, or *ad hoc*) at the root level.  To avoid problems with such groups past the `NXentry` group, use NXcollection.  NeXus validation rules do not allow NXcollection at the root level.  NXentry is the only NeXus group allowed at root level.  This is in the NXDL for the NXroot class.

HDF5 hard links can be used to co-locate content (avoid duplication) as-desired, as long as the applicable rules for that content are satisfied.

> NXcollection is often used to describe beamline components not defined in NeXus and in some facilities it is used only for those purpose ...

This is limited convention of some facilities has not been endorsed by the NIAC.  NXcollection was created to hold any type of non-NeXus content.  Period.  No need for an additional class.

**Comment by prjemian** [comment]
See also:

- #1387

**Comment by jkotan** [comment]
@prjemian, thank you for your answer.
