### ISSUE TITLE
UPPER case notation

### ISSUE THREAD

**Issue by sanbrock** [nexusformat/definitions#1436]

**Comment by tacaswell** [comment]
```
@ ack '(field|group) name="[^"]*[A-Z]+"' --xml
applications/NXcanSAS.nxdl.xml
281:      <field name="Q" type="NX_NUMBER" units="NX_PER_LENGTH">
428:      <field name="I" type="NX_NUMBER">
851:        <field name="SDD" type="NX_NUMBER" units="NX_LENGTH" minOccurs="0" maxOccurs="1">
1190:    <group name="TRANSMISSION_SPECTRUM" type="NXdata" minOccurs="0">
1248:      <field name="T" type="NX_NUMBER" units="NX_DIMENSIONLESS">

base_classes/NXaperture.nxdl.xml
81:    <group name="BLADE_GEOMETRY" type="NXgeometry" deprecated="Use :ref:`NXoff_geometry` instead to describe the shape of the aperture">

base_classes/NXbeam.nxdl.xml
284:        <field name="DIRECTION" nameType="any" units="NX_TRANSFORMATION" type="NX_NUMBER">

base_classes/NXdata.nxdl.xml
342:	<field name="AXISNAME" type="NX_CHAR_OR_NUMBER" nameType="any">
380:	<field name="DATA" type="NX_NUMBER" nameType="any">

base_classes/NXparameters.nxdl.xml
30:    <field name="TERM" minOccurs="0" maxOccurs="unbounded" nameType="any">

base_classes/NXsample.nxdl.xml
351:	<field name="external_DAC" type="NX_FLOAT" units="NX_ANY">
354:	<group name="external_ADC" type="NXlog">

base_classes/NXtransformations.nxdl.xml
112:	<field name="AXISNAME" nameType="any" units="NX_TRANSFORMATION" type="NX_NUMBER" maxOccurs="unbounded">

base_classes/NXuser.nxdl.xml
69:	<field name="ORCID">

contributed_definitions/NXapm.nxdl.xml
494:                <group name="ION" type="NXion" minOccurs="1" maxOccurs="118">
684:            <group name="TRANSFORMATIONS" type="NXtransformations" minOccurs="0" maxOccurs="unbounded"/>
866:                <group name="SOURCE" type="NXsource" minOccurs="0" maxOccurs="2">

contributed_definitions/NXapm_paraprobe_config_intersector.nxdl.xml
94:        <group name="VOLUME_VOLUME_SPATIAL_CORRELATION" type="NXprocess" minOccurs="1" maxOccurs="unbounded">
217:                <group name="FEATURE" type="NXcollection" minOccurs="1" maxOccurs="4">
297:                <group name="FEATURE" type="NXcollection" minOccurs="1" maxOccurs="4">

contributed_definitions/NXapm_paraprobe_results_clusterer.nxdl.xml
223:                <group name="dbscanID" type="NXsimilarity_grouping" minOccurs="0" maxOccurs="unbounded">

contributed_definitions/NXapm_paraprobe_results_intersector.nxdl.xml
177:            <group name="VOLUME_VOLUME_SPATIAL_CORRELATION" type="NXprocess" minOccurs="0" maxOccurs="1">

contributed_definitions/NXapm_paraprobe_results_nanochem.nxdl.xml
248:                <group name="DELOCALIZATION" type="NXdelocalization">
1175:                                            <group name="ION" type="NXion" minOccurs="0" maxOccurs="unbounded">
1191:                                        <group name="objectID" type="NXcg_polyhedron_set" minOccurs="0" maxOccurs="unbounded">
1263:                                            <group name="ION" type="NXion" minOccurs="0" maxOccurs="unbounded">
1279:                                        <group name="objectID" type="NXcg_polyhedron_set" minOccurs="0" maxOccurs="unbounded">
1376:                                            <group name="ION" type="NXion" minOccurs="0" maxOccurs="unbounded">
1391:                                        <group name="objectID" type="NXcg_polyhedron_set" minOccurs="0" maxOccurs="unbounded">
1463:                                            <group name="ION" type="NXion" minOccurs="0" maxOccurs="unbounded">
1478:                                        <group name="objectID" type="NXcg_polyhedron_set" minOccurs="0" maxOccurs="unbounded">
1571:                <group name="MESH_CURR_PRE_DCOM_STEP" type="NXcg_triangle_set" minOccurs="0" maxOccurs="unbounded">
1690:                <group name="MESH_CURR_POST_DCOM_STEP" type="NXcg_triangle_set" minOccurs="0" maxOccurs="unbounded">
1872:                    <group name="ROI" type="NXcollection" minOccurs="0" maxOccurs="unbounded">

contributed_definitions/NXapm_paraprobe_results_ranger.nxdl.xml
188:                <group name="ION" type="NXion" minOccurs="1" maxOccurs="256">
341:                <group name="charged_ION" type="NXion" minOccurs="1" maxOccurs="256">

contributed_definitions/NXapm_paraprobe_results_surfacer.nxdl.xml
224:            <group name="POINT_SET_WRAPPING" type="NXprocess" minOccurs="0" maxOccurs="unbounded">
420:            <group name="TRIANGLE_SET_WRAPPING" type="NXprocess" minOccurs="0" maxOccurs="unbounded">

contributed_definitions/NXbeam_path.nxdl.xml
73:        <field name="AXISNAME" type="NX_NUMBER" units="NX_TRANSFORMATION">
229:    <group name="aperture_NUMBER" type="NXaperture">
235:    <group name="window_NUMBER" type="NXaperture">
283:    <group name="filter_NUMBER" type="NXfilter"/>

contributed_definitions/NXcg_roi_set.nxdl.xml
34:    <group name="CG_SPHERE_SET" type="NXcg_sphere_set"/>
35:    <group name="CG_ELLIPSOID_SET" type="NXcg_ellipsoid_set"/>
36:    <group name="CG_CYLINDER_SET" type="NXcg_cylinder_set"/>
37:    <group name="CG_POLYHEDRON_SET" type="NXcg_polyhedron_set"/>

contributed_definitions/NXchemical_composition.nxdl.xml
50:    <group name="ION" type="NXion">

contributed_definitions/NXcorrector_cs.nxdl.xml
54:    <group name="ZEMLIN_TABLEAU" type="NXprocess">

contributed_definitions/NXdispersive_material.nxdl.xml
107:        <group name="REFERENCES" type="NXcite" recommended="true">

contributed_definitions/NXem.nxdl.xml
671:            <group name="TRANSFORMATIONS" type="NXtransformations" minOccurs="0" maxOccurs="unbounded"/>
782:                    <group name="ZEMLIN_TABLEAU" type="NXprocess" recommended="true">
1086:            <group name="EBEAM_DEFLECTOR" type="NXscanbox_em" minOccurs="0" maxOccurs="unbounded">
1094:            <group name="IBEAM_DEFLECTOR" type="NXscanbox_em" minOccurs="0" maxOccurs="unbounded">
1117:            <group name="DETECTOR" type="NXdetector" minOccurs="1" maxOccurs="unbounded">
1305:                <group name="IMAGE_SET" type="NXimage_set" optional="true">
1349:                <group name="SPECTRUM_SET" type="NXspectrum_set" optional="true">
1532:                        <group name="ELEMENTNAME" type="NXprocess" minOccurs="1" maxOccurs="256">
1724:                            <group name="ZEMLIN_TABLEAU" type="NXprocess" recommended="true">

contributed_definitions/NXlab_electro_chemo_mechanical_preparation.nxdl.xml
51:        <group name="SAMPLE" type="NXsample" minOccurs="1" maxOccurs="1"/>
52:        <group name="USER" type="NXuser" minOccurs="1" maxOccurs="unbounded"/>
59:        <group name="GRINDING_STEP" type="NXprocess">
180:        <group name="CLEANING_STEP" type="NXprocess">

contributed_definitions/NXlab_sample_mounting.nxdl.xml
48:        <group name="SAMPLE" type="NXsample" minOccurs="1" maxOccurs="1"/>
49:        <group name="USER" type="NXuser" minOccurs="1" maxOccurs="unbounded"/>

contributed_definitions/NXlens_opt.nxdl.xml
106:    <group name="COATING" type="NXsample">
170:    <field name="curvature_radius_FACE" type="NX_NUMBER" recommended="true" units="NX_LENGTH">

contributed_definitions/NXms.nxdl.xml
124:        <group name="PROGRAM" type="NXprogram" minOccurs="1" maxOccurs="unbounded">
151:        <group name="USER" type="NXuser" minOccurs="0" maxOccurs="unbounded">
251:            <group name="TRANSFORMATIONS" type="NXtransformations" minOccurs="3" maxOccurs="unbounded"/>
279:        <group name="ROI_SET" type="NXcg_roi_set" minOccurs="1" maxOccurs="unbounded">
369:                <group name="MS_SNAPSHOT" type="NXms_snapshot">
396:                    <group name="MS_FEATURE_SET" type="NXms_feature_set" minOccurs="0" maxOccurs="unbounded">
451:                            <group name="TRANSFORMATIONS" type="NXtransformations">

contributed_definitions/NXms_score_config.nxdl.xml
59:        <group name="PROGRAM" type="NXprogram">

contributed_definitions/NXms_score_results.nxdl.xml
129:        <group name="PROGRAM" type="NXprogram" minOccurs="1" maxOccurs="unbounded">
186:        <group name="USER" type="NXuser" minOccurs="0" maxOccurs="unbounded">
286:            <group name="TRANSFORMATIONS" type="NXtransformations" minOccurs="3" maxOccurs="unbounded"/>
314:        <group name="ROI_SET" type="NXcg_roi_set" minOccurs="1" maxOccurs="unbounded">
429:                <group name="MS_SNAPSHOT" type="NXms_snapshot">

contributed_definitions/NXopt.nxdl.xml
366:                    <group name="PARAMETER" type="NXsensor" optional="true">
470:                <group name="WINDOW" type="NXaperture" optional="true">

contributed_definitions/NXpolarizer_opt.nxdl.xml
182:    <group name="COATING" type="NXsample">

contributed_definitions/NXspectrum_set_em_xray.nxdl.xml
232:        <group name="ELEMENTNAME" type="NXprocess">

```

**Comment by prjemian** [comment]
Speaking for NXcansas, the use of `"Q"` and `"I"` mean that **exactly** those names must be used. How can this be expressed in NXDL?

**Comment by prjemian** [comment]
So we need a `flexible_name="true"` attribute for groups and fields to mark
a name as flexible? Default would be false.

**Comment by prjemian** [comment]
On second thought, same idea but invert the logic. Apply a new
`"exact_name=false"` attribute for a name that is flexible. Default is true.

**Comment by phyy-nx** [comment]
Usages of uppercase as a convention in NeXus

- FIELDNAME_errors in NXdata
- AXISNAME in NXtransformations,  NXdetector and NXdata
- DATA in NXdata
- base class names in when name= is not defined (eg INSTRUMENT, SAMPLE, etc.)
- nameType="any"
- FIELDNAME_scaling_factor and FIELDNAME_offset in NXdata
- [Reserved prefixes](https://manual.nexusformat.org/datarules.html#reserved-prefixes), which cannot be substituted
- "It is recognized that some facilities will construct data files with group and field names with upper case letters or start names with a number or include a period in a name." ([source](https://manual.nexusformat.org/datarules.html#regexpname))
- Specific field names exactly in uppercase  (eg "Q" and "I" above)
- "The actual names of the [DATA](https://manual.nexusformat.org/classes/base_classes/NXdata.html#nxdata-data-field) and [AXISNAME](https://manual.nexusformat.org/classes/base_classes/NXdata.html#nxdata-axisname-field) fields can be chosen [freely](https://manual.nexusformat.org/datarules.html#validitemname), as indicated by the upper case (this is a common convention in all NeXus classes)."  ([source](https://manual.nexusformat.org/classes/base_classes/NXdata.html#nxdata))

**Comment by PeterC-DLS** [comment]
`$ egrep -r 'name="[A-Z]{4,}' base_classes/ contributed_definitions/ ` will get a list...

**Comment by prjemian** [comment]
And implemented by #411 in [`nxdl.xsd`](https://github.com/nexusformat/definitions/blob/9059815e131dd308677d01da793b63f9d214dbb3/nxdl.xsd#L916-L930):

![image](https://github.com/user-attachments/assets/a6908df4-a18b-41c1-8b33-27944ab0d26d)

**Comment by tacaswell** [comment]
A proposal:

 - add "templated" as a valid value of `nameType`
 - add new attribute of "nameTemplates" which is a comma separated list of the substrings that can be templated


Alternately, we could use some escaping (`{}` or `||` or ....) to mark the substrings.

**Comment by prjemian** [comment]
The work remaining to close this issue is to review (list here) existing NXDL files.  Separate issues can be opened to resolve each.  If we try to change them all in this one issue, it could take considerable time to finish reviews and the changes could trigger merge conflicts with existing branches.

**Comment by prjemian** [comment]
Templating adds a new complexity.  Is there an advantage that is not available in the existing naming rules?

**Comment by tacaswell** [comment]
It is explicit rather than implicit.

**Comment by phyy-nx** [comment]
Use cases:

- Exact name (upper/lower)
- Full substitution with any string if nameType=any or if name is not specified
- Partial substitution by user or application definition

Proposal:

1. Keep nameType=specified as the default
2. Keep nameType=any to mean any string is allowed. Note that if name is not specified, then nameType=any
3. Add nameType=partial: the capital letters are substitutable (empty string allowed), and the lower case letters (and other allowed symbols such as underscore) are not.

Additionally, render in the documentation all substitable letters in italics.  This will make situations like "Q" and "I" in NXcanSAS more readable, as they will be in non-italics.

Finally, check the sources for instances where the above rules are broken and fix them (`egrep -r 'name="[A-Z]{4,}' base_classes/ contributed_definitions/ applications/`

**Comment by phyy-nx** [comment]
We will vote on the above tomorrow.  Any feedback is welcome!

**Comment by woutdenolf** [comment]
> "nameType=specified as the default" and "if name is not specified, then nameType=any"

_My interpretation of this is_: when the `nameType` attribute is not defined it defaults to "specified" when the `name` attribute is defined and "any" when the `name` attribute is not defined. Can this even be expressed in XDS?

> Add nameType=partial: the capital letters are substitutable (empty string allowed), and the lower case letters (and other allowed symbols such as underscore) are not.

Convoluted statement.

_My interpretation of this is_: when the `nameType` attribute is equal to "partial", all capital letters are substitutable and all other characters are not.

Note: I just discovered this only applies to fields, not groups. Does this mean that the upper-case-being-substitutable rule we have at the moment (before all this) does not apply to groups?

**Comment by sanbrock** [comment]
- The plan is to clarify and unify the rules. Hence, the new ruleset should apply on Groups, Fields and Attributes. (Although the `name=` attribute can only be omitted in case of groups, where the substitutable `nameType=any` style all capital italic HTML name is automatically generated from the referenced `type=` attribute. )  
- Note that empty substitution is only allowed in case of `nameType=partial` where it does not result in an empty string.  
- The extra rule for groupType that nameType can be freely defined only if name is present can be implemented in xsd e.g. by setting the valid  sequences of either a required name and a nameType defaulting to specified, or no name and a default nameType of any.

**Comment by phyy-nx** [comment]
Revised from NIAC 2024 session D

Use cases:

- Exact name (upper/lower)
- Full substitution with any string if nameType=any or if name is not specified
- Partial substitution by user or application definition

Proposal:

1. Keep nameType=specified as the default when a name is provided.
2. Keep nameType=any to mean any name that follows the [naming rules](https://manual.nexusformat.org/datarules.html#naming-conventions) is allowed. Note that if a name is not provided, then nameType=any.
3. Add nameType=partial: the capital letters are substitutable (empty string allowed), and the lower case letters (and other allowed symbols such as underscore) are not.  After substitution, the final name should follow the [naming rules](https://manual.nexusformat.org/datarules.html#naming-conventions).

Additionally, render in the documentation all substitable letters in italics.  This will make situations like "Q" and "I" in NXcanSAS more readable, as they will be in non-italics.

Additionally, nameType as an attribute has only applied to fields.  Make it apply to fields, groups, and attributes.

Finally, check the sources for instances where the above rules are broken and fix them (`egrep -r 'name="[A-Z]{4,}' base_classes/ contributed_definitions/ applications/`

The above is adopted by vote in [NIAC 2024](https://www.nexusformat.org/NIAC2024.html).  A PR that implements this will be prepared.

**Comment by phyy-nx** [comment]
Possible example in the PR could be dataNN or sourceTYPE to illustrate how this is done.

**Comment by prjemian** [comment]
### editing checklist

- [ ] add `partial` and its description
- [ ] Document all substitutable letters in italics.  This will make situations like "Q" and "I" in NXcanSAS more readable, as they will be in non-italics.
- [ ] use `nameType` in fields, groups, and attributes
- [ ] check the sources for instances where the above rules are broken

**Comment by prjemian** [comment]
Here's a procedure to validate this XSD Schema file:
https://stackoverflow.com/a/48980995/1046449
