### ISSUE TITLE
does entry(NXentry) allow entry1, entry2, entry3 etc.

### ISSUE THREAD

**Issue by sanbrock** [nexusformat/definitions#1438]
- Or should it be defined as entryID(NXentry) instead ?
- ENTRY(NXentry) is not strict enough but entryID (aka mixed capitalization) is also not because what does the character sequence ID tell?
- Only from the allowed characters as defined in NeXus, two of characters or multiple i.e.
also entrymyfamous(NXentry) is allowed?
- Why at all to start from 1 when 0 is an allowed character? Is the best practice counting defined in the documentation?

**Comment by prjemian** [comment]
Answering the title: yes, as described in the [manual](https://manual.nexusformat.org/rules.html#rules-for-structuring-information-in-nexus-files).

**Comment by prjemian** [comment]
You may also use other names, including names that do not contain the letters `"entry"`.  It is the group's `NX_class="NXentry"` attribute  that identifies the group as an NXentry.

Whatever name you pick, it must match the [*validItemName*](https://manual.nexusformat.org/datarules.html#validitemname) regular expression.

**Comment by prjemian** [comment]
> Why at all to start from 1 when 0

It is only a convention, not a requirement.

**Comment by sanbrock** [comment]
Exactly, this is what NXroot also declares haveing ENTRY defined there, so one can have any nuumber of entries called as wished, like my_experiment. The problem is that appdef, like NXmonopd, where the name is fixed to "entry" so it does not allow multiple different names for different entries for NXmonopd.

**Comment by sanbrock** [comment]
See #1445

**Comment by phyy-nx** [comment]
Proposal:

- Change all instances of `<group type="NXentry" name="entry">` to `<group type="NXentry">` (24 instances)
- Deprecate all instances of `<attribute name="entry">` (6 instances)

Resolved to the do the above in [NIAC 2024](https://www.nexusformat.org/NIAC2024.html)
