### ISSUE TITLE
NXroot

### ISSUE THREAD

**Issue by sanbrock** [nexusformat/definitions#1455]

**Comment by sanbrock** [comment]
PR #1418

**Comment by sanbrock** [comment]
Proposal:
- added NeXus_repository to give the possibility to specify a url where definitions of the given version can be accessed
  A) accept 
  B) remove it from proposal
- NeXus version to enable referencing the specific version of definitions
  A) accept that the meaning changes to support the attribute which is not in use anymore because NAPI is not supported
  B) use a different attribute name for this  purpose
  C) reject referencing a specific version
- new attribute 'partial' to flag that the given file only implements a part of an application definition. Requested by companies which can only provide data for specific parts, like DETECTOR or INSTRUMENT, but not for SAMPLE or USER
  A) accept as proposed
  B) reject thie use of this flag

**Comment by woutdenolf** [comment]
Discussion related to versioning: https://github.com/nexusformat/definitions/issues/1038
