### ISSUE TITLE
NXuser

### ISSUE THREAD

**Issue by sanbrock** [nexusformat/definitions#1462]

**Comment by sanbrock** [comment]
PR #1416

**Comment by lukaspie** [comment]
Idea: use new base class `NXidentifier` in `NXuser`

**Comment by sanbrock** [comment]
Proposal:
- NXidentifier - implement NIAC suggestions
- NXuser
  A) deprecate ORCID field and suggest IDENTIFIER
  B) do not deprecate ORCID, but add IDENTIFIER
  C) reject adding IDENTIFIER for now

**Comment by sanbrock** [comment]
NIAC suggested B for the moment
