### ISSUE TITLE
Base classes mentioning other base classes but not modifying them or leaving them as ALLCAPITAL

### ISSUE THREAD

**Issue by sanbrock** [nexusformat/definitions#1471]
https://manual.nexusformat.org/classes/base_classes/NXinstrument.html#index-0
this is the most prominent example of it,
essentially it is quite an empty base class namely an offspring of NXobject with nothing more than a name.
My proposal is to use some of the ALLCAPITAL base classes mentioned
like APERTURE, DETECTOR in the docstring of the class to guide users as to what could be used BUT remove this habit of mentioning such unmodified base classes.

Admittedly, one value of having them in NXinstrument is that because of composition it avoids that one needs to mention in .../myinstrument(NXinstrument)/APERTURE(NXaperture) in the appdef directly because NXinstrument comes with that APERTURE inbuild but if the list in NXinstrument is not updated one still needs to add it in the appdef. Not only because of this APERTURE as such is inherently optional and hence why should one not better mention what an appdef needs there, specifically if in NXinstrument these base classes are not modified. Negotiating convenience vs consistence.

These base class create several logical connections between base classes that one needs to be aware of when updating the definitions.

**Comment by sanbrock** [comment]
Note that such definitions do not (necessarily) change the referenced concept, but the purpose is to set a(potentionaly optional) <HAS> relationship. In the example above: NXinstrument can have (one or multiple) NXaperture, or NXdetector.

**Comment by prjemian** [comment]
Related *new* issues that add such mentions:

- #1430 
- #1431

**Comment by phyy-nx** [comment]
No action from NIAC.  It's a bit more wordy than necessary but after discussion we'll leave as is.
