### ISSUE TITLE
Devise way for validators to better understand substitutions in the definitions

### ISSUE THREAD

**Issue by phyy-nx** [nexusformat/definitions#1475]
A validator currently has problems understanding the relationships between the definition names and the actual object names used in a file. This is also an issue when dealing with string substitutions for object names, especially when there are multiple similar names. 

Edit: search from @prjemian:
https://github.com/search?q=repo%3Anexusformat%2Fdefinitions%20nameType&type=code

**Comment by phyy-nx** [comment]
In the search we found two bugs:

In NXbeam reference_beam should probably be nameType=specified
In NXcanSAS, run could be runNUMBER nameType=partial, and the details field could be DETAILS

Other than NXdata, it's possible that after the resolution of the above, there aren't any actual definitions where we have a problem.  And NXdata should be fixed to be unambigous after #1381

**Comment by lukaspie** [comment]
Based on [this search](https://github.com/search?q=repo%3Anexusformat%2Fdefinitions%20nameType&type=code), would `AXISNAME_end` and `AXISNAME_increment_set` in `NXtransformations` not also be set to `nameType="partial"`?
