### ISSUE TITLE
Introduction paragraph of main documentation states that NeXus is built on HDF5 explicitly

### ISSUE THREAD

**Issue by RussBerg** [nexusformat/definitions#1504]
The [introduction:](https://manual.nexusformat.org/introduction.html) paragraph of the documentation makes it sound like all NeXus files are HDF5 files when it should at most say that HDF5 is the most popular file container for NeXus files. I know that there are some limitations imposed by HDF5 like no soft links but it is not clear to me if that the documentation should be this explicit about HDF5.

"NeXus [[1]](https://manual.nexusformat.org/introduction.html#id2) is an effort by an international group of scientists [motivated](https://manual.nexusformat.org/motivations.html#motivationsfornexus) to define a common data exchange format for neutron, X-ray, and muon experiments. **NeXus is built on top of the scientific data format HDF5 and adds domain-specific rules for organizing data within HDF5 files** in addition to a dictionary of well-defined domain-specific field names"

**Comment by rayosborn** [comment]
Although it used to be the case that NeXus files could be written as HDF4, HDF5, or XML files when we were willing to maintain an API that handled all three, I think we now have to insist on the use of HDF5, or we will have a situation where nobody can read files produced at other facilities, defeating one of our main goals. It's understandable to wish that NeXus could be agnostic about the underlying file format, but I don't think it's a practical possibility without cloning Mark Koennecke several times to regenerate the C API. Personally I think it's helpful to make that clear at the beginning.

As an aside, HDF5 does support soft links. The nexusformat package has handled them for a while now.

**Comment by RussBerg** [comment]
Ok based on telco conversations I was under the impression that we were avoiding locking "NeXus" to HDF5 so I thought I would raise it, but what you are saying about the API makes sense 👍 .
