### ISSUE TITLE
NXcharacterization needs proper documentation

### ISSUE THREAD

**Issue by stuartcampbell** [nexusformat/definitions#177]
**Original reporter**: _[prjemian](https://github.com/prjemian)_

The documentation in the NXcharacterization NXDL file is incorrect.  It reveals the NXDL was created by first copying NXentry but the documentation string was never changed.

**Comment by zjttoefs** [comment]
The class has been marked for deletion. There is no evidence of it being used and no one appears to have an idea of the intended use. The class definition is no help either. I would suggest we just delete this class.

**Comment by prjemian** [comment]
discuss at next [2017-01-30 Telco](http://wiki.nexusformat.org/Telco_20170130)
