### ISSUE TITLE
nxtranslate documentation

### ISSUE THREAD

**Issue by stuartcampbell** [nexusformat/definitions#192]
**Original reporter**: *[prjemian](https://github.com/prjemian)*

nxtranslate manual content is in the code tree, fold this in to the manual proper

**Comment by zjttoefs** [comment]
All command line utilities have man pages in the code repository. And I think that is not a bad place for them.

The "definitions" repository should carry the definitions that affect anyone using NeXus. The NAPI and tools are optional and are covered to some extend in the manual that is generated in line with the definitions documentation. If we think a general action is required I would rather move the NAPI and tools documentation out of here and integrating more.
