### ISSUE TITLE
use cmake to build Sphinx documentation

### ISSUE THREAD

**Issue by stuartcampbell** [nexusformat/definitions#230]
**Original reporter**: *[prjemian](https://github.com/prjemian)*

see:  http://ericscottbarr.com/blog/2012/03/sphinx-and-cmake-beautiful-documentation-for-c-projects/

**Comment by zjttoefs** [comment]
#360 seems to be the remaining problem.

**Comment by eugenwintersberger** [comment]
Not for long  - I have a local branch here where this issue is resolved. Unfortunately, the solution was to entirely rewrite the cmake files. And I still have to do some fixes on the nxdl2rst.py scripts. I hope I can release a first beta version for the documentation next week.
