### ISSUE TITLE
NXxraylens - review

### ISSUE THREAD

**Issue by stuartcampbell** [nexusformat/definitions#238]
**Original reporter**: _Eugenwintersberger_

Should be renamed as the name does not directly describe what it is. 
The new name will be NXrefractive_lens.

aperture: use only diameter and remove radius

cylinder_orientation: should be NXgeometry

Need more information on the topic to fix the base class.

**Comment by zjttoefs** [comment]
With NXgeometry deprecated we should not convert the orientation to that. 

Having a well defined refractive lens class instead, would be good.

Fixed the radius or diameter stupidity.
