### ISSUE TITLE
revise NXgeometry documentation

### ISSUE THREAD

**Issue by stuartcampbell** [nexusformat/definitions#253]
**Original reporter**: *[prjemian](https://github.com/prjemian)*

revisions to the NXGeometry documentation have been developed on the NeXus wiki:

http://wiki.nexusformat.org/NXgeometry_and_NXshape_-_documentation_and_review

These are intended to be added to the NXgeometry.nxdl.xml file as documentation.

**Comment by zjttoefs** [comment]
NXgeometry deprecated
