### ISSUE TITLE
manual: not obvious how to find the latest definitions release

### ISSUE THREAD

**Issue by stuartcampbell** [nexusformat/definitions#254]
**Original reporter**: *[prjemian](https://github.com/prjemian)*

A user wrote, asking if the definitions have been released formally and where to find that release.

Clarify this in the manual.

**Comment by zjttoefs** [comment]
The commit messages above introduced some stub page that must have been dropped again later.

So for the moment there still is no indication for outsiders what our release history or roadmap is.

**Comment by prjemian** [comment]
We are [now ](https://github.com/nexusformat/definitions/issues/387#issuecomment-252921684) tagging releases in the GitHub repository

* releases: https://github.com/nexusformat/definitions/releases
* discussion: https://github.com/nexusformat/definitions/issues/387#issuecomment-252921684

**Comment by prjemian** [comment]
added to manual, see: https://github.com/nexusformat/definitions/issues/387#issuecomment-253238632
