### ISSUE TITLE
NXtransformations and "anonymous" field in NXDL specification

### ISSUE THREAD

**Issue by stuartcampbell** [nexusformat/definitions#272]
**Original reporter**: *[prjemian](https://github.com/prjemian)*

In the NXtransformations NXDL specification, there appears an unnamed field (field element with no name attribute).  The present NXDL rules do not allow this.

Should the rules (nxdl.xsd) be extended to provide for anonymous fields or can this idea be redesigned to avoid this situation?

The nxdl.xsd could define an "anonymous attribute, such as:
```
 <xs:attribute name="anonymous" 
               type="nx:NX_BOOLEAN" 
               use="optional" 
               default="false">
 	<xs:annotation>
 		<xs:documentation>
 			Name of this field is not known or defined 
 			by the NXDL specification.
		</xs:documentation>
	</xs:annotation>
 </xs:attribute>
```

The nxdl.xsd would also need to assert this rule:

 name is defined and anonymous is false
 -- *or* --
 name is not defined and anonymous is true

**Comment by zjttoefs** [comment]
A proposed solution is available since merging of pr #411
