### ISSUE TITLE
make distinction between required and optional content in the manual

### ISSUE THREAD

**Issue by zjttoefs** [nexusformat/definitions#277]
As we allow optional data in application definitions, the user should know which ones they are. Cases where multiple instances of an object are allowed might be obvious from the context, but maybe we do want to report the entire minOccurs/maxOccurs?

I don't think we do required fields in base classes, otherwise that should be clear as well.

**Comment by zjttoefs** [comment]
Strongly relates to #266 but is a separate (further) documentation problem.

**Comment by prjemian** [comment]
Overall comment in the first paragraph here:
http://download.nexusformat.org/doc/html/classes/applications/index.html

**Comment by prjemian** [comment]
``NXcanSAS`` is one application definition which uses the ``minOccurs`` attribute, such as for the ``Qmean`` field.  The value of ``minOccurs`` is not represented in the HTML documentation.

Changes to ``utils/nxdl2rst.py`` are in order.

**Comment by prjemian** [comment]
refs  3efce81857487b41c7b4b01663cd8c761f57ef61

**Comment by prjemian** [comment]
Can this be closed at the 2016-11-16 telco?

**Comment by zjttoefs** [comment]
success!
