### ISSUE TITLE
allow string array content 

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#281]
need to allow string array content in addition to standard strings (an enhancement to NeXus)

in some instances, strings may be limited to rank=1 (which is, in effect, what exists now)
in some cases, we can be less restrictive, up to NX_RANK_MAX

**Comment by prjemian** [comment]
What work is required to close this ticket?  Perhaps this added to the manual in *the right place*:

Clients should support string arrays.  When shape is (1,) then that means there is only one string and the string array can be flattened to just string.

**Comment by zjttoefs** [comment]
The @axes does make use of it, doesn't it? Then there should be no work required.

**Comment by prjemian** [comment]
The `datarules.rst` file is one place to add the text under the *strings* definition.

http://download.nexusformat.org/doc/html/datarules.html#nexus-data-types

Also, to be like the other definitions nearby, start this definition with 

   `NX_CHAR`:

Could also expand the documentation of `NX_CHAR` in `nxdlTypes.xsd`
