### ISSUE TITLE
flexible field names in base classes

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#288]
In some of the base classes, the field names specify the name to use when that particular piece of information is provided.  In other cases, such as NXdata/data, the name is only a suggestion and other names are permitted.

Specifically, it is the case of NXdata/data that is most misunderstood in NeXus as a strong requirement that is not happily fulfilled by the creators of data files.

We need to describe that some field names are flexible and we need to provide an easy way to note that in the documentation, including the NXDL files.

**Comment by zjttoefs** [comment]
This (again) is not available using Peter Chang's annotations from pull request #411 

The open issue here would be to fit out NXdata with that.

**Comment by prjemian** [comment]
647f1e4 (from #411) introduced an attribute in nxdl.xsd called `nameType = specified | any` where `specified` is the default

this should be applied in various cases such as NXdata/data
