### ISSUE TITLE
The "NeXus" logo in the manual should link to http://www.nexusformat.org/

### ISSUE THREAD

**Issue by jwuttke** [nexusformat/definitions#297]
The "NeXus" logo (on the top right of each HTML manual page) should link to the top level page of our online information, http://www.nexusformat.org/, and not to http://download.nexusformat.org/doc/html/index.html

**Comment by zjttoefs** [comment]
In the manual I'm not convinced that is a good idea. Sphinx manual by default link to the top level of the manual in that place, so that's what people expect.
