### ISSUE TITLE
rename "NXvalidate"

### ISSUE THREAD

**Issue by jwuttke** [nexusformat/definitions#300]
When I first encountered "NXvalidate" I mistook it for the name of yet another proposed base class.
The prefix "NX" should be reserved for specified keywords.
I propose to stay with "nxvalidate".
If two different validation scripts survive the pending repair (#251), then I suggest to distinguish them through a command-line option, or using hyphenation: "nxvalidate-gui" or similar.

**Comment by zjttoefs** [comment]
called cnxvalidate now
