### ISSUE TITLE
avoid the term "data format"

### ISSUE THREAD

**Issue by jwuttke** [nexusformat/definitions#306]
The term "data format" is ambiguous and confusing. Look at the Manual, Sect 1.2.1 "What is NeXus?", subsection "A Set of Subroutines":

"In the past, a data format was defined by a document describing the precise location of every item in the data file, either as row and column numbers in an ASCII file, or as record and byte numbers in a binary file. It is the job of the subroutine library to retrieve the data. This subroutine library is commonly called an application-programmer interface or API."

The initial "in the past" is in conflict with the fact that file access via an API is still state of the art. Even today, a physical file format prescribes the precise location of every single byte.

I feel that the unclear term "data format" is responsible for much of this confusion. We should avoid it almost completely.

For the low-level physical storage format, there is the well established term "file format".

For everything else in NeXus, I suggest the term "data model", which comprises data structure, keyword dictionaries, and semantics.

**Comment by prjemian** [comment]
This is semantics.  Data format is an accepted term.  NeXus provides structure to the placement of data within the HDF5 file format.
