### ISSUE TITLE
NXDL data type vs NAPI type vs NeXus data type: clarify and simplify!

### ISSUE THREAD

**Issue by jwuttke** [nexusformat/definitions#307]
Manual 1.3.3.2. has a section on "NeXus Data Types". 

2.2.1.1 has "NXDL Data Types (internal)", and an attribute "type"

2.2.1.2 has "NXDL: Data Types", "Data Types allowed in NXDL specifications", "Data types for use in NXDL" (three wordings for the same?), and also mentions "the NAPI type".

Then of course there is the data field name "type", which has nothing to do with the above.

The relation between NeXus, NXDL, and NAPI types needs to be clearly exposed, and if possible simplified.

1.3.3.2 introduces far too briefly a "binary data" type. 2.2.1.2 introduces "NX_BINARY". The relation between both is unclear.

The suggestion to use NX_BINARY for text with Microsoft linebreaks looks very much ad hoc. This is not a serious way to specify a text exchange format. What about character encoding?

**Comment by PeterC-DLS** [comment]
Update on the numbering:
```
Manual 1.3.3.2. has a section on "NeXus Data Types".
```
refers to (http://download.nexusformat.org/doc/html/datarules.html#nexus-data-types)

```
2.2.1.1 has "NXDL Data Types (internal)", and an attribute "type"
2.2.1.2 has "NXDL: Data Types", "Data Types allowed in NXDL specifications", "Data types for use in NXDL" (three wordings for the same?), and also mentions "the NAPI type".
Then of course there is the data field name "type", which has nothing to do with the above.
```
refers to (http://download.nexusformat.org/doc/html/nxdl_desc.html)

```
The relation between NeXus, NXDL, and NAPI types needs to be clearly exposed, and if possible simplified.

1.3.3.2 introduces far too briefly a "binary data" type. 2.2.1.2 introduces "NX_BINARY". The relation between both is unclear.

The suggestion to use NX_BINARY for text with Microsoft linebreaks looks very much ad hoc. This is not a serious way to specify a text exchange format. What about character encoding?
```

**Comment by PeterC-DLS** [comment]
I think the way to remove any confusion is to drop the phrase "NXDL data type" and use "NXDL field type" for specifying the internal type used in the schema files.

**Comment by PeterC-DLS** [comment]
The `NX_BINARY` issue should be addressed separately.
