### ISSUE TITLE
clean up the entry (entry) @entry subentry mess, or explain

### ISSUE THREAD

**Issue by jwuttke** [nexusformat/definitions#314]
Most application definitions have `entry: NXentry`.

Some have `(entry): NXentry`

Some of these have an extra attribute ` @entry: NX_CHAR`

And some of these have an extra doc line: `NeXus convention is to use “entry1”, “entry2”, ... for analysis software to locate each entry`

Furthermore we have `NXsubentry`.

I suspect at least some of these variants can be deleted or marked as obsolete.

However, when all them are considered good practice, then I need an explanation when to use which variant.

**Comment by prjemian** [comment]
NXentry Group given "entry" as an explicit name:

    entry: NXentry

NXentry Group with no name described, "entry" is suggested:

    (entry): NXentry

When there are more than one NXentry group, follow the NeXus convention as you described it above.  It's a convention but not a rule.  Do anything you want.

The attribute @entry is specific to the class in which it is declared.  Use it as that class describes or ask about that class specifically.

The NXsubentry class is used to describe "multimodal" data (when more than one application definition applies, such as SAXS/WAXS).  It is ALWAYS used as a child of NXentry.
