### ISSUE TITLE
Remove redundant minOccurs from class definitions

### ISSUE THREAD

**Issue by jwuttke** [nexusformat/definitions#317]
In base classes, minOccurs="0" is redundant, since fields are optional by default. Therefore, remove minOccurs=0 from Nxparameters.nxdl.xml.

In application definitions, minOccurs="1" is redundant, since fields are mandatory by default. Therefore, remove minOccurs=1 from NXxbase.nxdl.xml and from several contributed definitions.

**Comment by zjttoefs** [comment]
Same as #266
