### ISSUE TITLE
Automatically translate minOccurs="0" from NXDL to html and pdf docs

### ISSUE THREAD

**Issue by jwuttke** [nexusformat/definitions#318]
Fields in application definitions are obligatory by default. When an explicit attribute 'minOccurs="0"' makes them optional, then this is an important information that must reliably show up in the HTML and PDF view of the specs. Therefore, nxdl2rst.py needs to be modified to provide automatic translation of this piece of information.

**Comment by zjttoefs** [comment]
This is the same as
https://github.com/nexusformat/definitions/issues/277
