### ISSUE TITLE
Agree on a default for maxOccurs, mark the opposite case in the class definitions, and provide automatic translation

### ISSUE THREAD

**Issue by jwuttke** [nexusformat/definitions#320]
What is the default value of maxOccurs? 1 or unbounded?

Say we settle on "unbounded". Otherwise, modify the following text accordingly.

Once a decision is taken, the following remains to be done:
- Remove all attributes 'maxOccurs="unbounded" from the NXDL definitions, since this information has become redundant and is potentially confusing when randomly inserted or not.
- Determine for each single field in each class definition whether the default is applicable. If not, then insert an explicit attribute 'maxOccurs="1"'.
- Modify nxdl2rst.py to provide automatic translation of this attribute into the HTML and PDF view of the specs.

**Comment by zjttoefs** [comment]
Same as #266
