### ISSUE TITLE
NXsqom: filenames -> file_name

### ISSUE THREAD

**Issue by jwuttke** [nexusformat/definitions#322]
NXsqom has a data field named "filenames" while elsewhere (NXroot, NXnote) we have file_name. Use of the underscore should be unified. The plural should quite generally be avoided; instead, once we have practicable rules about ranks, this field should be marked as admitting rank 1 (string) or 2 (list of strings).

**Comment by zjttoefs** [comment]
Can be addressed in a next revision of NXsqom with the new versioning scheme.

**Comment by benajamin** [comment]
@RussBerg Do you have an opinion on how the NXDL should specify a list of file paths? Could you please make a pull request demonstrating a fix for this issue?

**Comment by prjemian** [comment]
In two places:

```bash
(bluesky_2022_3) prjemian@zap:~/.../NeXus/definitions$ git grep filename | grep field
applications/NXiqproc.nxdl.xml:             <field name="filenames" type="NX_CHAR">
applications/NXsqom.nxdl.xml:        <field name="filenames" type="NX_CHAR">
```

**Comment by benajamin** [comment]
Would `file_list` perhaps be a better field name?

**Comment by benajamin** [comment]
@jwuttke We suggest that `file_list` would be an appropriate name for this field. However, this issue is quite old and we don't know if a change is still wanted. Therefore, we will close the issue and invite you to reopen it if you wish to request such a change to be made.

**Comment by jwuttke** [comment]
Thanks for coming back to me. However, I have not followed the evolution of NeXuS for quite some years. Therefore I should not influence your decision in any way.

My original posting talks about systematic handling of ranks, by which I meant either syntax or conventions to infer ways of storing an array of X from given definition of element X. Has anything in this direction been developed? Maybe using the English plural in tags like "filenames" is a perfectly sufficient solution.

**Comment by benajamin** [comment]
The rank of an array and the size of each dimension can be proscribed in the NXDL definition of a base class or application definition. For example, NXsqom includes:
>       <field name="data" type="NX_INT" signal="1">
>         <dimensions rank="1">
>           <dim index="1" value="nP"/>
>         </dimensions>
Your comments sound to me like you are asking if the choice of field name can indicate the rank of an array. We tend to try to avoid such conventions for two reasons:
1. validation of the files should be performed by formal definitions in XML and naming conventions don't fit this model.
2. avoiding plural forms of required field names reduces confusion over what is the correct string to use.
