### ISSUE TITLE
sample/nature: allow other values (and change name?)

### ISSUE THREAD

**Issue by jwuttke** [nexusformat/definitions#327]
Is there a better name than "nature" for the physical state of a sample?

In any case, values must not be restricted to powder | liquid | single crystal; there are many other states, like liquid crystal, glass, man-made multilayers, etc etc

**Comment by prjemian** [comment]
Is there a compelling reason to change an existing name?  at NIAC2018, decided to keep `nature`

**Comment by prjemian** [comment]
@stuartcampbell : just assigned to you
