### ISSUE TITLE
remove @ignoreExtra... from NXDL

### ISSUE THREAD

**Issue by jwuttke** [nexusformat/definitions#328]
Since we agreed that it is always allowed to add extra datafields and extra groups to NeXus groups, there is no point in raising warnings about unknown items. Hence there is also no point in suppressing such warnings using @ignoreExtra(Attributes|Fields|Groups). I therefore suggest to remove these attributes from the NXDL and from the three classes that are currently using them.

**Comment by prjemian** [comment]
this attribute is for the use of validation
