### ISSUE TITLE
remove unused attributes from the NXDL

### ISSUE THREAD

**Issue by jwuttke** [nexusformat/definitions#330]
To make the NXDL lighter, remove unused attributes:

definitionType/@restricts
dimensionsType/@refindex
fieldType/@interpretation
fieldType/@offset
fieldType/@stride

**Comment by zjttoefs** [comment]
Discussed in http://wiki.nexusformat.org/Telco_20160614

**Comment by zjttoefs** [comment]
interpretation is used

offset renamed to data_offset, may be in use with stride, check

restricts is liked by PJ

refindex and ref - puzzled

**Comment by mkoennecke** [comment]
Offset was renamed to data_offset because offset is  used with the CIF stuff. Offset is definitely needed.

**Comment by prjemian** [comment]
Can this be closed at 2016-11-16 telco?

**Comment by zjttoefs** [comment]
ref and refindex look like they can be deprecated

**Comment by prjemian** [comment]
``ref`` and ``refindex`` are in nxdl.xsd, line 1186 or thereabouts
