### ISSUE TITLE
review rarely used NXDL attributes

### ISSUE THREAD

**Issue by jwuttke** [nexusformat/definitions#331]
dimensionsType/@incr is used only once, in NXfilter - is it really needed?

dimensionsType/@ref and fieldType/@long_name also have relatively few uses.

**Comment by prjemian** [comment]
at NIAC2018, no one interested in discussion
These are questions that no one has chosen to answer in four years.
Closing as will not take action.

**Comment by prjemian** [comment]
re-open for tomorrow's plenary decision

**Comment by prjemian** [comment]
decided at NIAC2018
