### ISSUE TITLE
documentation of NXcanSAS has problems with margins

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#341]
in the deeper subgroups, the margins consume most of the width

assume this is also an uncommented situation for other NXDL document

**Comment by prjemian** [comment]
need to reengineer this solution *and* preserve the sidebar content

**Comment by zjttoefs** [comment]
Currently this margin are fine, but the sidebar is missing. Closing this and reopening #361.

**Comment by prjemian** [comment]
Work is in progress on this issue.
