### ISSUE TITLE
sidebar content missing from HTML manual

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#361]
Since moving to cmake builds of the manual, all content in the sidebar does not appear in the manual.  This content should be restored.

**Comment by prjemian** [comment]
The fix to the margins applied in #341 is responsible for the sidebar content being missing

**Comment by prjemian** [comment]
removal of the manual.source/_templates/layout.html file will restore both the sidebar and the problem of #341.

The resolution to this issue is to re-open #341 with the added consideration of preserving sidebar content and close this issue.

**Comment by prjemian** [comment]
This issue is resolved, issue #341 must be re-opened since work is still open on that issue.

**Comment by zjttoefs** [comment]
I'm confused. The sidebar isn't there now, right?

**Comment by prjemian** [comment]
That is correct.

Issue 361 was about cmake.  When #361 was created, it was not understood 
why the sidebars disappeared.  Assumption was some aspect of cmake 
configuration caused this.

Issue 341 was about the indentations observed in NXcansas documentation. 
  While fixing that, by providing a custom file 
(manual/source/_templates/layout.html), the indentation was fixed and 
the sidebar lost.  Removing the custom layout.html results in 
reappearance of the sidebar.  The layout.html needs to be corrected or 
reimplemented.

Pete

**Comment by zjttoefs** [comment]
The title says #361 (this ticket) is about the sidebar. And in #341 you just stated that the two issues are unrelated. 

To the bystander it looks as if this is closed because we don't want the sidebar any more. Do you see where I'm coming from?

**Comment by prjemian** [comment]
See my first comment on Feb 26.  Change the title as you see fit.
