### ISSUE TITLE
Manual build not creating top level classes index

### ISSUE THREAD

**Issue by FreddieAkeroyd** [nexusformat/definitions#363]
The links

http://download.nexusformat.org/doc/html/classes/base_classes/
http://download.nexusformat.org/doc/html/classes/applications/
http://download.nexusformat.org/doc/html/classes/contributed_definitions/

wotk but a top level index.html is missing from 
 
http://download.nexusformat.org/doc/html/classes/

**Comment by zjttoefs** [comment]
Ah! That's why I had to fix some links on the wiki... I assumed that was deliberate.

**Comment by FreddieAkeroyd** [comment]
I've had to add a new index.rst, so I'm assuming the link never worked before!

pull request #364 submitted with fix
