### ISSUE TITLE
mark NXgeometry as deprecated

### ISSUE THREAD

**Issue by zjttoefs** [nexusformat/definitions#367]
Needs to be clear from the generated documentation, web and NXDL

**Comment by prjemian** [comment]
![2015-01-21 nxgeometry html screen image](https://cloud.githubusercontent.com/assets/2279984/5840161/0a1cdb18-a159-11e4-9ecd-5efd99d1aa49.png)

This is the present HTML representation.

**Comment by prjemian** [comment]
![2015-01-21 nxgeometry html screen image](https://cloud.githubusercontent.com/assets/2279984/5840191/46331176-a159-11e4-9c36-35de763c99d1.png)

This is the present NXDL source.

**Comment by prjemian** [comment]
![2015-01-21 nxgeometry nxdl screen image](https://cloud.githubusercontent.com/assets/2279984/5840202/57d368b8-a159-11e4-8e68-2ddb9ec64c1a.png)

This is the present NXDL source.

**Comment by prjemian** [comment]
Other suggestions?

**Comment by prjemian** [comment]
completed in c1e502c95f7a78b6b4746dbf70a19b6fd462b1de
