### ISSUE TITLE
document new accepted axes scheme 

### ISSUE THREAD

**Issue by zjttoefs** [nexusformat/definitions#369]
That may be documentation mainly, as full validation may not be possible using (just) NXDL

**Comment by prjemian** [comment]
related to #182

**Comment by prjemian** [comment]
proposal: http://wiki.nexusformat.org/2014_axes_and_uncertainties
minutes: http://wiki.nexusformat.org/NIAC2014_Meeting#Minutes

**Comment by prjemian** [comment]
Note that proposal on **axes** was accepted.
Proposal on **uncertainties** was not accepted.  *NIAC will see a proposal when experience has been gained with all variations.*

**Comment by rayosborn** [comment]
Just to say that I intend to contest the decision at the next NIAC to make canSAS-like axes attributes mandatory. The vote to make it mandatory followed immediately a vote to allow the new system, and I was unprepared for it and, in retrospect, should have demanded a longer discussion. I haven't heard a single argument explaining why we require the use of a more complex system in the 99.9% of cases where it is not needed, and if we are not to provide a higher-level NAPI to make the writing of such attributes easier for non-experts, then we will have a flood of non-conformant NeXus files that I will have to deal with in NeXpy. I notice that the wiki page says, "However, if the indices attributes are missing, file readers are encouraged to make their best efforts to plot the data." This is a ridiculous way to write a standard, i.e., to make it so complex that few files are conformant. I do not have the time to update the Python API to use the new system (i.e., parse existing files using the canSAS system and automatically writing new files with it), but if someone at the code camp wants to give it a go, I will look into it. Note that it is not just a matter of reading and writing - you will also have to modify the rename and other update procedures to update the new axis scheme. I maintain that these kinds of decision will harm the uptake of NeXus by third-party software developers that we should be encouraging to adopt NeXus as an export format.

**Comment by prjemian** [comment]
Ray:

This vote was taken after much discussion at the preceding code camp, 
most of which you chose not to attend.  Had you made time to attend, 
your voice would have carried greater impact and you would have had a 
chance to hear the discussion.

The change addresses a poor design choice made early in NeXus that 
required the use of heuristics to identify the default plottable data. 
With this change, a deterministic method is described to identify the 
default plottable data.  Further, this change was motivated by 
suggestions from outside the NeXus community, to increase the ability of 
that external community (canSAS) to adopt the NeXus standard.

Why is a deterministic method not an advantage over heuristics?
Why should this change, ratified by the NIAC, not be applied uniformly 
to all new NeXus data files?

We have learned the NAPI is not used uniformly throughout the community. 
  Isn't your NeXpy software one such example?  We cannot count on the 
effort spent to maintain the NAPI as addressing the needs of the community.

Pete

**Comment by rayosborn** [comment]
There was nothing heuristic about the previous scheme. The axes are fully determined - it had no short-comings except in the case where the grid was completely irregular, which in my experience has been extremely rare. I did participate in discussions about the extra axis attributes and supported adding them when they were needed, which should have been enough for the canSAS community. I have spent a considerable effort in groups such as the BES Facilities Computing Working Group arguing for the adoption of NeXus, as well as many hours developing the Python API, but decisions like these undermine those efforts by making the standard more arcane and difficult to implement. It is also an unfunded mandate - if people at the code camp want to write the Python code to automatically parse and update the axis attributes, then I will gladly add it to the Python API, but I don't have time to do it myself.

**Comment by zjttoefs** [comment]
We're actually working on a bit of python code that does what you suggest at the end. We hope to have that ready tomorrow for you to inspect.

**Comment by rayosborn** [comment]
That's good news. There is one additional complication, which is that the Python API plotting assumes a regular, though not necessarily equally-spaced, grid. It will take some awkward coding to add multi-dimensional axes to the plotted data. This is something that I support in the long-run because it is a valid, if rare, use case, but it won't happen overnight. In the short term, I will probably have to regularize the grid so that we can produce some kind of plot. If this is also something that others in the NIAC are willing to work on, then I will happily consider any pull requests.

**Comment by markbasham** [comment]
Hi Ray,  I have just committed some code which may be useful here : 

https://github.com/nexusformat/features/blob/master/src/recipes/D1A0000000000001/recipe.py

Hope this is useful, and please feel free to drop me an email for any more info

**Comment by rayosborn** [comment]
Thanks Mark. 
I tried running the recipe on a file that Pete Jemian sent me, which I have sent to you by email - I don't know if it can be added to the Github somehow. It failed to identify the canSAS axes, which I presume are set correctly.

In [52]: c=h5.File('Data_Q.h5')
In [53]: d=recipe(c,'/')
In [54]: d.process()
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-54-5957ec4a69db> in <module>()
----> 1 d.process()

<ipython-input-28-016958236795> in process(self)
    117 
    118         if len(self.NXdatas) == 0:
--> 119             raise AssertionError('No NXdata with cansas Axis found\n'+'\n'.join(self.failure_comments))
    120         a = self.NXdatas[0]
    121         return self.NXdatas

AssertionError: No NXdata with cansas Axis found
/sasentry01/sasdata01 : No axes are specified

Did I run your program correctly? You should be able to reproduce it from the above, if you got the email.

**Comment by prjemian** [comment]
That file is on GitHub already:
https://github.com/prjemian/spec2nexus/tree/master/src/spec2nexus/data/Data_Q.h5

See the (terse) comment about it in:
https://github.com/prjemian/spec2nexus/blob/master/src/spec2nexus/data/README.txt

**Comment by markbasham** [comment]
ooh pretty data :)

Yep it failed on the axes as it is looking for "axes" and not "I_axes"

I seem to remember this was a compromise we made at the Niac meeting.  Pete are you happy for me to modify the file and put it up as example data in the features repo?

**Comment by markbasham** [comment]
Ok, I have updated the check code to deal with comma separated axes as well as array attributes, and have uploaded the slightly modified file to the repo ('I_axes' replaced with 'axes')

**Comment by prjemian** [comment]
that's fine, I _do_ remember now that agreement.  This has been one of things that has stalled me updating the manual

**Comment by zjttoefs** [comment]
The agreement was also to use string arrays. Since this feature recipe is part of the documentation of how to write that data, I am not actually in support of allowing commas there.

**Comment by rayosborn** [comment]
The nexusformat package will parse an 'axes' attribute with a variety of delimiters, including white space, commas, and colons. Of course, we can encourage people to use string arrays, but we have to continue supporting the large number of legacy files that use the single-string format. I'll check the new version some time this week.

**Comment by zjttoefs** [comment]
There is no legacy for the canSAS style axes. And my argument would be to not start one as part of the initial rollout. 

You're referring to the old attribute to the dataset, Ray. Different thing.

**Comment by zjttoefs** [comment]
We've talked about the CSV at the telco yesterday and were in agreement that string parsing is to be avoided. I've committed the revert to Mark's accommodating patch.
We still need to make sure the documentation is consistent with that.

**Comment by zjttoefs** [comment]
Discuss in telco. Appears all work required is done.
