### ISSUE TITLE
more prominently document existing scheme for uncertainties

### ISSUE THREAD

**Issue by zjttoefs** [nexusformat/definitions#370]
There is a _fieldname__errors way of adding uncertainties to arbitrary fields defined at least within NXdata. That could be generalised, but should be more widely known anyway.

**Comment by prjemian** [comment]
It was decided at NIAC2010 that the uncertainties attribute be added to all fields, by adding it under fieldType in nxdl.xsd

Show a simple example from https://github.com/canSAS-org/NXcanSAS_examples

**Comment by prjemian** [comment]
copy (and modify) definition of **@uncertainties** from #516

**Comment by prjemian** [comment]
done with #685
