### ISSUE TITLE
research NXformula

### ISSUE THREAD

**Issue by zjttoefs** [nexusformat/definitions#376]

**Comment by zjttoefs** [comment]
current plan: Adding executable code is not a good idea in a data file.

**Comment by zjttoefs** [comment]
update at NIAC?

**Comment by prjemian** [comment]
this issue is ambiguous
please provide a description of what is intended

**Comment by zjttoefs** [comment]
http://wiki.nexusformat.org/NIAC2014_Meeting

NXformula: Agreed as research project (no vote). No evaluation of formula intended by consumer, use in documentation only. Will be developed by Eugen. Use of attributes may be required to find formula for data. muparser may or may not be sufficient.

**Comment by zjttoefs** [comment]
Is this still an ongoing thing @eugenwintersberger?

**Comment by zjttoefs** [comment]
Looks like the research didn't bring up any suggested actions. Closing.
