### ISSUE TITLE
NXgrating: move to accepted and update NXmonochromator to include

### ISSUE THREAD

**Issue by zjttoefs** [nexusformat/definitions#377]

**Comment by benajamin** [comment]
Moved: cd5bc868bf31c510a8310eb7646d6ec712aaf96b
389b714effdb337c84f235e6643c8c842860b607

still need to update NXmonochromator.

**Comment by benajamin** [comment]
NXmonochromator updated to include NXgrating in commit 452289133e866d96126ff90defa93826e68e80aa
