### ISSUE TITLE
explore thumbnail provision at root level

### ISSUE THREAD

**Issue by zjttoefs** [nexusformat/definitions#381]

**Comment by zjttoefs** [comment]
Is there possibly an update at the next NIAC in October?

**Comment by zjttoefs** [comment]
Had a chat with @benajamin a while back: There is some progress on doing this generically for HDF5. With some support from OSes in their native file browsers.

**Comment by zjttoefs** [comment]
Is there documentation we could point people to or reference from the manual, @benajamin ?

**Comment by benajamin** [comment]
I now have documentation and code for including XMP standard metadata (including thumbnails) in the userblock of HDF5 files (not in the HDF5 root), together with filebrowser plugins for windows, OSX, Gnome and KDE. I am just about done with testing and need to finalise things with the company who wrote the code so that I can release everything publicly.

**Comment by zjttoefs** [comment]
Found its way here: https://github.com/nexusformat/hdf5xmp

This is not at root level, though. Close anyway?

**Comment by benajamin** [comment]
We explored storing thumbnails and other metadata at the HDF5 root level, but found that it required too much overhead (need HDF5 libraries installed, relatively slow to open files and read metadata). Storing metadata in the "user block" (i.e. file header) is faster and easier to work with, so we have gone forward with that approach instead.
I agree that we can close this issue.

**Comment by rayosborn** [comment]
Do you happen to know if the file header is accessible through the HDF5 library - in my case, h5py?

**Comment by benajamin** [comment]
Hi Ray,
   No, the HDF5 libs and h5py have no functions regarding the file header,
except for leaving space for the "user block" when creating the file. You
can access the metadata through straight Python code that treats the file
as simple binary. You can find some example code in the python directory of
the repository.

Cheers,
Ben
