### ISSUE TITLE
explore validation using "features" as proposed at NIAC

### ISSUE THREAD

**Issue by zjttoefs** [nexusformat/definitions#382]
with help from Ray, Herbert and Mark B

Raised in definitions repo due to validation aspect.

**Comment by zjttoefs** [comment]
Work is happening in https://github.com/nexusformat/features among other places.

**Comment by zjttoefs** [comment]
We need to appear active here @markbasham ...

**Comment by prjemian** [comment]
Closing this issue due to https://github.com/nexusformat/NIAC/issues/3.
