### ISSUE TITLE
sort_xsd.xsl does not generate a valid XML Schema file

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#393]
sort_xsd.xsl purports to generate "XML Schema (.xsd) files for use in validating candidate NeXus data files and also in preparing additional application definitions and XML schemas for use by NeXus."

It does not generate valid XML Schema (.xsd file) statements.

Instead, it reproduces the contents of the .nxdl.xml file, without the comments.  The result is a perfectly valid XML file, but it is not an XML Schema file.  Thus, sort_xsd.xsl is rather a trojan horse.

**Comment by eugenwintersberger** [comment]
Is this an issue of the xsl file or a problem of the stupid xmlstrip.py (yes, it was me who produced this piece of crap ;))?

**Comment by prjemian** [comment]
It's the XSLT file.  I have pushed a change that fixes the issue.
