### ISSUE TITLE
clarify the geometry documentation as agreed upon at 2014 NIAC

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#397]
The specification of geometry and axis coordinates needs to be clarified in the manual, as revisions were agreed upon at the 2014 NIAC meeting.

Use this as the starting point
http://www.bernstein-plus-sons.com/software/CBF/doc/cif_img_1.7.8.html#axis

**Comment by yayahjb** [comment]
See also the attached Dectris document, and the history of the discussion at
https://sites.google.com/site/nexuscbf -- HJB

**Comment by prjemian** [comment]
see #195

**Comment by zjttoefs** [comment]
Will add some information and links here to aid to updating of the manual.

**Comment by zjttoefs** [comment]
The code to convert CBF to NeXus is deeply bundled in CBFlib. You'll find evidence it exists here:

http://sourceforge.net/p/cbflib/code-0/HEAD/tree/trunk/CBFlib/src/cbf_hdf5.c

Some documentation is here:

http://cbflib.sourceforge.net/doc/CBFlib.html#2.7

The short bit we already have in the manual is here: http://download.nexusformat.org/sphinx/design.html#coordinate-transformations

**Comment by zjttoefs** [comment]
This poster is probably the most useful to visually experience the CBF-NeXus mapping:

https://sites.google.com/site/nexuscbf/home/presentation-foils/Integration_Poster_10May14_w_overlays.pdf

**Comment by zjttoefs** [comment]
I don't think there is a concrete problem outstanding. There is always room for improvement.
