### ISSUE TITLE
NXtransformations' field default name is not useful for automatic code generation

### ISSUE THREAD

**Issue by PeterC-DLS** [nexusformat/definitions#399]
It is currently defined as "anonymous__NEEDS_XSD_CHANGE__", perhaps "transformation" is better.

**Comment by zjttoefs** [comment]
The idea is that this group has a suggested, but not required name. The current XSD cannot handle that to my knowledge. Hence this "marker" for now. 
Good to have a ticket to keep an eye on it though.

**Comment by prjemian** [comment]
There may be other NXDL files in which the notion of an "anonymous" field (anonymous: name to be defined when the file is written) is used.  

This needs a general solution.

**Comment by PeterC-DLS** [comment]
See possible solution in pull request #411

**Comment by zjttoefs** [comment]
Since that has been merged, I guess we're done.
