### ISSUE TITLE
missing environment variables with cmake on linux

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#401]
mintadmin@mintadmin-VirtualBox ~/.../eclipse/NeXus/definitions $     mkdir build
mintadmin@mintadmin-VirtualBox ~/.../eclipse/NeXus/definitions $     cd build
mintadmin@mintadmin-VirtualBox ~/.../NeXus/definitions/build $     cmake ..
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_LANGUAGES_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_LANGUAGES_COMPILER
CMake Error: Could not find cmake module file: /home/mintadmin/Documents/eclipse/NeXus/definitions/build/CMakeFiles/2.8.12.2/CMakeLANGUAGESCompiler.cmake
CMake Error: Could not find cmake module file: CMakeLANGUAGESInformation.cmake
CMake Error: CMAKE_LANGUAGES_COMPILER not set, after EnableLanguage
-- Found PythonInterp: /home/mintadmin/Apps/anaconda/bin/python (found version "2.7.9") 
-- Found Sphinx: /home/mintadmin/Apps/anaconda/bin/sphinx-build  
-- Configuring incomplete, errors occurred!
See also "/home/mintadmin/Documents/eclipse/NeXus/definitions/build/CMakeFiles/CMakeOutput.log".

**Comment by prjemian** [comment]
mintadmin@mintadmin-VirtualBox ~/.../NeXus/definitions/build $ cmake --version
cmake version 2.8.12.2

**Comment by eugenwintersberger** [comment]
I can confirm this on Debian Wheezy with cmake 2.8.9. The reason why this slipped through the tests was that this issue does not appear on cmake 3.0.2 on Debian Jessie. Seems that I have to test more extensively with different cmake versions.

**Comment by eugenwintersberger** [comment]
Have a look on the issue_401 branch. This should solve the problem.

**Comment by prjemian** [comment]
mintadmin@mintadmin-VirtualBox ~/.../NeXus/definitions/build $ cd ..
mintadmin@mintadmin-VirtualBox ~/.../eclipse/NeXus/definitions $ /bin/rm -rf build/
mintadmin@mintadmin-VirtualBox ~/.../eclipse/NeXus/definitions $ !mkd
mkdir build
mintadmin@mintadmin-VirtualBox ~/.../eclipse/NeXus/definitions $ cd build/
mintadmin@mintadmin-VirtualBox ~/.../NeXus/definitions/build $ cmake ..
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_LANGUAGES_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_LANGUAGES_COMPILER
CMake Error: Could not find cmake module file: /home/mintadmin/Documents/eclipse/NeXus/definitions/build/CMakeFiles/2.8.12.2/CMakeLANGUAGESCompiler.cmake
CMake Error: Could not find cmake module file: CMakeLANGUAGESInformation.cmake
CMake Error: CMAKE_LANGUAGES_COMPILER not set, after EnableLanguage
-- Found PythonInterp: /home/mintadmin/Apps/anaconda/bin/python (found version "2.7.9") 
-- Found Sphinx: /home/mintadmin/Apps/anaconda/bin/sphinx-build  
-- Configuring incomplete, errors occurred!
See also "/home/mintadmin/Documents/eclipse/NeXus/definitions/build/CMakeFiles/CMakeOutput.log".
mintadmin@mintadmin-VirtualBox ~/.../NeXus/definitions/build $ git branch
  cmake_build
* issue_401
  master

**Comment by prjemian** [comment]
this effort is not productive

**Comment by eugenwintersberger** [comment]
You try this with the issue_401 branch right?

**Comment by zjttoefs** [comment]
This is what the last line of his console output would suggest.

**Comment by eugenwintersberger** [comment]
ok

**Comment by prjemian** [comment]
Exactly

**Comment by eugenwintersberger** [comment]
This is getting ridiculous
cmake 2.8.9 (Debian Wheezy): OK
cmake 2.8.11 (Centos 7): OK with warning concerning the CMAKE_INSTALL_LIBDIR
cmake 3.0.2 (Debian Jessie): OK 

2.8.11 is the closest I can currently get to your 2.8.12 installation. But with none of the versions I have available I get serious problems (the CMAKE_INSTALL_LIBDIR is not used).

**Comment by eugenwintersberger** [comment]
Ok - cmake 2.8.12 is available on Ubuntu 14.04. I will install a system in a VM and continue testing. 
However, until now I get successful builds on all systems I have so far tried.

**Comment by eugenwintersberger** [comment]
I have no idea why you get this error. Just made  a build on Ubuntu 14.04 with cmake 2.8.12 (that is basically what you have) -- no warnings, no errors, no problems
