### ISSUE TITLE
remove cmake from builds of definitions branch

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#402]
Building with cmake was supposed to be an enhancement. Despite the hard work contributed to implement, cmake is now a roadblock and prevents the documentation editor from building.

It is not clear that using cmake contributes any value to the definitions repository.
Any possible benefits from a cmake-based build of the definitions must be proven and tested before they are made the official build process.

**Comment by eugenwintersberger** [comment]
BTW - with the code from the issue_401 the HTML documentation also builds without problems on Windows (Win 7 64Bit).

**Comment by zjttoefs** [comment]
Eugen produced a fix on a branch within 33 minutes of #401 being reported. Many thanks Eugen!
Since then he reportedly tried reproduce your problem on 3 Linux distributions and Windows. I can also successfully build on a VM here.

**Comment by prjemian** [comment]
The Jenkins server also shows the same problem.
Eugen's commit did not resolve the problem.  Thus, it was not a fix. 
That result was reported.

**Comment by eugenwintersberger** [comment]
Pete's problem is really weired as I permanently fail to reproduce it. Will think about this tomorrow.

**Comment by prjemian** [comment]
related to #391

**Comment by zjttoefs** [comment]
Jenkins configures fine (except for an ignored warning Eugen mentions in #401). Then the build seems to succeed as well. Just the publish stuff on Jenkins doesn't do the right thing:

copying static files... done
copying extra files... done
dumping search index... done
dumping object inventory... done
build succeeded, 2 warnings.
[100%] Built target htmldoc
jenkins_build: line 26: cd: build: No such file or directory
Build step 'Execute shell' marked build as failure
Archiving artifacts
Sending e-mails to: XXXXX@nexusformat.org
Finished: FAILURE

I'll see if I can update that. But we're no longer in territory where cmake does not work. This is a /bin/sh problem.

**Comment by zjttoefs** [comment]
The build now works on Jenkins. There are two remaining problems with the Jenkins setup:
* The Jenkins config expects the artefacts in a different directory from where they are now produced. Someone with access to the Jenkins config (Freddie?) needs to have a look.
* The location for the pdf download on www.nexusformat.org is no longer correct. The build script actively did place it in a different location already. I've changed the location. I'm not sure that is picked up and updated by jenkins. At least that's not done via the standard build script. I'll wait and see, if nothing happens I might take a guess at the correct location and add that step to jenkins_build.

**Comment by zjttoefs** [comment]
Could oddly fix the first but not the latter problem. Will open ticket.

**Comment by prjemian** [comment]
I confirm that cmake build of documentation **on linuxmint** works properly.
On windows, there are problems, as noted in #407.
