### ISSUE TITLE
PDF of manual is not built

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#406]
The PDF version of the manual is not built at this time.  Can we build it, or should we remove the text and links that reference it?

A link to the PDF is given on our home page: http://www.nexusformat.org/
Text that would provide a link on the documentation page: http://download.nexusformat.org/doc/html/index.html

When building the documentation, the PDF should be built first so at can be included with the HTML documentation.

**Comment by zjttoefs** [comment]
The PDF Version is built. The main website is updated in git to reference it, change needs to propagate through to the web server. Separate ticket was opened for that.

**Comment by prjemian** [comment]
confirmed that PDF is not built at this time

	mintadmin@mintadmin-VirtualBox ~ $ cd Documents/eclipse/NeXus/definitions/
	mintadmin@mintadmin-VirtualBox ~/.../eclipse/NeXus/definitions $ git pull
	Already up-to-date.
	mintadmin@mintadmin-VirtualBox ~/.../eclipse/NeXus/definitions $ git branch -a
	* master
	  origin/issue_402
	  remotes/origin/HEAD -> origin/master
	  remotes/origin/depends_on
	  remotes/origin/interfaces
	  remotes/origin/issue_336
	  remotes/origin/issue_341
	  remotes/origin/issue_360
	  remotes/origin/issue_363
	  remotes/origin/issue_401
	  remotes/origin/issue_402
	  remotes/origin/master
	  remotes/origin/use_make_391
	  remotes/origin/zjttoefs-ticket-395
	mintadmin@mintadmin-VirtualBox ~/.../eclipse/NeXus/definitions $ /bin/rm -rf build/
	mintadmin@mintadmin-VirtualBox ~/.../eclipse/NeXus/definitions $ mkdir build
	mintadmin@mintadmin-VirtualBox ~/.../eclipse/NeXus/definitions $ cd build/
	mintadmin@mintadmin-VirtualBox ~/.../NeXus/definitions/build $ cmake ..
	-- Found PythonInterp: /home/mintadmin/Apps/anaconda/bin/python (found version "2.7.9") 
	-- Found Sphinx: /home/mintadmin/Apps/anaconda/bin/sphinx-build  
	-- Configuring done
	-- Generating done
	-- Build files have been written to: /home/mintadmin/Documents/eclipse/NeXus/definitions/build
	mintadmin@mintadmin-VirtualBox ~/.../NeXus/definitions/build $ make
	Scanning dependencies of target DoXSD
	[  0%] Built target DoXSD
	Scanning dependencies of target xds-manual-source
	[  1%] Generating manual/source/types.table
	[  2%] Generating manual/source/units.table
	[  3%] Generating manual/source/nxdl_desc.rst
	[  3%] Built target xds-manual-source
	Scanning dependencies of target applications-manual-sources
	[  4%] Generating ../manual/source/classes/applications/NXarpes.rst
	[  5%] Generating ../manual/source/classes/applications/NXarchive.rst
	[  6%] Generating ../manual/source/classes/applications/NXdirecttof.rst
	[  7%] Generating ../manual/source/classes/applications/NXfluo.rst
	[  8%] Generating ../manual/source/classes/applications/NXindirecttof.rst
	[  9%] Generating ../manual/source/classes/applications/NXiqproc.rst
	[ 10%] Generating ../manual/source/classes/applications/NXlauetof.rst
	[ 11%] Generating ../manual/source/classes/applications/NXmonopd.rst
	[ 12%] Generating ../manual/source/classes/applications/NXmx.rst
	[ 13%] Generating ../manual/source/classes/applications/NXrefscan.rst
	[ 14%] Generating ../manual/source/classes/applications/NXreftof.rst
	[ 15%] Generating ../manual/source/classes/applications/NXsas.rst
	[ 16%] Generating ../manual/source/classes/applications/NXsastof.rst
	[ 17%] Generating ../manual/source/classes/applications/NXscan.rst
	[ 18%] Generating ../manual/source/classes/applications/NXspe.rst
	[ 19%] Generating ../manual/source/classes/applications/NXsqom.rst
	[ 20%] Generating ../manual/source/classes/applications/NXstxm.rst
	[ 21%] Generating ../manual/source/classes/applications/NXtas.rst
	[ 22%] Generating ../manual/source/classes/applications/NXtofnpd.rst
	[ 23%] Generating ../manual/source/classes/applications/NXtofraw.rst
	[ 24%] Generating ../manual/source/classes/applications/NXtofsingle.rst
	[ 25%] Generating ../manual/source/classes/applications/NXtomo.rst
	[ 26%] Generating ../manual/source/classes/applications/NXtomophase.rst
	[ 27%] Generating ../manual/source/classes/applications/NXtomoproc.rst
	[ 28%] Generating ../manual/source/classes/applications/NXxas.rst
	[ 29%] Generating ../manual/source/classes/applications/NXxasproc.rst
	[ 30%] Generating ../manual/source/classes/applications/NXxbase.rst
	[ 31%] Generating ../manual/source/classes/applications/NXxeuler.rst
	[ 32%] Generating ../manual/source/classes/applications/NXxkappa.rst
	[ 33%] Generating ../manual/source/classes/applications/NXxlaue.rst
	[ 34%] Generating ../manual/source/classes/applications/NXxlaueplate.rst
	[ 35%] Generating ../manual/source/classes/applications/NXxnb.rst
	[ 36%] Generating ../manual/source/classes/applications/NXxrot.rst
	[ 36%] Built target applications-manual-sources
	Scanning dependencies of target base-class-manual-sources
	[ 37%] Generating ../manual/source/classes/base_classes/NXaperture.rst
	[ 38%] Generating ../manual/source/classes/base_classes/NXattenuator.rst
	[ 39%] Generating ../manual/source/classes/base_classes/NXbeam.rst
	[ 40%] Generating ../manual/source/classes/base_classes/NXbeam_stop.rst
	[ 41%] Generating ../manual/source/classes/base_classes/NXbending_magnet.rst
	[ 42%] Generating ../manual/source/classes/base_classes/NXcapillary.rst
	[ 43%] Generating ../manual/source/classes/base_classes/NXcharacterization.rst
	[ 44%] Generating ../manual/source/classes/base_classes/NXcite.rst
	[ 45%] Generating ../manual/source/classes/base_classes/NXcollection.rst
	[ 46%] Generating ../manual/source/classes/base_classes/NXcollimator.rst
	[ 47%] Generating ../manual/source/classes/base_classes/NXcrystal.rst
	[ 48%] Generating ../manual/source/classes/base_classes/NXdata.rst
	[ 50%] Generating ../manual/source/classes/base_classes/NXdetector_group.rst
	[ 51%] Generating ../manual/source/classes/base_classes/NXdetector_module.rst
	[ 52%] Generating ../manual/source/classes/base_classes/NXdetector.rst
	[ 53%] Generating ../manual/source/classes/base_classes/NXdisk_chopper.rst
	[ 54%] Generating ../manual/source/classes/base_classes/NXentry.rst
	[ 55%] Generating ../manual/source/classes/base_classes/NXenvironment.rst
	[ 56%] Generating ../manual/source/classes/base_classes/NXevent_data.rst
	[ 57%] Generating ../manual/source/classes/base_classes/NXfermi_chopper.rst
	[ 58%] Generating ../manual/source/classes/base_classes/NXfilter.rst
	[ 59%] Generating ../manual/source/classes/base_classes/NXflipper.rst
	[ 60%] Generating ../manual/source/classes/base_classes/NXfresnel_zone_plate.rst
	[ 61%] Generating ../manual/source/classes/base_classes/NXgeometry.rst
	[ 62%] Generating ../manual/source/classes/base_classes/NXgrating.rst
	[ 63%] Generating ../manual/source/classes/base_classes/NXguide.rst
	[ 64%] Generating ../manual/source/classes/base_classes/NXinsertion_device.rst
	[ 65%] Generating ../manual/source/classes/base_classes/NXinstrument.rst
	[ 66%] Generating ../manual/source/classes/base_classes/NXlog.rst
	[ 67%] Generating ../manual/source/classes/base_classes/NXmirror.rst
	[ 68%] Generating ../manual/source/classes/base_classes/NXmoderator.rst
	[ 69%] Generating ../manual/source/classes/base_classes/NXmonitor.rst
	[ 70%] Generating ../manual/source/classes/base_classes/NXmonochromator.rst
	[ 71%] Generating ../manual/source/classes/base_classes/NXnote.rst
	[ 72%] Generating ../manual/source/classes/base_classes/NXobject.rst
	[ 73%] Generating ../manual/source/classes/base_classes/NXorientation.rst
	[ 74%] Generating ../manual/source/classes/base_classes/NXparameters.rst
	[ 75%] Generating ../manual/source/classes/base_classes/NXpinhole.rst
	[ 76%] Generating ../manual/source/classes/base_classes/NXpolarizer.rst
	[ 77%] Generating ../manual/source/classes/base_classes/NXpositioner.rst
	[ 78%] Generating ../manual/source/classes/base_classes/NXprocess.rst
	[ 79%] Generating ../manual/source/classes/base_classes/NXroot.rst
	[ 80%] Generating ../manual/source/classes/base_classes/NXsample.rst
	[ 81%] Generating ../manual/source/classes/base_classes/NXsensor.rst
	[ 82%] Generating ../manual/source/classes/base_classes/NXshape.rst
	[ 83%] Generating ../manual/source/classes/base_classes/NXslit.rst
	[ 84%] Generating ../manual/source/classes/base_classes/NXsource.rst
	[ 85%] Generating ../manual/source/classes/base_classes/NXsubentry.rst
	[ 86%] Generating ../manual/source/classes/base_classes/NXtransformations.rst
	[ 87%] Generating ../manual/source/classes/base_classes/NXtranslation.rst
	[ 88%] Generating ../manual/source/classes/base_classes/NXuser.rst
	[ 89%] Generating ../manual/source/classes/base_classes/NXvelocity_selector.rst
	[ 90%] Generating ../manual/source/classes/base_classes/NXxraylens.rst
	[ 90%] Built target base-class-manual-sources
	Scanning dependencies of target contributed-manual-sources
	[ 91%] Generating ../manual/source/classes/contributed_definitions/NXcanSAS.rst
	[ 92%] Generating ../manual/source/classes/contributed_definitions/NXelectrostatic_kicker.rst
	[ 93%] Generating ../manual/source/classes/contributed_definitions/NXmagnetic_kicker.rst
	[ 94%] Generating ../manual/source/classes/contributed_definitions/NXquadrupole_magnet.rst
	[ 95%] Generating ../manual/source/classes/contributed_definitions/NXseparator.rst
	[ 96%] Generating ../manual/source/classes/contributed_definitions/NXsnsevent.rst
	[ 97%] Generating ../manual/source/classes/contributed_definitions/NXsnshisto.rst
	[ 98%] Generating ../manual/source/classes/contributed_definitions/NXsolenoid_magnet.rst
	[100%] Generating ../manual/source/classes/contributed_definitions/NXspin_rotator.rst
	[100%] Built target contributed-manual-sources
	Scanning dependencies of target htmldoc
	Making output directory...
	Running Sphinx v1.2.3
	loading pickled environment... not yet created
	building [html]: targets for 145 source files that are out of date
	updating environment: 145 added, 0 changed, 0 removed
	reading sources... [100%] validation                                                                                                                                                
	/home/mintadmin/Documents/eclipse/NeXus/definitions/build/manual/source/index.rst:37: WARNING: download file not readable: /home/mintadmin/Documents/eclipse/NeXus/definitions/build/manual/source/nexus.pdf
	looking for now-outdated files... none found
	pickling environment... done
	checking consistency... done
	preparing documents... done
	##writing output... [  1%] authorgroup                                                                                                                                              #writing output... [  6%] classes/applications/NXlauetof                                                                                                                            #writing output... [ 10%] classes/applications/NXsastof                                                                                                                             #writing output... [ 33%] classes/base_classes/NXdata                                                                                                                               ####################################writing output... [ 63%] classes/contributed_definitions/NXelectrostatic_kicker                                                                 writing output... [100%] validation                                                                                                                                                 
	writing additional files... (0 module code pages) genindex search
	copying images... [100%] img/polplane.png                                                                                                                                           
	copying downloadable files... [100%] /home/mintadmin/Documents/eclipse/NeXus/definitions/build/manual/source/examples/verysimple.nx5                                                
	copying static files... done
	copying extra files... done
	dumping search index... done
	dumping object inventory... done
	build succeeded, 1 warning.
	[100%] Built target htmldoc
	mintadmin@mintadmin-VirtualBox ~/.../NeXus/definitions/build $ ll manual/
	total 24
	drwxr-xr-x 5 mintadmin 4096 May 29 10:56 CMakeFiles/
	-rw-r--r-- 1 mintadmin 1770 May 29 10:56 cmake_install.cmake
	drwxr-xr-x 9 mintadmin 4096 May 29 10:56 html/
	-rw-r--r-- 1 mintadmin 7333 May 29 10:56 Makefile
	drwxr-xr-x 8 mintadmin 4096 May 29 10:56 source/
	mintadmin@mintadmin-VirtualBox ~/.../NeXus/definitions/build $ ll manual/html/*.pdf
	ls: cannot access manual/html/*.pdf: No such file or directory
	mintadmin@mintadmin-VirtualBox ~/.../NeXus/definitions/build $

**Comment by prjemian** [comment]
Here's how the build/manual/html/index.html looks in firefox (with markup highlighting the problem):

![screen](https://cloud.githubusercontent.com/assets/2279984/7886904/d8fdb83c-05f2-11e5-9701-3ad5264d75cf.png)

**Comment by zjttoefs** [comment]
Okay, in the text you were referring to the main website, which is another problem. 
There is a separate build target pdfdoc to build the PDF. That makes sense, because then you can build something successfully without latex. 
I'm not convinced the generated PDF needs to reside in the HTML tree, but we can discuss here or at the telco.

**Comment by prjemian** [comment]
I can agree with that.  This is a change to the previous build of the documentation.
