### ISSUE TITLE
clarify Status of NAPI in the manual

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#413]
The manual is inconsistent with regards to its description of the current status of the NAPI.

Andy Gotz writes:

What is the status of the NAPI? I thought it is being maintained only for legacy applications and that it is not recommended for new applications. But this is not clear from the manual. In some places the reader gets the impression the NAPI is the official API for accessing files conforming to Nexus. In other places the opposite is stated and the hdf5 API is considered as the right way to access files.

What is the official policy on the NAPI?

**Comment by prjemian** [comment]
Tobias Richter writes:

The official policy just reflects the (perceived) requirements of the community. Your thoughts are correct NAPI is not recommended for new applications. And yes, the manual hasn’t been updated in all areas to reflect this. Please point us to the relevant sections you find unclear. Someone reading the texts with fresh eyes can really make a difference.

Since we focus on HDF5 now, the NAPI backend abstraction (supporting XML and HDF4 in addition) isn’t needed for that. NAPI also provides nothing that would ensure files follow the standard and very little that would at least make conforming easier. So the only benefit is some slight simplification of the hdf5 interface, which denies some of the power of the underlying container format.

That being said, NAPI is not disappearing any time soon, while people rely on it. We should drop support for unused bindings though.

In my view in the long run, some reference application or tools would still be needed to be able to demonstrate interoperability.

**Comment by prjemian** [comment]
Pete Jemian writes:

Andy:

Thanks for pointing this out. I agree that the manual may appear to be inconsistent with regards to the NAPI, as well as a few other things (backend storage file format, coordinate system, method to identify the default data for plotting, just to name a few).

Are there some obvious locations that make this point. Otherwise, my approach to editing and revising will be to start with a produced version (includes documentation content from both .rst files and NXDL files) and search it for terms such as "NAPI" or "how to access/read/write data".

Pete

**Comment by prjemian** [comment]
TODO:

* consistent present of NAPI status (as described above)
* emphasis on current backend file format
* describe the geometry (#397), long-standing concern, see #195
* describe the NIAC2014 method to identify the default data to be plotted, (see #380 but there is more to it than just the ``default`` attribute)
* move all mention of legacy components as revised above to secondary material, such as an appendix

**Comment by prjemian** [comment]
The current status of the NAPI is documented here, in the first three paragraphs:
http://download.nexusformat.org/doc/html/napi.html

Pending any further direction from the NIAC to the contrary, this will be used as the basis for applying consistency throughout the manual with regards to the status of the NAPI.

**Comment by prjemian** [comment]
Checking through the online minutes of the 2014 and 2012 NIAC meetings, there was no mention of a light version of the NAPI, only this question at the 2012 NIAC meeting:

    MK: Can we put NAPI into maintenance mode?

The text in the documentation describing that the NAPI has been "frozen:

http://download.nexusformat.org/doc/html/napi.html

was entered in the manual here:

https://github.com/nexusformat/definitions/commit/8565bda01bb79b72cd07c875efe3a204b9360a2b

and here

https://github.com/nexusformat/definitions/commit/9d8cbac2bbc091a41569cce882f05b40965f1ce6

What I have not found yet is any documentation of a NIAC agreement for the changes of text in those two commits. Perhaps this was discussed (and agreed) in the tech committee teleconferences. Perhaps "freezing the NAPI" was discussed at a NIAC meeting.

Regardless of the history now, which seems undocumented, do the first three paragraphs on the NAPI page of the manual represent NIAC's opinion of the current status of the NAPI?

http://download.nexusformat.org/doc/html/napi.html

**Comment by zjttoefs** [comment]
I think they do. The README in the code repo has just been updated as well.
