### ISSUE TITLE
clarify that the application definitions are allowed to define new fields

### ISSUE THREAD

**Issue by zjttoefs** [nexusformat/definitions#418]
This is required for a number of reasons but the documentation is a misleading:

http://download.nexusformat.org/doc/html/classes/base_classes/index.html

**Comment by prjemian** [comment]
Is this the part which is misleading?

NeXus base class definitions define the complete set of terms that might be used in an instance of that class.

Are there other parts of the documentation that mislead about fields declared in base classes vs. fields in application definitions?

**Comment by zjttoefs** [comment]
I've edited that place and one other instance in that pull request referenced here. 
No other wording I came across in a quick browse was as strong.
