### ISSUE TITLE
NXcanSAS: prepare for acceptance as application definition

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#420]
* [x] revise per latest NeXus data standards for axes: 37c3d46
* [x] revise per latest NeXus data standards for uncertainties: 8a82c44
* [x] revise per latest NeXus data standards for ... NXDL is compliant with nxdl.xsd
* [x] refactor legacy NXorientation, NXtranslation
* [ ] revise graphics
* [x] incorporate feedback from canSAS-VIII:  	5b7f51a,  	c361220
* [x] example data file converted from canSAS 1D XML data file examples
* [x] example data file from APS: several of the 1D example files are APS data (e.g., collagen, Round-Robin polymers, 1998 PS spheres)
* [x] example data file from ISIS
* [x] present to NIAC for acceptance: https://github.com/nexusformat/NIAC/issues/7
* [x] fix #369 (new style axes): https://github.com/nexusformat/definitions/issues/369#issuecomment-196887958

**Comment by zjttoefs** [comment]
We run a risk of adopting more things than we can document. I would suggest we fix #369 first.

**Comment by prjemian** [comment]
Of the outstanding issues in the canSAS2012 tracker:
https://github.com/canSAS-org/canSAS2012/issues

only two of them are marked for the *NIAC acceptance of NXcanSAS* milestone
(https://github.com/canSAS-org/canSAS2012/milestones/NIAC%20acceptance%20of%20NXcanSAS)

This should be presented at the NIAC for ratification as an application definition.
An example data file is in production from ISIS.  Another will be generated soon from the APS.

**Comment by prjemian** [comment]
moved canSAS2012 milestone to 2016-10-01 preceding NIAC2016

**Comment by prjemian** [comment]
repository for NXcanSAS examples has been created:
https://github.com/canSAS-org/NXcanSAS_examples

as noted in commit 4d47510

**Comment by prjemian** [comment]
NXcanSAS examples from canSAS1d posted in https://github.com/canSAS-org/NXcanSAS_examples/commit/db49bd512b4a4f32542bf08cb72c583ba2afb11d

**Comment by prjemian** [comment]
Version of NXCanSAS.nxdl.xml in the master branch does not contain the revisions that I expected today.  Presentation of this version to NIAC was a disaster.  One point of contention was the mapping of roll, pitch, yaw into NeXus angular nomenclature.  The revised version should have dropped this completely.

Recover content, some of which seems to be in the www_2016_demo branch. stay tuned ...

**Comment by prjemian** [comment]
Note that several of the 1-D example files are data from UNICAT 33ID-D USAXS at APS.  For example, the cs_rr_polymers.h5 data has several SASentry groups, from as many samples, and shows metadata that it was reduced through IgorPro ( raw_IgorPro_wavenote:NXnote group).

**Comment by prjemian** [comment]
refs #492: 2016NIAC review requested that NXinstrument become optional, done in 92dc0f5

**Comment by prjemian** [comment]
@zjttoefs : this is ready for a PR - should we have canSAS look it over first?

As I look at the 2012 specification document, it shows the SASinstrument as optional.

If canSAS review comes first, we'll need to build the docs separately so they can view the current specification exactly as it exists.  Otherwise, the revised docs will be built automatically by the NeXus build server and we can refer there.
