### ISSUE TITLE
Discrepancy between fields in NXdetector_module and NXtransformations

### ISSUE THREAD

**Issue by PeterC-DLS** [nexusformat/definitions#421]
The transformation fields in these two classes are nearly the same but subtly different:

NXdetector_module has for slow_pixel_direction an offset attribute defined as
```
		<attribute name="offset" type="NX_NUMBER">
			<doc>
				A fixed offset applied before the transformation
			</doc>
		</attribute>
```
whereas in NXtransformations has for each field
```
		<attribute name="offset" type="NX_NUMBER">
			<doc>
				A fixed offset applied before the transformation (three vector components).
			</doc>
		</attribute>
```

Assuming they should be the same, which one is correct?

**Comment by zjttoefs** [comment]
I don't see these as different. One is more precisely defined than the other. The intention was for them to be the same. 
Unless DIALS does something strange, which you can check at your end, editing the detector module to be more qualified would make sense.

**Comment by PeterC-DLS** [comment]
Thanks, it was just that it is not explicit that that offset is a translation (in position) so we at DLS had different interpretations...
