### ISSUE TITLE
NXdata group uses old signal/axis definitions

### ISSUE THREAD

**Issue by rayosborn** [nexusformat/definitions#434]
The current recommendation is to add 'signal' and 'axes' attributes to the NXdata group, but there are no group-level attributes in the NXdata NXDL file.

**Comment by prjemian** [comment]
created branch https://github.com/nexusformat/definitions/tree/issue_434 for this work

**Comment by prjemian** [comment]
The change for the group **signal** attribute to be implemented is described here:
http://wiki.nexusformat.org/2014_How_to_find_default_data

**Comment by prjemian** [comment]
Should the previous dataset attributes be marked as deprecated?

**Comment by prjemian** [comment]
The manual documentation needs to be updated, as well.
