### ISSUE TITLE
consider dropping my_lib from h5py examples

### ISSUE THREAD

**Issue by zjttoefs** [nexusformat/definitions#442]
Writing NeXus using h5py is fairly straight forward. I found the my_lib indirection confusing (not only for the name). If that makes the examples slightly more verbose the increased clarity makes up for it.

**Comment by prjemian** [comment]
This is a distinct possibility.  One of the examples uses only h5py, the others use my_lib.  But, the my_lib has moved on to become part of [spec2nexus.eznx](http://spec2nexus.readthedocs.org/en/latest/eznx.html)

**Comment by zjttoefs** [comment]
Certainly some library would be the way to do things for any project, Just for the sake of demonstrating what needs to be done I think the simple bare metal examples are better suited.
We'll leave this for the next revision, I guess.
