### ISSUE TITLE
NXentry/@entry attribute in application definitions

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#445]
In several of the application definitions, there is an attribute for the NXentry group called "entry".
Why is this defined?
Should it be removed?

```
$ grep attribute *.xml | grep name | grep entry
NXarpes.nxdl.xml:    <attribute name="entry">
NXiqproc.nxdl.xml:        <attribute name="entry">
NXsas.nxdl.xml:    <attribute name="entry">
NXsastof.nxdl.xml:    <attribute name="entry">
NXsqom.nxdl.xml:    <attribute name="entry"> </attribute>
NXxas.nxdl.xml:        <attribute name="entry">
NXxasproc.nxdl.xml:        <attribute name="entry">
```

**Comment by prjemian** [comment]
When it occurs, it appears like this example:

``` xml
  <group type="NXentry">
    <attribute name="entry">
      <doc>
		NeXus convention is to use ``entry1``, ``entry2``, ... 
		for analysis software to locate each entry
      </doc>
    </attribute>
    ...
```


Other NXDL files use this construction to suggest a name for the NXentry group:

``` xml
<group type="NXentry" name="entry">
```

**Comment by prjemian** [comment]
Why are there two different to suggest how to name the NXentry group?
Shouldn't that suggestion be placed in a documentation block since it can only be a suggestion?

**Comment by mkoennecke** [comment]
Pete,

Am 13.02.2016 um 15:42 schrieb Pete R Jemian <notifications@github.com<mailto:notifications@github.com>>:


In several of the application definitions, there is an attribute for the NXentry group called "entry".
Why is this defined?
Should it be removed?

$ grep attribute *.xml | grep name | grep entry
NXarpes.nxdl.xml:    <attribute name="entry">
NXiqproc.nxdl.xml:        <attribute name="entry">
NXsas.nxdl.xml:    <attribute name="entry">
NXsastof.nxdl.xml:    <attribute name="entry">
NXsqom.nxdl.xml:    <attribute name="entry"> </attribute>
NXxas.nxdl.xml:        <attribute name="entry">
NXxasproc.nxdl.xml:        <attribute name="entry">


—
Reply to this email directly or view it on GitHub<https://github.com/nexusformat/definitions/issues/445>.

this raises a whole can of worms. The first worm (the shiny yellow one) is the fact that we have two ways to specify group attributes in NXDL:

* directly in the tag
* as separate attribute tags.

This is an issue which we do not only have with groups but with fields too.

The other worm (the blue one) comes out of the problem how we validate NeXus files. An application definition can validate a NXentry or a NXsubentry.
Which  already defeats having name attributes for NXentries. For other groups under NXentry they still make sense though.

The other issue is that we may multiple NXentries in a file which validate against different application definitions stated in the definitions field.

Perhaps we should drop the name attribute on NXentry.

Regards,

    Mark

**Comment by zjttoefs** [comment]
I agree with @prjemian that these NXenrty/@entry attributes serve no purpose that I am aware of an would suggest we remove them. For NXapres this attribute is present only due to copy & paste.
