### ISSUE TITLE
update app defs & con defs per #443

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#447]
as noted in https://github.com/nexusformat/definitions/issues/443#issuecomment-186121108

**Comment by prjemian** [comment]
opened branch issue_447 for this work

https://github.com/nexusformat/definitions/tree/issue_447

**Comment by prjemian** [comment]
from https://github.com/nexusformat/definitions/pull/448#issuecomment-188335854

Wait for community review on each NXDL here before merge.

This may take some time to complete.
Some NXDL files may receive no review at all, could that be an indicator of lack of use? NIAC might consider deprecating such.

Suggest to merge into master (after 443 has been merged).

**Comment by zjttoefs** [comment]
I've created a discussion item for the NIAC:

￼https://github.com/nexusformat/NIAC/issues/4

I guess until that is done this ticket does not really need to be kept open.
