### ISSUE TITLE
Review: NXmirror

### ISSUE THREAD

**Issue by stuartcampbell** [nexusformat/definitions#45]
**Original reporter**: _[prjemian](https://github.com/prjemian)_
- incident_angle, bend_angle_x, bend_angle_y, substrate_thickness needs units[[BR]]
- reflectivity, m_value, *_roughness need to be NX_UNITLESS

**Comment by zjttoefs** [comment]
The base class has a number of TODO items. The main thing being lack of proper documentation. Someone with an interest in optics should have a look.

Quite a few of the fields requested in addition could be removed from the TODO list, as they to not appear to have been put in by people in practise so far.
