### ISSUE TITLE
Build failed in Jenkins: definitions-master 

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#456]
Somethings wrong with the Jenkins build with respect to the PDF version.  The error shows up in LaTeX.  Needs investigation.  Starts failing with this message:

```
<nexuslogo.png, id=5, 202.7575pt x 77.28876pt> <use nexuslogo.png>
<use nexuslogo.png> (/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1phv.fd)<<
ot1.cmap>> [1{/usr/share/texlive/texmf-dist/fonts/map/pdftex/updmap/pdftex.map}
 <./nexuslogo.png>] [2]
Adding blank page after the table of contents.
[1] [2] <NeXus.png, id=29, 405.515pt x 154.5775pt> <use NeXus.png> [1 <./NeXus.
png>] [2]
Chapter 1.
<use NeXus.png>

LaTeX Warning: Hyper reference `history:history' on page 3 undefined on input l
ine 177.
```  

Last message before LaTeX interrupts the build:

```
[5 <./Hierarchy.png>] <NXinstrument.png, id=71, 722.7pt x 542.025pt>
<use NXinstrument.png> <Simple1.png, id=72, 475.02469pt x 150.5625pt>
<use Simple1.png> (/usr/share/texlive/texmf-dist/tex/latex/psnfss/ts1pcr.fd)
[6 <./NXinstrument.png> <./Simple1.png (PNG copy)>]
<verysimple.png, id=86, 1141.26375pt x 485.815pt> <use verysimple.png>

! LaTeX Error: Something's wrong--perhaps a missing \item.
```

This is typical for some formatting or syntax error in the ReST source code (or a documentation block in the NXDL).  Inspection of the nexus.text file should be helpful.

**Comment by FreddieAkeroyd** [comment]
Had a quick look in http://build.nexusformat.org/job/definitions-master/ws/build/manual/build/latex/ and it seems the failing line includes graphics but is in a second level of \end{quote} unlike earlier ones that work, don't know if that helps at all
