### ISSUE TITLE
Impatient guide is not updating online after commits.

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#458]
Updates to the Impatient guide are not appearing online.
@FreddieAkeroyd : Doesn't this commit trigger a Jenkins rebuild of the manual and Impatient guide?

In #455, changes affecting the signal attribute were made (moved from field to NXdata group).

**Comment by prjemian** [comment]
Note that Jenkins reports the builds are successful and the PDF file contains the expected revisions.  Only the HTML is not updated.

**Comment by zjttoefs** [comment]
Cool. Much better than my stupid hack in the shell script.

**Comment by prjemian** [comment]
In the jenkins build log (https://build.nexusformat.org/job/definitions-master/lastSuccessfulBuild/consoleText), there is no indication that the previous build product was removed from the impatient-guide/_build directory.

**Comment by prjemian** [comment]
still no update to the HTML page

Looking at this part of the page, http://download.nexusformat.org/doc/impatient/#the-nexus-raw-data-file-hierarchy, the signal attribute has not been moved.

@FreddieAkeroyd : can you identify other reason why the HTML is not updated?  I think I have adjusted the build scripts as far as I can take them.
