### ISSUE TITLE
What happened to NXGoniometer

### ISSUE THREAD

**Issue by markbasham** [nexusformat/definitions#464]
It is referenced in https://github.com/nexusformat/definitions/issues/268 and is used in the Arpes Nexus files at DLS.  Should this just be replaced by a NXCollection?

**Comment by zjttoefs** [comment]
No, it has been replaced by NXtransformations 
Thanks for spotting that!

**Comment by zjttoefs** [comment]
Ah, we're not actually still referencing this. I just checked.
You just need to adapt the arpes files locally then, Mark.
