### ISSUE TITLE
doxygen build not current

### ISSUE THREAD

**Issue by zjttoefs** [nexusformat/definitions#473]
http://download.nexusformat.org/doxygen/

Is that worth fixing / keeping at all?

**Comment by prjemian** [comment]
@zjttoefs: Anything else to do with this issue?

**Comment by zjttoefs** [comment]
@FreddieAkeroyd can you delete what is offered under http://download.nexusformat.org/doxygen/
It's all never updated.

**Comment by prjemian** [comment]
@zjttoefs @FreddieAkeroyd : The URL still shows a directory of contents.
