### ISSUE TITLE
NXtransformations needs an equation in the documentation

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#484]
a start has been made (but commented out) since the vector math needs to be clear

\vec{p_{i+1}} = \vec{o_{i}} + \vec{V_{i}} * \vec{p_{i}}

V should actually be a matrix but the data described is a vector
Needs some help here.

**Comment by prjemian** [comment]
It's a bit more involved than that.  The field itself must have data (?an array?) that defines the transformation.  Call that T.  Then (T x v) x p_i would be for `transformation_type=rotation`. 

**None** of this is obvious from the documentation.  Let's sketch it out here, then update the documentation.

**Comment by prjemian** [comment]
Here's my best start on this:

		The entry point has a depends_on attribute with absolute or local HDF5 address.
		The depends_on field says that
		"entry point" is calculated from "depends_on" point
		
		A field may be depeneded on by several entry points.
		
		Hypothetical Example:		# needs to be confirmed
			diffractometer arm
			   detector slit
			   detector stage
			      detector mount
			         pixel location
		
		here:
		
		* pixel location is an entry point which depends on detector mount
		* detector mount is an entry point which depends on detector stage
		* detector stage is an entry point which depends on diffractometer arm
		* detector slit is an entry point which depends on diffractometer arm
		
		To compute the position of pixel location, we first construct the chain
		starting from the entry point, until the last "depends_on" which must be known.
		Then traverse the chain in reverse, starting from known positions
		and computing the points back to the entry position.
		
		* diffractometer arm position must be known
		* detector stage computed by its transformation from diffractometer arm
		* detector mount computed by its transformation from detector stage
		* pixel location computed by its transformation from detector mount

**Comment by prjemian** [comment]
There are *some* notes in the wiki:
http://wiki.nexusformat.org/Main_Page/NXdetector_2012_10

not enough for the documentation that is needed

**Comment by prjemian** [comment]
@mkoennecke : can you assist?

**Comment by PeterC-DLS** [comment]
Added equations in branch [issue-484] (https://github.com/nexusformat/definitions/tree/issue-484/base_classes)

**Comment by prjemian** [comment]
checked the documentation built for html and pdf, made revisions:

* d0d6e7f50d542c7c9d58dcfc3876d1888eb8210c
* 6f85ad62f279552c6aaa1a3a64f32b6a793adfab
* 4253445516ef4d99799881f80629aa3e771ec22d
