### ISSUE TITLE
revise main WWW page

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#486]
The main WWW page could use an update.  We could make it look more like the manual if we use Sphinx.  One model to follow would be the Sphinx web site.

**Comment by prjemian** [comment]
@rayosborn: I branched (https://github.com/nexusformat/definitions/tree/www_page_486) from your branch (https://github.com/nexusformat/definitions/tree/www_2016_demo) to work your proposal into the existing manual source.  It would be more work to move the manual to a new "doc" directory at this time.

**Comment by prjemian** [comment]
The manual now builds with the new home page.  This branch is not ready for PR yet.
Content on the main page needs to be fixed up.  Link to the "impatient" tutorial needs to be fixed.

"Contributor Guide" section needs changes or removal.

The big logo at the top of every page looks garish.  Discussion?

------------

To build the documentation, start in the root directory of "definitions":

    make makebuilddir

To *rebuild* incrementally the documentation, start in the root directory of "definitions":

    make remakebuilddir

To completely *rebuild* the documentation, start in the root directory of "definitions":

    make rmbuilddir makebuilddir

**Comment by prjemian** [comment]
Commit d759b4a0c414d046d6f74c825543a57ac70afe23 was extra large as this branch had languished since it was made half a year ago.  Would have been easier (less likely to have merge conflicts) if it had master merged in before recent work began.  Lesson relearned.

**Comment by prjemian** [comment]
PDF manual builds now, TOC is the master document and the depth is only one level for the PDF build

**Comment by prjemian** [comment]
Also, the space on the main html page above the NeXus logo is excessive.

Suggest we examine the new default RTD theme since it adapts to both portrait and landscape display.  It may be possible to import the technique into this theme -- or switch the theme.

**Comment by prjemian** [comment]
Perhaps this works? (refers to a very old version of the NeXus manual.  The current branch should be built as HTML and posted to its own branch for our review.)  Not sure that CSS styling is shown.

http://htmlpreview.github.io/?https://github.com/nexusformat/definitions/blob/www_page_486/www/download.nexusformat.org/index.html

**Comment by prjemian** [comment]
http://htmlpreview.github.io/?https://github.com/epics-modules/alive/blob/master/documentation/aliveRecord.html

look at this from EPICS

**Comment by prjemian** [comment]
we've displayed from a repository [previously](https://github.com/nexusformat/NIAC/issues/20#issue-182948568)

**Comment by prjemian** [comment]
@rayosborn 

1. Continuing the thought, you clone the master branch of  https://github.com/nexusformat/NIAC.git
2. replace the master branch content (with the new built copy of the html documentation) under this directory: ``2016/www_page_486``
3. commit & push back to the repository
4. then the draft of the manual is available via:  preview: https://htmlpreview.github.io/?https://github.com/nexusformat/NIAC/blob/master/2016/www_page_486/index.html

**Comment by zjttoefs** [comment]
The new web page is live. Both for wiki.n.o and www.n.o
Outstanding issues should be reported in the wiki repository from now on.

**Comment by prjemian** [comment]
**Don't delete** the related branch for this issue yet.  There are a couple commits that will be lost if not moved to the master.  Issue #539 and related branch [issue_539](https://github.com/nexusformat/definitions/tree/issue_539) have been created to address this point.

**Comment by zjttoefs** [comment]
Deleted the 486 branch now. I could restore it if needed.
