### ISSUE TITLE
NXlog 2016

### ISSUE THREAD

**Issue by mkoennecke** [nexusformat/definitions#502]
Update NXlog to reflect the decisions at NIAC 2016. As are:
- Add an optional scaling_factor attribute to the time field
- Clarify that value can be multi dimensional
- Add optional cue_time_zero and cue_index fields

**Comment by zjttoefs** [comment]
left open for a final check

**Comment by mkoennecke** [comment]
Doen, scaling_factor has become scaling

**Comment by zjttoefs** [comment]
That's not ideal for consistency reasons:
```
$ grep -r scaling base_classes/
base_classes//NXdata.nxdl.xml:	<field name="scaling_factor" type="NX_FLOAT">
base_classes//NXdata.nxdl.xml:			after scaling with a scale factor. This value is the scale
base_classes//NXlog.nxdl.xml:		specified in the units attribute. An optional scaling attribute
base_classes//NXlog.nxdl.xml:	<attribute name="scaling" type="NX_NUMBER"/>
```

I like the `NX_NUMBER` more than the `NX_FLOAT`, though.
