### ISSUE TITLE
Recording time-stamped data

### ISSUE THREAD

**Issue by mkoennecke** [nexusformat/definitions#503]
Update the manual with the decisions of the NIAC 2016 on how to store streamed data in NeXus files.

**Comment by zjttoefs** [comment]
NXlog has something and in the features there is code to explain it. At least that could be linked, but some examples and the fact that NXlog can replace datasets needs to be mentioned.

**Comment by prjemian** [comment]
@mkoennecke @zjttoefs Can either of you provide this documentation?

**Comment by zjttoefs** [comment]
I found a volunteer!

**Comment by prjemian** [comment]
2020 Code Camp: We might be able to resolve this by mining the features repo as suggested above (per NXlog).
