### ISSUE TITLE
Tag current versions

### ISSUE THREAD

**Issue by mkoennecke** [nexusformat/definitions#507]
Tag the nexus definition repository with the current versions available. As a start for the introduction of the new versioning scheme as decided at NIAC 2016

**Comment by prjemian** [comment]
We tagged version 3.2 during the Code Camp, prior to any new agreements at the NIAC.  

Q: Should the tag be advanced to include changes from NIAC2016 (such as optional NXdata)?

**Comment by mkoennecke** [comment]
No, what I mean with that is to go through all application definitions and base classes we have and 
look their versions. If for example we find a version of 1.0 in NXsomething, we just tag the repository with NXsomething-1.0. This is to get a start on the new versioning scheme.

**Comment by prjemian** [comment]
Hypothetically, for N definitions with a "1.0" version, we create N tags in the definitions repo, right?

**Comment by prjemian** [comment]
for example: [NXcanSAS-1.0](https://github.com/nexusformat/definitions/releases/tag/NXcanSAS-1.0])

**Comment by mkoennecke** [comment]
Yes, I mean that and I know we create a lot of tags. 86 to be exact.  But how else are we to capture the current starting state? Do you have a better idea? 

But if you have doubts we can defer the operation until we have discussed that a Telco.

**Comment by prjemian** [comment]
That's OK, just wanted to confirm before proceeding.

**Comment by prjemian** [comment]
@mkoennecke : Please review the list of tags.  
https://github.com/nexusformat/definitions/tags

If satisfactory, close this issue.

**Comment by mkoennecke** [comment]
Thanks a lot Pete. This looks good.
