### ISSUE TITLE
Allow pixel as units at least for beam centre

### ISSUE THREAD

**Issue by zjttoefs** [nexusformat/definitions#511]
Find out what the right unit name is. Does UNIDATA have that?

**Comment by zjttoefs** [comment]
Also: Where does this permission go in the repository. We are completely liberal with length units at the moment, there is no list of allowed units. (Should there be?)

**Comment by rayosborn** [comment]
We need to update the NXdetector.nxdl file, and all application definitions that use it, since the beam_center_x and beam_center_y descriptions say "This is a length, not a pixel position, and can be outside of the actual detector."

**Comment by zjttoefs** [comment]
Eugen reckons "px" would be a fine choice.

Documentation should state "use unidata or px if you have to record in pixels" or something not too encouraging.

**Comment by prjemian** [comment]
make these changes in a new branch: such as "pixel_as_length_issue_511"

**Comment by zjttoefs** [comment]
Herbert creates a branch for us to develop this idea.

**Comment by yayahjb** [comment]
The list of all "not a pixel" comments in branch pixel_as_length_issue_511 is

applications/NXcanSAS.nxdl.xml:            This is a length, not a pixel position, and can be outside of the actual
applications/NXcanSAS.nxdl.xml:            This is a length, not a pixel position, and can be outside of the actual
applications/NXmx.nxdl.xml:                                             detector. This is a length, not a pixel position, and can be
applications/NXmx.nxdl.xml:                                             detector. This is a length, not a pixel position, and can be
applications/NXsas.nxdl.xml:                            length, not a pixel position, and can be outside of the actual detector.
applications/NXsas.nxdl.xml:                            length, not a pixel position, and can be outside of the actual detector.
applications/NXsastof.nxdl.xml:                length, not a pixel position, and can be outside of the actual detector.
applications/NXsastof.nxdl.xml:                  length, not a pixel position, and can be outside of the actual detector.
applications/NXxrot.nxdl.xml:              length, not a pixel position, and can be outside of the actual detector.
applications/NXxrot.nxdl.xml:                length, not a pixel position, and can be outside of the actual detector.
base_classes/NXdetector.nxdl.xml:           This is a length, not a pixel position, and can be outside of the actual
base_classes/NXdetector.nxdl.xml:           This is a length, not a pixel position, and can be outside of the actual

If we merge the branch NXmx_multimodule_and_dectris_changes, those will all be gone.

**Comment by prjemian** [comment]
Can you make the proposed changes in the *pixel_as_length_issue_511* branch instead?  This branch is even with master at this time.

The branch *NXmx_multimodule_and_dectris_changes* *is 9 commits ahead, 64 commits behind master.*  If you must make these changes in this other branch, please merge master into this branch and then push the revised branch back to GitHub so we can see these changes against the current master.

**Comment by yayahjb** [comment]
I have now brought NXmx_multimodule_and_dectris_changes up to the level of
master*.  *The use of pixels as a length is just a part of the necessary
dectris changes so far.  I would suggest putting that full set of changes
to bed before doing further changes to the handling of pixels, but using
*pixel_as_length_issue_511* to discuss any such further changes, so we
don't hold up the dectris changes any more than necessary.

**Comment by prjemian** [comment]
NXcanSAS passes my spot check, thanks for the work on this

**Comment by prjemian** [comment]
@yayahjb @zjttoefs - Is there more work to be done on this issue or can it be closed now?

**Comment by zjttoefs** [comment]
I believe that's complete.

**Comment by prjemian** [comment]
I see this issue closed but the [branch](https://github.com/nexusformat/definitions/tree/pixel_as_length_issue_511) is still open.  Since the branch has no commits *beyond* master (and is only hundreds of commits behind master), can the branch be removed?  Were all the commits made directly to master?  Perhaps referenced to other issues or none at all?

**Comment by yayahjb** [comment]
I see no reason not to remove the branch, unless somebody else needs it
there to try something they have in mind. -- Herbert
