### ISSUE TITLE
apply travis-ci continuous integration

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#513]
http://travis-ci.org/nexusformat/definitions can be used to apply unit testing after every commit, giving a report if a commit introduces problems, such as syntax errors (see aad0034, 3d2b473, & 32b130a).

follows  #512

**Comment by prjemian** [comment]
@zjttoefs : Can you add administrator/owner/whatever permission for me to the nexusformat/definitions repository?  I want to work on issue #513 (travis-ci runs of NXDL validity for each commit) for which I will need this.

**Comment by zjttoefs** [comment]
@prjemian You're now an owner.

**Comment by prjemian** [comment]
fixed in #514
