### ISSUE TITLE
NXsas: review use of minOccurs on various components

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#522]
For base classes, minOccurs=0 is the default and means the dataset is optional.  For application definitions, the default is minOccurs=1 which means it is required.  (HDF5 imposes maxOccurs=1 since item names must be unique within a group).

add: NXsas [documentation](https://manual.nexusformat.org/classes/applications/NXsas.html#nxsas)

**Comment by prjemian** [comment]
important to make next milestone

**Comment by prjemian** [comment]
Do this with a branch+PR

**Comment by zjttoefs** [comment]
NXsas has no instances of max* or minOccurs. What is there to review? Is this a proposal to change the application definition?

**Comment by prjemian** [comment]
The application definition should be examined to determine which components *must* be given or that some components need a declaration of `minOccurs=0`.  For example, *must* `NXsample` always be provided?  Must the `NXdata` group only be named `data`?

**Comment by benajamin** [comment]
@prjemian is this (and [NIAC#58](https://github.com/nexusformat/NIAC/issues/58)) still relevant?

**Comment by prjemian** [comment]
@benajamin : Yes, and Yes.

@zjttoefs You [asked above](https://github.com/nexusformat/definitions/issues/522#issuecomment-419442200):
> NXsas has no instances of max* or minOccurs. What is there to review? Is this a proposal to change the application definition?

We should review the definition with this question:

* Is the NXsas definition missing these attributes (max* or minOccurs)?

If they are missing (it is likely the existing application did not consider these attributes) and the need for them sufficient, we should propose changes to NXsas in a branch.

**Comment by prjemian** [comment]
This is the structure of the NXsas definition at this time.  None of the items are marked optional or minOccurs=0:

```
NXsas (application definition)
  (overlays NXentry)
  NXentry
    @entry
    definition:NX_CHAR
    end_time:NX_DATE_TIME
    start_time:NX_DATE_TIME
    title:NX_CHAR
    data:NXdata
      data --> /NXentry/NXinstrument/NXdetector/data
    instrument:NXinstrument
      name:NX_CHAR
      collimator:NXcollimator
        geometry:NXgeometry
          shape:NXshape
            shape:NX_CHAR
            size:NX_FLOAT
      detector:NXdetector
        aequatorial_angle:NX_FLOAT
        azimuthal_angle:NX_FLOAT
        beam_center_x:NX_FLOAT
        beam_center_y:NX_FLOAT
        data:NX_NUMBER[nXPixel,nYPixel]
        distance:NX_FLOAT
        polar_angle:NX_FLOAT
        rotation_angle:NX_FLOAT
        x_pixel_size:NX_FLOAT
        y_pixel_size:NX_FLOAT
      monochromator:NXmonochromator
        wavelength:NX_FLOAT
        wavelength_spread:NX_FLOAT
      source:NXsource
        name:NX_CHAR
        probe:NX_CHAR
        type:NX_CHAR
    control:NXmonitor
      integral:NX_FLOAT
      mode:NX_CHAR
      preset:NX_FLOAT
    sample:NXsample
      aequatorial_angle:NX_FLOAT
      name:NX_CHAR
```
