### ISSUE TITLE
add machine-readable unit string for each NeXus units type

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#530]
To validate the engineering units provided with a field, each field is assigned one of the NeXus units types listed in the file ``nxdlTypes.xsd``.  At this time, NeXus states that the ``units`` attribute is not validated.  With use of the UDUNITS-2 C library, it is possible validate such strings.  To make that a possibility, each of the specifications for units will have to be modified such that the example becomes both machine-readable (defined in its own XML element) and the example must be compatible with what UDUNITS-2 will accept (which is very broad).

This change will require an addition to the NeXus XML Schema (``nxdl.xsd``) to allow for the new content.

**Comment by prjemian** [comment]
For example, this existing specification:

    <xs:enumeration value="NX_CROSS_SECTION">
        <xs:annotation>
            <xs:documentation>example: barns</xs:documentation>
        </xs:annotation>
    </xs:enumeration>

could (for example) be changed to:

			<xs:enumeration value="NX_CROSS_SECTION">
				<xs:annotation>
					<xs:documentation>
						cross sectional area of a scattering process
						<xs:element name="example">barn</xs:element>
						<xs:element name="example">m2</xs:element>
					</xs:documentation>
				</xs:annotation>
			</xs:enumeration>

note: The process that builds the manual documentation from these enumerations will need to be revised in consequence to this change.

**Comment by eugenwintersberger** [comment]
Sounds like avery reasonable idea to me.
