### ISSUE TITLE
add "mask" attribute to NXdata

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#533]
The "mask" attribute (like the uncertainties attribute) names the field (dataset) that contains the mask data.  The name is flexible but the recommended name is (data)_mask where (data) is the data to be masked.

It must have the same shape as (data).

The value of the mask field may be either a boolean array where false=no mask, true=mask or the more descriptive array as defined in NXdetector

**Comment by prjemian** [comment]
@rayosborn , @yayahjb : comments before I begin on this?

**Comment by rayosborn** [comment]
Looks okay to me. If the mask is int32 as required in NXdetector, then a boolean check would still work with this definition, but I'll have to check if I need to change any NeXpy code. At the moment, I assume that the mask can be used to create a Numpy masked array. It shouldn't be a problem.

**Comment by prjemian** [comment]
Is it better to have the attribute on the field or the group? What are the
chances of having more than one mask in a group?

@jilavsky: opinion?

**Comment by jilavsky** [comment]
While I do not plan to implement more than one mask myself, I can imagine having good reason for multiple masks. For example common mask for chip layout and damaged pixels. This one is common for all experiments done with specific detector. And second mask, which masks beamstop and other hardware and depends on specific setup for specific user. For purpose of future flexibility I suggest assuming that multiple masks may be needed.

**Comment by prjemian** [comment]
With the "mask" attribute at the group level, it is like the "signal" attribute.  It designates one mask (of many possible present) as the "chosen".

With the "mask" attribute on the field, it says this is *the* mask to use with this field.

@jilavsky: your comments seem to support the choice of: "mask" attribute at the group level

**Comment by toqduj** [comment]
@jilavsky this is not necessarily incompatible with the current int32 implementation: you can indicate that a pixel is both masked because it's shit, as well as because it's behind a beamstop. It's a quite nice definition in that sense.

**Comment by prjemian** [comment]
Does not look like this will be resolved to a PR by the end of March.  Move to next milestone for now.

**Comment by prjemian** [comment]
this will be resolve by #840, closing as duplicate here
