### ISSUE TITLE
NXcanSAS: Units dictionary for I & Q related terms

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#534]
Providing a units dictionary for NXcanSAS has been discussed in the canSAS Google Group:
https://groups.google.com/forum/#!topic/cansas-dfwg/pItbRKXeFfE

In [the NeXus manual section: NeXus Data Units](http://download.nexusformat.org/doc/html/datarules.html?highlight=units#nexus-data-units), it says *Application definitions may specify units to be used for fields using an enumeration.*

**Comment by prjemian** [comment]
I will move the tag in NeXus for "NXcanSAS-1.0" as the new units changeset is pushed to GitHub.  Since the NeXus definitions release tag includes NXcanSAS-1.0, I will advance the definitions "v3.2" release tag there as well.

**Comment by zjttoefs** [comment]
This concrete case aside (what's done is done and the community appears to be onboad), but moving release tags is not the idea we had with the versioning. Especially when there are implementations of the "old" release tag out in the wild. Correct me if I'm wrong @mkoennecke 

Next time a case like this comes up we should use that as a opportunity to try out our new scheme and see how we do provide documentation for then superceeded definitions.

**Comment by prjemian** [comment]
Thought this *was* the new scheme.  We need to clarify what are the steps.

**Comment by mkoennecke** [comment]
Hi,

Am 19.01.2017 um 14:10 schrieb Pete R Jemian <notifications@github.com<mailto:notifications@github.com>>:

Thought this *was* the new scheme. We need to clarify what are the steps.


the necessary steps where documented in the NIAC 2016 minutes.
The use case though is an enhancement/change in the base class or application definition NXDL:

You change the NXDL and increment the version in the NXDL file
In order to save the old state, you build a new manual and commit it together with the state.
You tage with NXxxxxx-1.x with xxx being a name and 1.x the relevant version

Regards,

    Mark

**Comment by prjemian** [comment]
This change was not the substantive change justifying an increment in 
the minor version number (in the sense of semantic versioning where 
major.minor.patch is used).  The change was a matter of completion of 
the 1.0 initial release based on strong reaction in the community, to 
add something that was missing but did not change in any substance the 
definition.  Thus the choice to move tag.

As for moving the v3.2 definitions tag and release, as stated, I thought 
this was the agreed procedure as we discussed it at NIAC2016.  This is 
not the first time the v3.2 tag was moved.  Originally, v3.2 was tagged 
at the start of the NIAC2016 meeting.  Later, after the decision to make 
NXdata an optional child of NXentry (& NXsubentry), the tag & release 
were moved.  This move of tag & release was in the spirit as the move 
after the NXdata decision.

This is the very example that justifies the use of the patch revision 
level.  The addition to the existing NXcanSAS-1.0 definition of lists of 
expected units for intensity and Q (and related terms) would best be 
indicated as NXcanSAS-1.0.1, certainly not NXcanSAS-1.1.  And the latest 
definitions repository release would now be at v3.2.2 if patch level 
versioning were accepted.

Pete

**Comment by zjttoefs** [comment]
Sounds like wrapping this up at the next Telco (or the one after as Pete has limited time at the next one) is a good idea.
I advocated creating a new version because then the existing data files keep their valid documention and we need to try out the new scheme anyway. But we can discuss.

**Comment by prjemian** [comment]
the git log shows that previous to this change

    Tag: v3.2
    object c0b950028bd5c7a05ab16d0dfca94fbcf84bdb65

    Tag: NXcanSAS-1.0
    object 375d3808c8f2b1a4f9de1fb1762fd87862b94bcd

**Comment by prjemian** [comment]
canSAS agreed there were no existing data files to be supported

See remarks from Andrew Jackson on Jan 16 at this URL:
https://groups.google.com/forum/#!topic/cansas-dfwg/pItbRKXeFfE
