### ISSUE TITLE
revise or remove the suggestion in NXpositioner

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#535]
In the documentation for [NXpositioner](http://download.nexusformat.org/doc/html/classes/base_classes/NXpositioner.html), it states in the first paragraph:

> Note: When using multiple NXpositioner groups, it is suggested to place them inside a NXcollection group. In such cases, when NXpositioner is used in another class, NXcollection/NXpositioner is then constructed.

This is wrong and must be changed.  The [NXcollection](http://download.nexusformat.org/doc/html/classes/base_classes/NXcollection.html) documentation states:

> An unvalidated set of terms, such as the description of a beam line.
...
> Anything (groups, fields, or attributes) placed in an NXcollection group will not be validated.

It is the clear intent of *NXcollection* that all content within (and beneath) that group will not be validated.

Find or create a different container for multiple *NXpositioner* groups.

**Comment by prjemian** [comment]
There is no clear choice for a container group.  For [NXdetector](http://download.nexusformat.org/doc/html/classes/base_classes/NXdetector.html), there are two related base classes:

* [NXdetector_group](http://download.nexusformat.org/doc/html/classes/base_classes/NXdetector_group.html): Logical grouping of detector elements.
* [NXdetector_module](http://download.nexusformat.org/doc/html/classes/base_classes/NXdetector_module.html): Geometry and logical description of a detector module.

Perhaps we follow this pattern for positioners?

**Comment by zjttoefs** [comment]
NXpositioner is not overly used in the files I've come across. A lot of the heavy lifting for positioning samples or detectors is done in CIF style geometry with NXtransformations. 

So far there has been not much need to group base classes of the same type. NXinstrument expects them flat. The detector examples are special because they have shared information (at least for the module).
