### ISSUE TITLE
Build the manual in travis-ci

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#537]
Taking inspiration from a different GitHub project suite, can we build the NeXus manual as part of the travis-ci script, then push to GH pages for publishing?

This would duplicate the jenkins build and copy process currently running at nexusformat.org

**Comment by zjttoefs** [comment]
We certainly can, I've done that for canSAS (I believe). It's also worth considering, but not before the web page has moved over (that currently gets published from a definitions build).
Even then it's a case of "never touch a running system": Once we need to make changes anyway, I'd be happy to do it.

**Comment by prjemian** [comment]
Great!  Manual [builds](https://travis-ci.org/nexusformat/definitions/builds/243014738) (no PDF for now, see #570) in py2 and py3.

Next step before this issue can be closed is to copy the built manual to our published site (presumably a GitHub pages site).

**Comment by prjemian** [comment]
some one has written this up for us on [StackOverflow](https://stackoverflow.com/questions/23277391/how-to-publish-to-github-pages-from-travis-ci#33125422)

**Comment by prjemian** [comment]
No *latexmk* on travis-ci now, latexpdf [failed](https://travis-ci.org/nexusformat/definitions/jobs/243034665)

**Comment by prjemian** [comment]
Travis-ci needs to include support for building LaTeX documentation.  Until then, travis-ci [cannot be used](https://github.com/travis-ci/travis-ci/issues/7772#issuecomment-309111559) to build both HTML and PDF versions of the NeXus documentation.
