### ISSUE TITLE
datarules.rst contains information on 2014 discussions

### ISSUE THREAD

**Issue by zjttoefs** [nexusformat/definitions#541]
We should revise what has been accepted and put that in the manual directly.
Could be up for discussion what level of in progress material is right for the manual.

**Comment by prjemian** [comment]
edit the part related to "2014 discussion"

**Comment by prjemian** [comment]
Do this with a branch+PR

**Comment by prjemian** [comment]
2020 Code Camp: Has any of this work already been completed?  Where?  Push this off to next milestone.

**Comment by prjemian** [comment]
2014 minutes: https://www.nexusformat.org/NIAC2014_Meeting#Minutes.html

Is this about the uncertainties and axes attributes or are there other items to act on?

**Comment by prjemian** [comment]
@benajamin Please identify what proposals were approved that still need to be acted on.

**Comment by PeterC-DLS** [comment]
The page that's always not linked to correctly: https://www.nexusformat.org/2014_axes_and_uncertainties.html

**Comment by prjemian** [comment]
That link is already in the manual, it appears here https://manual.nexusformat.org/datarules.html#examples as the footnote `(7)`.

> More examples are available in the NeXus webpage (7).

**Comment by prjemian** [comment]
Back to the original statement:

> We should revise what has been accepted and put that in the manual directly.

Here is my analysis of approved items from [NIAC2014](https://www.nexusformat.org/NIAC2014_Meeting#Minutes.html) minutes that have not yet been acted upon:

* **CIF style marked as preferred method ...** (#)
* **Vote on proposal for NXdata axes ...** (#)
* **Clarification decision:  ...** (#)
* **“rgbimage”, “rgbaimage”,  ...** (#)

**Comment by prjemian** [comment]
This reST link target in `datarules.rst`:

```
.. _Design-FindPlottable-NIAC2014:
```

is used elsewhere in the manual, such as:

```
manual/source/datarules.rst:   Perhaps substitute with the discussion from NIAC2014?
manual/source/examples/code_napi.rst:   New code should use the method described in :ref:`Design-FindPlottable-NIAC2014`.
manual/source/examples/code_native.rst:   in :ref:`Design-FindPlottable-NIAC2014` for indicating plottable data.
manual/source/history.rst:    See the description in :ref:`Design-FindPlottable-NIAC2014`
manual/source/rules.rst:  as described in :ref:`Design-FindPlottable-NIAC2014`.
```

The section linked, `:ref:`Design-FindPlottable-NIAC2014` contains the footnote mentioned above.

**Comment by prjemian** [comment]
Closing this issue since new issues have been created for each remaining approval from NIAC2014.
