### ISSUE TITLE
NXtransformations adds units attribute to vector attribute

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#547]
This is an error (in both HDF5 and XML).

Neither HDF5 nor XML attributes can have attributes themselves. As-is, this would result in a specification where a data file would specify a ``vector`` attribute which would, by the specification now, have a ``units`` attribute which could be assigned a value compatible with ``NX_DIMENSIONLESS``.

**Comment by prjemian** [comment]
Here is the code with the error:

		<attribute name="vector" units="AXISNAME" type="NX_NUMBER">
			<doc>
				Three values that define the axis for this transformation.
				The axis should be normalized to unit length, making it
				dimensionless.  For ``rotation`` axes, the direction should be
				chosen for a right-handed rotation with increasing angle.
				For ``translation`` axes the direction should be chosen for
				increasing displacement.
			</doc>
			<dimensions rank="1" value="3" />
		</attribute>

**Comment by prjemian** [comment]
Because is a design error that interrupts validation, it is high-priority to resolve.

**Comment by prjemian** [comment]
suggest adding a ``vector_units`` attribute to provide the requested information

**Comment by zjttoefs** [comment]
The documentation clearly states that vector is dimensionless. A units attribute is not required.
