### ISSUE TITLE
NXtransformations has attributes that define dimensions

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#548]
This is an error (incompatible with ``nxdl.xsd``).

		<attribute name="vector" units="NX_DIMENSIONLESS" type="NX_NUMBER">
			<doc>
				Three values that define the axis for this transformation.
				The axis should be normalized to unit length, making it
				dimensionless.  For ``rotation`` axes, the direction should be
				chosen for a right-handed rotation with increasing angle.
				For ``translation`` axes the direction should be chosen for
				increasing displacement.
			</doc>
			<dimensions rank="1" value="3" />
		</attribute>

Need to identify if there is an XML Schema syntax to provide this directive.  The ability to describe the shape explicitly is likely useful in other base classes.

**Comment by prjemian** [comment]
Also in NXmx:

	<field name="incident_beam_size" type="NX_FLOAT" units="NX_LENGTH"  minOccurs="0">
		<doc>
			Two-element array of FWHM (if Gaussian or Airy function) or
			diameters (if top hat) or widths (if rectangular) of beam
			in the order x, y
		</doc>
		<dimensions rank="1" value="2" />
	</field>

**Comment by prjemian** [comment]
At least three ways to resolve this issue:

1. add attributes for rank and length to each field
2. add ``dimensions`` rule to XML Schema ``nxdl.xsd``
3. add attribute for each value to each field

## Question: array attributes

* [ ] Do we already accept arrays as attribute values in data files?
* [ ] Is this supported in the NAPI?

**Comment by prjemian** [comment]
@zjttoefs : what was the conclusion for this issue at today's [telco](http://www.nexusformat.org/Telco_20170405.html)?

**Comment by zjttoefs** [comment]
The conclusion was to remove the `units="NX_DIMENSIONLESS"` vector should not have units.
I notice now that doesn't address the ticket. Of you three suggested solutions I would pick No 2. But you may have a better idea. We need to support this.

**Comment by prjemian** [comment]
Going with [2].  From comments in `nxdl.xsd`, looks as if this was intended but not implemented.  An oversight.  In `nxdl.xsd` see comment in this definition: `<xs:complexType name="dimensionsType">`
