### ISSUE TITLE
Make NXreflections a base class

### ISSUE THREAD

**Issue by phyy-nx** [nexusformat/definitions#574]
This is the last outstanding item from the last NIAC.  Is there more to this than moving the file from contributed_definitions to base_classes and changing the class listings in section 3.3 of the manual?

**Comment by prjemian** [comment]
Moving it from contributed to base classes is the NIAC ratification process.  Has the NIAC already ratified NXreflections?

Once it moves, the automation that publishes the documentation will pick that up and present this class in its new classification.

**Comment by prjemian** [comment]
note: this task is asynchronous from a definitions 3.3 release, removed that milestone assignment

**Comment by phyy-nx** [comment]
Yes it was ratified

http://www.nexusformat.org/NIAC2016Minutes.html
Accepted as a base class with 12 yes, with the changes listed above

**Comment by prjemian** [comment]
OK, I'll make that move later today.  Will close this issue with that action.

**Comment by phyy-nx** [comment]
Thanks
