### ISSUE TITLE
NXslit: add blade positions: top, left, bottom, right

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#585]
according to the NeXus coordinate frame and beam direction

**Comment by eugenwintersberger** [comment]
As the title of this issue says could we add the blade positions of slits to NXslit. Suggested names would be 

* top
* left
* bottom
* right

**Comment by zjttoefs** [comment]
The problem is that people will disagree on whether to look into the beam or along the beam.
Hence my xpos xneg ypos yneg proposal, which references the coordinate system.
In principle you can rotate the slit in the depends_on and make it all confusing in either case.

**Comment by prjemian** [comment]
Moving this out of the milestone for "NXDL 3.3" since the discussion may go longer.

**Comment by rayosborn** [comment]
On the other hand, if the documentation states that the terms refer to looking along the beam, which is the standard NeXus default (+z is along the beam), there is no confusion. Top, bottom, left, right are a bit more intuitive.

**Comment by prjemian** [comment]
top, left, bottom, right seem very intuitive, yet it imposes an unnecessary divide in our community, as already identified

xpos, xneg, ypos, yneg are consistent with terms related to coordinate axes in other classes and do not carry the burden of being defined relative to looking into or with the beam

**Comment by eugenwintersberger** [comment]
Well, concerning the beam: isn't the coordinate system defined by the beam and thus you have to know the beam direction anyhow if you want to know in which direction x and y goes?

**Comment by zjttoefs** [comment]
The indirection through the coordinate system makes it somewhat neutral. What the beamline people think is "left" and "right" may have been decided independently for their environment decades ago. If we force them to use it the "wrong" way they will either not follow or confuse their users. Not sure what's better.

You can always add a @local_name attribute.

**Comment by toqduj** [comment]
One more issue with this, J.S. Pedersen uses a slit set rotated 45 degrees, to get an octagonal beam. This wouldn't work anymore with LRUD, nor with x/y pos/neg (xypos, xyneg, yxpos, yxneg; super confusing). 

We'd have to indicate the vector of motion and on which side of the beam it's on. Can we use unicode?

**Comment by zjttoefs** [comment]
You can rotate the slit obviously, using the depends_on and a rotation transformation. 

For string content we have the implied agreement that UTF-8 should be allowed. Not for dataset (field) names, though. How is this question related?

**Comment by prjemian** [comment]
Refer to the manual's figure of the [NeXus coordinate system](http://download.nexusformat.org/doc/html/design.html#nexus-coordinate-systems), there is a clear description of positive and negative for X and Y axes.  Isn't Pedersen's octagonal slit system actually two sets of rectangular X/Y slits, one rotated 45 degrees to the other?  I agree with the suggestion of @zjttoefs to use a rotation transformation for the appropriate component.  

So far, we are not converging on acceptable names for the slit blades that do not come burdened by how one views the slit plane.  What's unacceptable about the terms `top`, `left`, `bottom`, and `right` is that, for those whose instruments use the *other* reference view, the terms would be incorrect descriptors.

**Comment by prjemian** [comment]
on discussion, the present version is adequate and no action needs to be taken.  A NXtransformations chain can position and/or rotate the slit as desired.
