### ISSUE TITLE
NeXus manual html pages in .zip file

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#587]
@jilavsky asks *why zip file with html version [of NeXus documentation] is not available?*

**Comment by prjemian** [comment]
This could be added to the jenkins build without much trouble.

**Comment by prjemian** [comment]
OTH, this begins to look like an epub version.

**Comment by prjemian** [comment]
I'd be happy with closing this issue as unresolved.

**Comment by zjttoefs** [comment]
That makes three of us that don't see a strong need. I've got nothing against offering a zip, if someone was to issue a pull request, though.
