### ISSUE TITLE
NXdetector seem to require 4 dimensional data

### ISSUE THREAD

**Issue by zjttoefs** [nexusformat/definitions#590]
The [manual](http://download.nexusformat.org/sphinx/classes/base_classes/NXdetector.html) renders as:

`data[np, i, j, tof]: (optional) NX_NUMBER {units=NX_ANY}`

To the newcomer it is not obvious how this should be interpreted. The x and y pixel offsets also require 2 dimensions according to the XML, but in the text they say **can** be multidimensional, if needed. 

There could be a whole host of XSD magic with `<choice>`, but getting any references right will be a mess. 

What to do?

**Comment by mkoennecke** [comment]
Telco comment: improve documentation

**Comment by prjemian** [comment]
@zjttoefs @mkoennecke Who will do this work?

**Comment by zjttoefs** [comment]
I don't have a good solution. Otherwise I would do something.

**Comment by prjemian** [comment]
This may be closed as "unresolved" due to lack of a sponsor

**Comment by zjttoefs** [comment]
That seems a bit unfair, given that we have 47 tickets in the backlog, some untouched for years.

**Comment by prjemian** [comment]
We should add words that assert that the definition is more flexible and more than one rank is allowed.  This could be presented in the description and *also* in the documentation for the **data** field.

**Comment by prjemian** [comment]
Needs English wordsmithing to make this clear.  Perhaps other definitions  could benefit also.

**Comment by zjttoefs** [comment]
As mentioned in the referenced ticket this can also have validation effects.

**Comment by prjemian** [comment]
Could this be coupled with #412?

**Comment by phyy-nx** [comment]
Yup, @yayahjb and I will work on this.

**Comment by woutdenolf** [comment]
The new rendering of the dimensions field (PR https://github.com/nexusformat/definitions/pull/1086) may help. For this particular field the old rending looks like this

![image](https://user-images.githubusercontent.com/7264703/173606578-c32eb33e-720a-4c32-9862-9742d1abf552.png)

the new rendering (still in review) looks like this

![image](https://user-images.githubusercontent.com/7264703/173606909-16fed969-3d88-4bc1-b67a-9c23031d65c7.png)
