### ISSUE TITLE
add example writing NeXus file from EPICS area detector using HDF5 plugin

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#605]

**Comment by rayosborn** [comment]
Where is the document you are updating? We will be using areadetector on Sector 6 and need to see what is being suggested. Is this something requested by Mark Rivers?

**Comment by prjemian** [comment]
I'm finishing up the editing now.  Doug Robinson (APS XSD 6-ID) and Mrinal Bera (APS CARS 15-ID) both asked for advice about how to configure the HDF5 File Writing Plugin of the EPICS Area Detector software to write NeXus files.  The email I sent them is the basis for this new example.  Just a couple more minutes.

**Comment by prjemian** [comment]
So far, the document is almost empty when it comes to configuring the `layout.xml` file.  It uses the standard layout from AD.  This should work for most uses.

**Comment by prjemian** [comment]
Look for section 2.1.5 on the [examples](http://download.nexusformat.org/doc/html/examples/index.html#code-examples-in-various-languages) page
might take a few minutes to rebuild
