### ISSUE TITLE
remove version attribute from NXDL Schema

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#616]
Per https://github.com/nexusformat/definitions/issues/597#issuecomment-378288498, remove the version attribute from `nxdl.xsd` and ***ALL*** the NXDL files.

This *will* compel a new minor release of the schema itself.

**Comment by prjemian** [comment]
Do this work in a branch.

**Comment by zjttoefs** [comment]
Would you think this is required for the current milestone? Would certainly be nice to have all changes to versioning done in one go.

**Comment by prjemian** [comment]
Let's keep this in the current milestone.  As you said: "[We're almost there.](https://github.com/nexusformat/definitions/issues/597#issuecomment-386018812)"

**Comment by prjemian** [comment]
BUT, I will bump the milestone to the end of this month, to keep it consistent with reality.

**Comment by prjemian** [comment]
The new tag Schema-3.4 should follow #619 and its PR 622.

**Comment by prjemian** [comment]
from #597:

* Base class version (in the NXDL file) can be removed.
* NXDL version number for base classes should be made optional in the XML Schema. (but this issue says remove it)

**Comment by prjemian** [comment]
A new branch, [version_attribute_616](https://github.com/nexusformat/definitions/tree/version_attribute_616), has been created for this work.
