### ISSUE TITLE
NXLog needs fixes to its definition

### ISSUE THREAD

**Issue by SkyToGround** [nexusformat/definitions#617]
There are (as far as I can tell) two issues with NXLog at the moment:
1. `cue_timestamp_zero` should be of type `NX_NUMBER` as the (optional) unit can not be `NX_TIME` if the type is an (ISO8601) string.
2. `time` should be of type `NX_NUMBER` as timestamping must allow for integer timestamps (see issue #593).

**Comment by prjemian** [comment]
Item 1 actually *must* have type=NX_CHAR if the type is an (ISO8601) string.  Is that what we want?

I agree with 2.
