### ISSUE TITLE
"Are there examples of NeXus data?" - asked at Nobugs 2018

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#629]
raise the prominence in the documentation of the exampledata repo

**Comment by toqduj** [comment]
All the data from the MAUS is NeXus...

**Comment by prjemian** [comment]
@toqduj - Please provide examples in the our exampledata repository: https://github.com/nexusformat/exampledata

Might be easiest for you to make a pull request

**Comment by prjemian** [comment]
2020 Code Camp states that housekeeping and curation of the example repo are timely.  Also, link to example data repo from the NeXus home page.  This work can be done in the code camp quite easily.  Longer term deposits (or references to external deposits) are a perennial matter.

**Comment by prjemian** [comment]
housekeeping in separate issue: https://github.com/nexusformat/exampledata/issues/3

**Comment by prjemian** [comment]
We'll continue to ask this question.  Good contributions towards this at this Code Camp.
