### ISSUE TITLE
"Are there examples of code that reads NeXus data?" - asked at Nobugs 2018

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#630]
Specifically, examples of code that reads specific *application definitions* and raise the prominence in the documentation

This will be a third subsection in examples/index.rst

**Comment by toqduj** [comment]
Very soon SasView 4.2.1 will have a functioning NXcanSAS reader. DAWN reads generic NeXus, and outputs NXcanSAS.

**Comment by prjemian** [comment]
@toqduj Can you provide URL to specific example in SASview?

**Comment by benajamin** [comment]
NXstxm can be read by:
* [Mantis](http://spectromicroscopy.com/), with the NeXus-specific python code [here](https://bitbucket.org/mlerotic/spectromicroscopy/src/default/)
* [aXis2000](http://unicorn.chemistry.mcmaster.ca/aXis2000.html), with the NeXus-specific IDL code [in the read_nexus.pro file](http://unicorn.chemistry.mcmaster.ca/axis/aXis2000.zip)

**Comment by benajamin** [comment]
SasView has python code to [read](https://github.com/SasView/sasview/blob/master/src/sas/sascalc/dataloader/readers/cansas_reader_HDF5.py) and [write](https://github.com/SasView/sasview/blob/master/src/sas/sascalc/file_converter/nxcansas_writer.py) NXcanSAS

**Comment by phyy-nx** [comment]
Dials code for reading NXmx: https://github.com/cctbx/dxtbx/blob/master/format/nexus.py
cctbx.xfel code for writing NXmx master files for JF16M at SwissFEL: https://github.com/cctbx/cctbx_project/blob/master/xfel/swissfel/jf16m_cxigeom2nexus.py

**Comment by benajamin** [comment]
[Dawn](https://dawnsci.org/) has java code to [read](https://github.com/DawnScience/scisoft-core/blob/master/uk.ac.diamond.scisoft.analysis/src/uk/ac/diamond/scisoft/analysis/io/NexusHDF5Loader.java) and [write](https://github.com/DawnScience/dawnsci/blob/master/org.eclipse.dawnsci.hdf5/src/org/eclipse/dawnsci/hdf5/nexus/NexusFileHDF5.java) HDF5 NeXus files (generic NeXus, not tied to specific application definitions).

**Comment by mkoennecke** [comment]
A F77 reading routine using NAPI for POLDI at SINQ PSI
[poldi.zip](https://github.com/nexusformat/definitions/files/4107360/poldi.zip) The archive includes the code and an example of a file which it reads

**Comment by mkoennecke** [comment]
FOCUS stuff: 
[focus.zip](https://github.com/nexusformat/definitions/files/4107386/focus.zip)
The archive contains:
- An example FOCUS file
- focusreport: A h5py program which skips through a list of files and prints statistics
- focusreport.tcl, same as above but in Tcl using the Swig generated binding to NAPI
- i80.f contains a F77 routine for reading FOCUS files into Ida. The routine is RRT_in_Foc.

**Comment by mkoennecke** [comment]
ZEBRA stuff in 
[zebra.zip](https://github.com/nexusformat/definitions/files/4107416/zebra.zip)
This contains:
- an example file
- zebra-to-ascii, a h5py script which dumps a zebra file to ASCII
- TRICSReader.* for reading ZEBRA files in C++ using C-NAPI calls

**Comment by mkoennecke** [comment]
[NXreader.zip](https://github.com/nexusformat/definitions/files/4107439/NXreader.zip)
This is some java code which reads NeXus files into ImageJ. It uses the Java-hdf interface to HDF5. It tries to do a good job locating the image dataset by NeXus conventions. But it uses the old style conventions.

**Comment by prjemian** [comment]
Once these are written into the user guide, this issue can be closed.

**Comment by prjemian** [comment]
[HDF5gateway](https://github.com/prjemian/hdf5gateway) makes it easy to read a HDF5 file into an [IgorPro](wavemetrics.com) folder, including group and dataset attributes, such as a NeXus data file, modify it, and then write it back out.

**Comment by prjemian** [comment]
Hmmm...  This list is similar to, yet different from, the listing in the [utilities](https://manual.nexusformat.org/utilities.html) section of the manual.  Enough that I will put all this content into the utilities page with a link from the [Examples](https://manual.nexusformat.org/examples/index.html)  page.
