### ISSUE TITLE
Mark and Armando to talk about how to solve #583

### ISSUE THREAD

**Issue by markbasham** [nexusformat/definitions#636]
https://github.com/nexusformat/definitions/issues/583

Possibly with something with Armando's suggestion of DATANAME_info as a link to the baseclass of the refrenced dataset.

**Comment by markbasham** [comment]
@vasole can you see this?

**Comment by vasole** [comment]
That's fine with me. At this point we are using something even more complex like having group named image containing data and info. image_data and image_data_info would make it even simpler.

I'm for it. DATANAME_info

**Comment by zjttoefs** [comment]
Having a ticket to address another ticket seems a bit redundant. I'll close this on an assign to @markbasham 
I have invited @vasole to the organisation, so I can assign to him as well. That's pending his acceptance of the invitation, though.
