### ISSUE TITLE
adjust NXdata to be consistent with #634 

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#640]
as in #639, suggest changing ``data_error`` to ``data_errors`` in NXdata to be consistent with #634

**Comment by zjttoefs** [comment]
I would say both are allowed now. Formally deprecating the old `data_error` would require a vote, I think.

**Comment by prjemian** [comment]
At CodeCamp2020-2, we decided this needs no further discussion.  Also see #639.  Mark existing field DEPRECATED.

**Comment by prjemian** [comment]
There is no work for this issue.
