### ISSUE TITLE
Documentation glitch?

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#648]
@vasole reports through the email listserv:

In http://download.nexusformat.org/sphinx/design.html one can read:

rgba, hsla and cmyk are (4 x n x m) arrays, where the 4 channels are the colour channels appropriately

I would appreciate that being written as (n x m x 4) because it is actually what people are going to write/use. I cannot imagine people writing the R component and nxm bytes later find the corresponding G component and so on. Usually one has the RGBARGBARGBA... and not RRRGGGBBBAAA...

**Comment by phyy-nx** [comment]
From Telco, @prjemian will fix (no branch needed)
