### ISSUE TITLE
data_origin and data_size documentation is unclear

### ISSUE THREAD

**Issue by phyy-nx** [nexusformat/definitions#650]
Hi all, there are two issues here:

1. NXdetector_module (base class) and NXmx (application definition that cites NXdetector_module) have different documentation for data_origin and data_size.  The former states these are 2 values for the origin and size, but the latter specifies 2 or 3 values
2. Assume the NXmx doc string is correct.  data_origin specifies the order the dimensions are listed (slow to fast), but data_size does not.  Presumably it also should be slow to fast.

**Comment by graeme-winter** [comment]
Further not helped by:

```
data[np, i, j, k]: (required) NX_NUMBER
```

For a dimension-2 detector, the rank of the data array will be 3. For a dimension-3 detector, the rank of the data array will be 4. This allows for the introduction of the frame number as the first index.

np, i, j, k suggests inverse of what is true i.e. index by frame, k, j, i in real life (or frame, j, i) for j, i slow then fast indices.

**Comment by phyy-nx** [comment]
At least the documentation here is explicit to clarify that part:

> The order of indices is i, j or i, j, k, i.e. slow to fast.
