### ISSUE TITLE
consider publishing docs in GitHub pages

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#663]
For more [timely](https://github.com/nexusformat/definitions/issues/658) updates to the documentation, consider publishing directly from travis-ci to [GitHub pages](https://help.github.com/en#github-pages-basics).  We are motivated by repeated permissions failures on our [jenkins server](https://build.nexusformat.org/job/definitions-master/381/) resulting in failure to post documentation revisions.  Other projects hosted on GH do this already.

**Comment by prjemian** [comment]
@danielballan : You've just been [updating](https://github.com/bluesky/ophyd/pull/721) how [bluesky](http://nsls-ii.github.io/bluesky/) posts its documentation to GH Pages.  Can you show us how or point us in the right direction?

**Comment by prjemian** [comment]
# (quick) Bibliography

- https://docs.travis-ci.com/user/deployment/pages/
- https://blog.ionelmc.ro/2015/07/11/publishing-to-github-pages-from-travis-ci/
- https://stackoverflow.com/questions/23277391/how-to-publish-to-github-pages-from-travis-ci

**Comment by prjemian** [comment]
First, branch this repo with name `gh-pages`

**Comment by prjemian** [comment]
Check the GitHub Pages settings [here](https://github.com/nexusformat/definitions/settings)

**Comment by prjemian** [comment]
Best to practice this on a different repo *first*.  Some basic advice:

* https://help.github.com/en/articles/creating-project-pages-using-the-command-line
* https://help.github.com/en/articles/user-organization-and-project-pages#project-pages-sites

**Comment by prjemian** [comment]
# Publish to GitHub Pages from local build

Following this [blog](https://www.bruttin.com/2017/12/22/github-ghpages-worktree.html) with additional [help](https://help.github.com/en/articles/creating-project-pages-using-the-command-line) and [more help](http://lea.verou.me/2011/10/easily-keep-gh-pages-in-sync-with-master/).  Also, have just built the documentation in the development directory (`~/Documents/eclipse/NeXus/definitions`) using `make local`.

**Basic Procedure**

1. `cd ~/Documents`
1. `mkdir gh-pages`  (separate directory from usual code development)
1. `git clone https://github.com/nexusformat/definitions`
1. `cd definitions`
1. `git checkout --orphan gh-pages`
1. `git rm -rf .`  (clear out all existing content, all but the `.git` directory)
1. `pushd ~/Documents/eclipse/NeXus/definitions/build/manual/build/html`
1. `tar cf - * .nojekyll | (cd ~/Documents/gh-pages/definitions && tar xf -)`
1. `popd`
1. `git add .`
1. `git commit -m publish`
1. `git push -u origin gh-pages`
1. view content: https://nexusformat.github.io/definitions

**Comment by prjemian** [comment]
Now that the gh-pages branch exists, describe how to post updated docs.  Then, automate this from travis-ci.

**Comment by prjemian** [comment]
## Update with new content

... working from the same directory as above ...

... assume that documentation has just been rebuilt ...

1. `git checkout gh-pages`  (ensure we are on the publishing branch -- do **not** do this to `master`!)
1. `git rm -rf .`
1. copy in the complete html content as above
1. `git add .`
1. `git commit -m publish`
1. `git push -u origin gh-pages`

**Comment by prjemian** [comment]
From the [Sphinx Google group](https://groups.google.com/d/msg/sphinx-users/3lMWsczWjuM/zibIc1mPCAAJ):
> Please check the repo:
> https://runawayhorse001.github.io/SphinxGithub/

**Comment by danielballan** [comment]
Somehow I missed being tagged on this back in May. I recommend the approach that I documented here: https://nsls-ii.github.io/scientific-python-cookiecutter/publishing-docs.html

I’ve tried a couple approaches over the years and this one has been the easiest to set up and keep working.

**Comment by prjemian** [comment]
Thanks, I'll look at it. LTS is important

**Comment by prjemian** [comment]
@FreddieAkeroyd emailed (to nexus-committee@nexusformat.org):

> There was discussion about some of our web links not being https at the [telco](https://www.nexusformat.org/Telco_20191107.html). Some links refer to  http://download.nexusformat.org/ which is an isis server and which currently does not have a valid certificate for download.nexusformat.org (so https will work, but the browser will moan at you). The user manual is built on the ISIS Jenkins server at the same location and then published to download.nexusformat.org   I can get a valid certificate for this address and we update links to https, or we could look at publishing the manual (and other stuff) elsewhere. We could push the built user manual html files to github pages maybe? I’m not sure what else on download.nexusformat.org is still relevant these days

**Comment by prjemian** [comment]
2020 Code Camp assesses this might too long to resolve but we can make technical comments on *how* to implement this.  We should also consider using `https` distribution.

**Comment by FreddieAkeroyd** [comment]
Above PR publishes docs to gh-pages using current Jenkins build system

**Comment by FreddieAkeroyd** [comment]
Now publishing to gh pages, redirect in place on old server, PR on main nexus wiki to update links there nexusformat/wiki#4
