### ISSUE TITLE
[DOC] C example uses old style NXdata

### ISSUE THREAD

**Issue by vasole** [nexusformat/definitions#665]
Nothing urgent. Just to comment that the C example about how to create a NeXus file with the original HDF5 API uses old style NXdata.

http://download.nexusformat.org/doc/html/examples/code_native.html

**Comment by prjemian** [comment]
Agreed.  Any volunteers to make the revision?

**Comment by prjemian** [comment]
@FreddieAkeroyd - Will this revision be ready for the 2020.1 milestone?  Otherwise, I'll move the issue to next milestone.

**Comment by FreddieAkeroyd** [comment]
Hi @prjemian that should now be fixed in above PR
