### ISSUE TITLE
Wrong long_name in verysimple example

### ISSUE THREAD

**Issue by schooft** [nexusformat/definitions#674]
The `long_name` attributes in the `verysimple.{txt,py,nx5}` example files are mixed up, e.g.,

```
      counts:int32[15] = [1193, 4474, 53220, '...', 1000]
        @units = counts
        @long_name = two_theta (degrees)
      two_theta:float64[15] = [18.9094, 18.9096, '...', 18.9122]
        @units = degrees
        @long_name = photodiode counts
```

**Comment by prjemian** [comment]
Thanks for that!  So simple, we all missed it until you noticed.

**Comment by prjemian** [comment]
@schooft : The bug was fixed but there will be a delay publishing it due to issue #676.

**Comment by prjemian** [comment]
Looks like it will be about a week before #676 is addressed.

**Comment by schooft** [comment]
Sorry, I forgot to mention that manual/source/img/verysimple.png is affected as well.
