### ISSUE TITLE
switch to new logo

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#692]
NeXus is [considering](https://www.nexusformat.org/Telco_20191107.html) a new logo.  The manual currently uses the old logo.  Once the new logo is decided, the manual should switch to that.

**Comment by prjemian** [comment]
And the GitHub avatar.

**Comment by prjemian** [comment]
We have no clear decision on a new logo.  Move this issue to next milestone.

**Comment by prjemian** [comment]
posted message to NeXus about dropbox collection:

> I've created a shared folder on dropbox.com to gather the various logo 
suggestions.  Some logo suggestions have already been uploaded.  The 
folder is shared by invitation only (through dropbox.com) so that the 
suggestions are not discovered  by web indexers.
> 
> If you want access editable or viewable-only to this folder, please send 
me your email address and which type of access you prefer.  I'll send 
you an invitation from dropbox with a link to the folder.  Editable 
access would be suited to those who wish to add additional logo designs 
or reorganize the collection.

**Comment by prjemian** [comment]
We want someone to gather all proposed logos to the [Dropbox folder](https://www.dropbox.com/sh/e9hjha6mtum79a5/AAAPp4nh43pdSQFyggWlOR-7a?dl=0).  Notify @prjemian to be granted write permission to the folder.

**Comment by benajamin** [comment]
This topic is too controversial to do anything about without a well-attended in-person meeting.

**Comment by prjemian** [comment]
new logo progress has langushed

**Comment by prjemian** [comment]
Either re-open this issue or create a new one should this topic arise again.
