### ISSUE TITLE
NXDL release 2020.1

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#693]
Follow the [documented release procedure](https://github.com/nexusformat/definitions/wiki/Release-Procedure).  Someone other than @prjemian should do this to test that procedure has been fully documented.

These steps:

* [x] rename the [NXDL 2019.10](https://github.com/nexusformat/definitions/milestone/8) milestone to *NXDL 2020.1*
* [x] identify and resolve existing issues which can be completed before release during the code camp
* [x] reassign unresolved issues to [next milestone](https://github.com/nexusformat/definitions/milestone/9)
* [x] follow [release procedure](https://github.com/nexusformat/definitions/wiki/Release-Procedure)
* [x] apply *lessons learned* to release procedure

Note: Any new issues will be assigned to next milestone *after* this code camp unless they are of immediate nature.

**Comment by prjemian** [comment]
Good first steps:

* [ ] rename the [NXDL 2019.10](https://github.com/nexusformat/definitions/milestone/8) milestone to *NXDL 2020.01*
* [ ] identify and resolve existing issues which can be completed before release during the code camp
* [ ] reassign unresolved issues to [next milestone](https://github.com/nexusformat/definitions/milestone/9)
* [ ] follow [release procedure](https://github.com/nexusformat/definitions/wiki/Release-Procedure)
* [ ] apply *lessons learned* to release procedure

Note: Any new issues will be assigned to next milestone *after* this code camp unless they are of immediate nature.

**Comment by prjemian** [comment]
@PeterC-DLS 

There's a checklist at the top of this issue.  Perhaps that should become part of the release procedures on the wiki?  We're at step 2 on that checklist.

I'm looking at the work queue for the [milestone](https://github.com/nexusformat/definitions/milestone/8) and expecting that most remaining PRs will be complete by Thursday.  Now that the release notes scripting is repaired (#735) but work remains to be merged, it's a good time to work the release process again with another R tag: *v2020.1rc2*.

**Comment by prjemian** [comment]
Each of the remaining PRs is waiting on one or more reviews.  I sent messages to each reviewer yesterday with a request to review by COB Thursday.  In one of them, I stated I want to release on Friday.  Any unreviewed items will move to next milestone.

**Comment by PeterC-DLS** [comment]
Ok, I have completed the process for rc2. Please check all it okay.

**Comment by prjemian** [comment]
One addition is to link to the release notes from the tag comment.  See https://github.com/nexusformat/definitions/releases/tag/v2018.5 for an example.

Release notes look good.

Updating the [Change History](https://github.com/nexusformat/definitions/blob/master/CHANGES.rst) needs to be added to the [Release Procedure](https://github.com/nexusformat/definitions/wiki/Release-Procedure).  The existing page refers to *2019.10* release that should be changed into *v2020.1*.  The contents are hand-selected highlights from the release notes (since important items might be overlooked in the complete release notes).

Fantastic! On Friday, you can do the final release of *v2020.1* after completing the checklist above.

### Lessons learned

* need linux OS for release process
* need latexmf installed with [certain additional fonts](https://github.com/nexusformat/definitions/wiki/Release-Procedure)

  > On Ubuntu xenial, the following packages need to be installed for successful PDF builds:
  > texlive-latex-recommended
  > texlive-fonts-recommended
  > texlive-latex-extra
  > latexmk (this is a Sphinx requirement on GNU/Linux and MacOS X for functioning of make latexpdf)

* can build complete (HTML& PDF) manual with `make all` in root directory

Anything else?

**Comment by prjemian** [comment]
One more lesson learned

Preparatory step

Get a GitHub personal access token, read only for access to repos,
milestones, pull requests, issues, ...

This is specific to the user for use on one workstation

**Comment by PeterC-DLS** [comment]
On Fedora 31, need to install:
* make hdf5-devel python-matplotlib python-lxml python3-sphinx-latex latexmk
* h5py=2.10.0
* pyRestTable
* pygithub
* sphinx==2.3.1

**Comment by prjemian** [comment]
@PeterC-DLS we are ready now for release *v2020.1*

**Comment by prjemian** [comment]
I just checked off items 2 & 3 in the check list above.

**Comment by PeterC-DLS** [comment]
Ok, I will proceed with release.

**Comment by PeterC-DLS** [comment]
All done so please check. I will be off-line so I will leave the mailing list announcement to you.

**Comment by prjemian** [comment]
Thanks.  Changed the release name to "v2020.1"
