### ISSUE TITLE
NXBeam symbols are redundant

### ISSUE THREAD

**Issue by phyy-nx** [nexusformat/definitions#708]
The symbol table in NXBeam that is going to be added by #706 lists `i` and `j` as possible symbols, but they appear to mean the same thing in the rest of the documentation.  Should `j` be removed and we only have `i`?

**Comment by prjemian** [comment]
not affected by #819

**Comment by prjemian** [comment]
@phyy-nx #706 was closed without merge, making this issue obsolete.  If you agree, please close this issue, adding the `wontfix` label.

**Comment by phyy-nx** [comment]
Still an issue in NXbeam.  No symbol table and `i` and `j` may mean the same thing (maybe not)?  Possible resolution is to sync NXmx's NXbeam to NXbeam, as it adds a lot of useful stuff and doc.

**Comment by phyy-nx** [comment]
I could use some help here.  I don't understand what [2,j] means for extent, incident_polarization, etc., and how it's related to [i] in incident_wavelength.  See [NXBeam](https://manual.nexusformat.org/classes/base_classes/NXbeam.html).

**Comment by PeterC-DLS** [comment]
Best to ask for clarification on the list. Also the 2-dimensions seem to be undefined: for divergence, is it horizontal and vertical; for polarization, two (real) components will not describe any phase relationship, i.e. for elliptically polarized beams.

**Comment by benajamin** [comment]
I think whoever wrote this clearly intended for i and j to have the same meaning and the size 2 dimension was clearly meant to be x and y directions. I also agree with Peter that 2 parameters are not sufficient to fully describe polarisation - a normalised [Stokes vector](https://en.wikipedia.org/wiki/Stokes_parameters) would be recommended.

**Comment by PeterC-DLS** [comment]
Also, need to reconcile with and update to https://manual.nexusformat.org/classes/applications/NXmx.html

**Comment by phyy-nx** [comment]
For my reference, here are the fields of interest that are all [2, j]:

- extent (length)
- incident_beam_divergence (angle)
- incident_polarization (any)
- final_polarization (any)
- final_beam_divergence (angle)

**Comment by phyy-nx** [comment]
Some fact finding/archeology in preparation of a proposal.

Divergence makes sense to me and seems to be not too controversial.

Extent in NXBeam probably does mean 2D beam size in units of length, but this seems to overlap with `profile` in NXmx, which is of type char and is an enumeration of Gaussian, Airy function, top-hat or rectangular.  Therefore, if extent is provided it seems only applicable to a rectangular profile.  Notably, NXmx doesn't cite NBbeam's extent field.

Polarization though is more complex:

- Polarization was changed from dimension `[3,:]` to `[2, j]` as part of a big revision to the dimensions system in 2009 by @prjemian. See https://github.com/nexusformat/definitions/commit/f86bdcb4591707db84346207dbbc49297c75c8a0.
- In 2013, @zjttoefs [asked](https://lists.nexusformat.org/pipermail/nexus/2013/000543.html) on the NeXus mailing list about the meaning of `[2, j]`. He proposed extending the 2 to 4 to allow using Stokes notation, and transposing the dimensionality to `[j, 4]`.  @yayahjb [responded](https://lists.nexusformat.org/pipermail/nexus/2013/000544.html) with detail about how this was implemented in CBFs, including what was possibly meant by the 2.
- Later that year, in the CBF to NeXus correspondence doc, both @yayahjb and @zjttoefs, [proposed](https://lists.nexusformat.org/pipermail/nexus/2013/000544.html) the same set of changes to NXbeam, additionally renaming j to i.
- This idea was present in the very first commit of NXmx from @zjttoefs in 2014 (https://github.com/nexusformat/definitions/commit/71ba99e9de2df0bf7f3361a15c429bda1a9b2f0c), which includes incident_polari**s**ation_stokes (note the 's' instead of the 'z'), with dimensionality `[np, 4]`.  NXmx does not cite NXbeam's incident_polarization or final_polarization.
- In 2015, @jmp1985 implemented serializing/deserializing NXreflections files in DIALS ([current code](https://github.com/dials/dials/blob/master/util/nexus/nx_mx.py#L208)), but used the name incident_polari**z**ation_stokes (note the 'z' instead of the 's').  The [current](https://github.com/nexusformat/exampledata/blob/master/DLS/reflections/hdf5/thaumatin_integrated.nxs) NXreflections example, which I generated using [DIALS](https://github.com/nexusformat/exampledata/blob/master/DLS/reflections/hdf5/DETAILS.rst), includes this field, spelled with the 'z'.

Note also that @mkoennecke has also [requested](https://lists.nexusformat.org/pipermail/nexus/2013/000545.html) expansion of the NXbeam polarization features:

> - the polarisation_efficiency = (spinup - spindown)/(spinup+spindown)
> - the transmission of the filter
> - the relaxation_time, for He3 polarisers. The polarisation of those 
degrades with time.

Set of proposals incoming to resolve the issues raised here.

**Comment by phyy-nx** [comment]
Proposal:

- NXBeam: rename `i` to `np` to be consistent with NXmx
- NXBeam: re-dimension extent, incident_beam_divergence, and final_beam_divergence to `[np, 2]`.  There are zero instances of these fields in nexusformat/exampledata, but first survey the community by email to see if these fields are used.
- NXBeam: deprecate incident_polarization and final_polarization.  There are zero instances of these fields in nexusformat/exampledata, but first survey the community by email to see if these fields are used.
- NXmx: deprecate incident_polarisation_stokes.
- NXmx: add incident_polarization_stokes `[np, 4]`
- NXbeam: add incident_polarization_stokes `[np, 4]` and final_polarization_stokes `[np, 4]`
- Regenerate ./autogenerated_examples/nxdl/applications/NXmx.hdf5, updating to incident_polarization_stokes

I'd suggest to @mkoennecke if he still is interested in the features he mentioned above to prepare a separate issue/PR for them.  Maybe they've been added to a different application definition?

Feedback?  Thanks!

**Comment by phyy-nx** [comment]
For reference, here's the command I used to search for instances of fields in nexusformat/exampledata:

```
for ext in hdf hdf5 h5 nexus nxs nx5; do for i in `find . -name "*.${ext}"`; do echo $i; h5ls -r $i | grep extent; done; done 2> /dev/null
```

**Comment by yayahjb** [comment]
The Stokes vector field is already in NXmx as an addition to NXbeam.  I was
planning to bring it into the NXbeam class as part of the
NXdetector clean-up.  The field is incident_polarisation_stokes which holds
the usual 4
Stokes components.
