### ISSUE TITLE
Consider changing _var to _errors in NXreflections

### ISSUE THREAD

**Issue by phyy-nx** [nexusformat/definitions#724]
Based on 2018 NIAC, we should be using _errors to track error in a measurement (See https://www.nexusformat.org/NIAC2018Minutes.html#uncertainties-continuation)

However, NXreflections uses _var to describe variances on the standard deviation.  Should we change to using _error instead?  Would we then store standard deviations instead of variances?  How would we document this?  Would we deprecate the affected fields, remove them, or leave them but note they are not recommended?

This would affect these fields:
- observed_frame_var
- observed_px_x_var
- observed_px_y_var
- observed_phi_var
- observed_x_var
- observed_y_var
- int_prf_var
- int_sum_var

**Comment by vasole** [comment]
I guess you meant ``_errors`` and not ``_error``

**Comment by phyy-nx** [comment]
Proposal from code camp is to ADD _errors but retain _var as optional fields.
