### ISSUE TITLE
create_release_notes.py should use SHA credentials

### ISSUE THREAD

**Issue by PeterC-DLS** [nexusformat/definitions#729]
Remove need to have separate file to store credentials

**Comment by prjemian** [comment]
As part of #728, will switch credentialing to use GitHub's Personal Access Token [credentialing](https://github.com/settings/tokens).  Use of PAT is preferred over SSH key due to the GitHub API Rate Limit.  SSH access is for normal push/pull usage, PAT is used with the GH API.
