### ISSUE TITLE
js warning - http "insecure endpoint"

### ISSUE THREAD

**Issue by rerpha** [nexusformat/definitions#753]
JavaScript is giving me this warning when accessing any of the NX base classes:

```
js: Mixed Content: The page at 'https://manual.nexusformat.org/classes/base_classes/NXaperture.html' was loaded over a secure connection, but contains a form that targets an insecure endpoint 'http://www.google.com/search'. This endpoint should be made available over a secure connection.
```

I think it is to do with the http request https://github.com/nexusformat/definitions/blob/c3d342f39bf05dcf59a6bbd7e88b0838bf11651f/manual/source/_templates/google_search.html#L14

**Comment by prjemian** [comment]
Thanks!
