### ISSUE TITLE
How to add extra attributes and avoid conflicts with NeXus in the future?

### ISSUE THREAD

**Issue by t20100** [nexusformat/definitions#757]
If I want to define additional attributes than the one defined by NeXus that are specific to an application, how can I make sure that those attribute names will not conflict with NeXus in the future when new attributes are added to the specification?

Could there be an attribute prefix, e.g., `_`, `addon_`, `extra_`, ... that NeXus guarantees it will never use?
Else I can use the application name as a prefix and assume that NeXus will not use that... which is most likely the case but not guaranteed.

**Comment by vasole** [comment]
In order to avoid conflicts with other applications implementing extras, I think you will need to use the application name prefix.

**Comment by prjemian** [comment]
*proposed action to resolve this issue*:  

Add this to the {FAQ](https://manual.nexusformat.org/faq.html) section of the manual.

**Comment by prjemian** [comment]
NeXus will develop and publish a list of reserved prefixes and avoid standardizing any attribute that starts with a reserved prefix.  Post a GitHub issue to begin the process of reserving a prefix.

**Comment by prjemian** [comment]
We should ask the NIAC for permission that the teleconference can maintain this list.

Also suggest that prefixes be easily recognizable, such as capitalized with underscore after, such `PRJ_`.

**Comment by prjemian** [comment]
Issues have been created for all matters presented.  Closing here.  Thanks for the question and contributions!
