### ISSUE TITLE
No documentation of DATASETNAME_weights

### ISSUE THREAD

**Issue by rayosborn** [nexusformat/definitions#763]
At the [NIAC 2018 meeting](https://www.nexusformat.org/NIAC2018Minutes.html), there was an agreement to provide a mechanism for defining weights that should be automatically applied to associated data before, *e.g.*, plotting. Here is the relevant section in the 2018 minutes.
```
It occurs that there is a need to divide a dataset with another one to normalize it.

Ray’s proposal: DATASETNAME_weights anywhere in a NeXus file. If it exists and has the 
same shape as the dataset, you are supposed to divide the data by the weights.
```
This has not been added to the documentation and should be included in the list of reserved suffixes.

**Comment by prjemian** [comment]
Also add to Index.
