### ISSUE TITLE
NXcanSAS "radiation" duplicates NXsource "type"

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#765]
The [NXcanSAS](https://manual.nexusformat.org/classes/applications/NXcanSAS.html) definition requires a field called [`radiation`](https://manual.nexusformat.org/classes/applications/NXcanSAS.html?highlight=radiation#index-74) in its use of the (optional) NXsource group.  No such field exists in the [NXsource](https://manual.nexusformat.org/classes/base_classes/NXsource.html) definition, although there is a field [`type`](https://manual.nexusformat.org/classes/base_classes/NXsource.html?type#index-5) which provides the same information.

Since there exist data files written to the NXcanSAS v1.0 specification, it may be too late to change the NXcanSAS definition.  At least, it should be documented that for NXcanSAS, `radiation` should be linked to `type` in the NXsource group.

Such as this python code

```python
    ds = nxsource.create_dataset('type', data="Synchrotron X-ray Source")
    ds.attrs["target"] = ds.name      # for NeXus link

    # NXcanSAS _requires_ a dataset called "radiation" in its NXsource
    # that takes the same values as "type _or_ "probe" in NXsource.
    # Here, we link radiation -> type
    nxsource["radiation"] = nxsource["type"]  # NeXus link to canSAS synonym
```

resulting in this tree structure:

```
        radiation --> /entry/instrument/source/type
        type:NX_CHAR = Synchrotron X-ray Source
          @target = /entry/instrument/source/type
```

**Comment by prjemian** [comment]
Thanks to @vasole and Jérôme Kieffer (ESRF) for identifying this!

**Comment by prjemian** [comment]
@butlerpd, @ajj, @timsnow, @zjttoefs, @smk78, @adrianrennie, @jilavsky: Any of you canSAS experts have a comment?

**Comment by prjemian** [comment]
@pbeaucage: you, too, might be interested

**Comment by prjemian** [comment]
@krzywon: you are involved with NXcanSAS and [SASview](https://github.com/SasView/sasview), that uses it.

**Comment by adrianrennie** [comment]
This does look to me as though NXcanSAS has an unfortunate definition in that descriptors for "radiation" have been appended to source "type".  Although I have some data files, I do not have an overview as to what different facilities/instruments write.  We do need comments from people that use this to find a a good way out of the difficulty.

**Comment by vasole** [comment]
To me the easy solution is that whoever is taking care to add an attribute SASclass besides the NXclass attribute can also take care to add a field radiation besides a field named type.

Therefore just documenting the inconsistency should be enough.

**Comment by krzywon** [comment]
I think the inconsistency is more nefarious then originally suggested. The NXcanSAS [radiation](https://manual.nexusformat.org/classes/applications/NXcanSAS.html?highlight=radiation#index-74) field seems to combine the allowable entries for both NXsource fields [type](https://manual.nexusformat.org/classes/base_classes/NXsource.html?type#index-5) and [probe](https://manual.nexusformat.org/classes/base_classes/NXsource.html?probe#index-6). I'm not sure a link will work in this situation.

One possible solution is to require at least one radiation field, but allow multiple instances to capture the type and probe, if desired. Liberal readers shouldn't have an issue with extra entries and facilities already creating data sets will still produce valid data. The worst case scenario I see with this suggestion: strict readers that don't accommodate this change might break and liberal ones could throw away some information.

**Comment by smk78** [comment]
Sorry, am coming late to the party on this.

So we have a large body of Users now with both 1D and 2D reduced data in NXcanSAS; indeed, it is the only format our Mantid interface supports for the 2D (so we can load it in SasView!).

And I can confirm that we **do** write to the _radiation_ field.

**Comment by benajamin** [comment]
If the _radiation_ field is not really needed, I would suggest it be marked as **deprecated** (to stop it being written in future) in addition to documentation (to make sure existing files are properly read).

**Comment by prjemian** [comment]
This paragraph to be added to the NXcanSAS documentation for the [*radiation*](https://manual.nexusformat.org/classes/applications/NXcanSAS.html#index-74) field:

> This field contains a value from either the [*NXsource/probe*](https://manual.nexusformat.org/classes/base_classes/NXsource.html#index-6) or [*NXsource/type*](https://manual.nexusformat.org/classes/base_classes/NXsource.html#index-5) field.  Thus, it is redundant with existing NeXus structure.

As discussed in today's [NeXus teleconference](https://www.nexusformat.org/Telco_20200424.html), it is suggested to mark this field as **deprecated** (see [above](https://github.com/nexusformat/definitions/issues/765#issuecomment-616382982)).  Existing data files with the *radiation* field would not be changed but data files written after this revision should use the `probe` and/or `type` fields instead.  The information will still be provided but data file readers would need to consider this variation.

@butlerpd, @ajj, @timsnow, @zjttoefs, @smk78, @adrianrennie, @jilavsky, @krzywon, @pbeaucage, @vasole, Jérôme Kieffer : Do you agree with this revision?  Anyone else need to be notified?

**Comment by vasole** [comment]
(@kif) No problem from our side.

**Comment by butlerpd** [comment]
Brian Pauw was also involved in the early work and has an implementation for his software. Perhaps he should be notified as well?

**Comment by prjemian** [comment]
@toqduj Do you agree with this revision? Anyone else need to be notified?

**Comment by smk78** [comment]
Seems ok to me.

Will this constitute a formal revision of the NXcanSAS standard to, what would it be 1.1?, or an under-the-hood change? In other words, when we change our writers, do we need to change the version number at the same time?

**Comment by prjemian** [comment]
I believe it should be a formal revision of the NXcanSAS standard. 
Makes it easier to reference.

Steve K wrote:

**Comment by krzywon** [comment]
Seems fine to me.

**Comment by smk78** [comment]
So what's the target date for adoption?

**Comment by prjemian** [comment]
Is one week too soon?

**Comment by smk78** [comment]
Prob ok.

I have a meeting with some Mantid guys on Mon. I'll bring this up there (as ultimately we will be asking changes to the NXcanSAS writer/reader in it). We've just missed one release but should be far enough ahead of the curve for the next. 

What's the verdict on the new version number; will it be 1.1?

**Comment by prjemian** [comment]
That's right.  NXDL file shows current is 1.0:  https://github.com/nexusformat/definitions/blob/0eeaea50c3818749093a9abc065118ce23427e43/applications/NXcanSAS.nxdl.xml#L152-L163

Previous release [NXcanSAS-1.0](https://github.com/nexusformat/definitions/releases/tag/NXcanSAS-1.0), this is a minor change, does not introduce a breaking change, thus bump the minor version number.  NeXus does not use a 3-level version scheme (such as [semantic versioning](https://semver.org)) so we'll just increment the last number in the version.

**Comment by smk78** [comment]
@krzywon : what will the SasView h5 reader do at the moment if it sees a file with _probe_ or _type_ instead of _radiation_?

**Comment by krzywon** [comment]
@smk78 : The reader currently dumps any 'unrecognized' values into a dictionary of {entryName: value}. That said, I'm already working on accommodating this change and a PR should be ready next week.

**Comment by prjemian** [comment]
Note: previous NXcanSAS-1.0 tagged with commit e888dac

Not making a GitHub release, just a tag with name [*NXcanSAS-1.1*](https://github.com/nexusformat/definitions/releases/tag/NXcanSAS-1.1) for commit 69b7168 .
