### ISSUE TITLE
reserved prefixes for names

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#769]
NeXus will develop and publish a list of reserved prefixes and avoid standardizing any name (specifically, we are thinking of attribute names) that starts with a reserved prefix.  To reserve a prefix, post a GitHub issue to the definitions repository.

Should this be generalized to prefix the names of groups, fields, and links, as well?

_Originally posted by @prjemian in https://github.com/nexusformat/definitions/issues/757#issuecomment-619031547_

**Comment by prjemian** [comment]
As [noted](https://github.com/nexusformat/definitions/issues/757#issuecomment-619033258), 

> Also suggest that prefixes be easily recognizable, such as capitalized with underscore after, such as PRJ_.

**Comment by prjemian** [comment]
The manual now has a subsection for reserved suffixes, under the section on [Naming Conventions](https://manual.nexusformat.org/datarules.html).  This content is similar.  A brief comment should accompany any prefix to describe its intended use.

**Comment by prjemian** [comment]
Planning to use a table, alphabetized by prefix, such as:

prefix | use | meaning
---- | ---- | ----
`NX` | NXDL class | For the class names used with NeXus groups
`NX_` | attributes | reserved for use by NeXus
`SAS_` | attributes | reserved for use by canSAS (?URL?)
`SILX_` | attributes | reserved for use by silx (?URL?)

Note that unless stated explicitly in the *meaning*, the reservation applies to any upper or lower case form of the prefix.

**Comment by prjemian** [comment]
As stated in https://github.com/nexusformat/definitions/issues/757#issuecomment-591001600, reference this subsection in the [FAQ](https://manual.nexusformat.org/faq.html).

**Comment by prjemian** [comment]
Also, search through the manual sections for mentions of reserved prefixes (such as `NX` reserved for NXDL class names) and create references to this new subsection where appropriate.

**Comment by prjemian** [comment]
While perusing ancient NeXus history, interesting to note the [idea of naming prefixes](https://github.com/nexusformat/wiki/blob/master/content/How_to_avoid_name_clashes_during_future_extensions_of_the_Nexus_standard.md#prefixes-for-user-defined-names) was discussed previously.

**Comment by prjemian** [comment]
Note that in NXentry, the attribute `IDF_Version` is *ISIS Muon IDF_Version*.  Add `IDF_` to the list.

**Comment by benajamin** [comment]
Proposal is to reserve the following prefixes:
prefix | use | meaning
---- | ---- | ----
`NX` | NXDL class | For the class names used with NeXus groups
`NX_` | attributes | reserved for use by NeXus
`SAS_` | attributes | reserved for use by canSAS (?URL?)
`SILX_` | attributes | reserved for use by silx (www.silx.org)


-    thumbs up to accept
-    thumbs down to reject
-    any other emoji to abstain

**Comment by prjemian** [comment]
* Check EPICS area detector, that it uses the `AD` prefix (@MarkRivers)
* Check `PDBX_` (protein data bank) URL: https://www.rcsb.org/

**Comment by prjemian** [comment]
Restrict `AD` to upper case (since `address` exists).

**Comment by prjemian** [comment]
Additional metadata in EPICS area detector matches the prefix `NDAttr`, for example:

```
        @NDAttrName = Sample_XTranslation
        @NDAttrDescription = Sample XTranslation [mm]
        @NDAttrSourceType = NDAttrSourceEPICSPV
        @NDAttrSource = 9idcSample:XTranslation
        @NDAttrName = UserName
        @NDAttrDescription = user name listed as GUP PI
        @NDAttrSourceType = NDAttrSourceEPICSPV
        @NDAttrSource = 9idcLAX:UserName
        @NDAttrName = GUPNumber
        @NDAttrDescription = GUP proposal number
        @NDAttrSourceType = NDAttrSourceEPICSPV
        @NDAttrSource = 9idcLAX:GUPNumber
```

**Comment by prjemian** [comment]
At NIAC2020:

> Prefixes should follow a naming scheme of uppercase letters followed by an underscore, but exceptions will be made for cases already in wide use.

**Comment by stuartcampbell** [comment]
Just linking https://github.com/nexusformat/NIAC/issues/80 as that discusses and adds a BLUESKY_ prefix
