### ISSUE TITLE
add NeXus entry

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#772]
Add a NeXus entry to http://fileformats.archiveteam.org/wiki/Scientific_Data_formats

**Comment by rayosborn** [comment]
It's already listed in the [Physics Formats](http://fileformats.archiveteam.org/wiki/Physics_data), which for some reason is on a subpage with only four entries. However, there is no link and NeXus should not be classified as Physics anyway. Perhaps, if you edit the page, you should try to create another section on Neutron and X-ray Scattering. We could be magnanimous and add links to CBF, canSAS and even DataExchange.

**Comment by prjemian** [comment]
@rayosborn : Thanks for that.  The page it links to is empty:

> There is currently no text in this page. You can search for this page title in other pages, or search the related logs. 

So, even that needs some work.  

I can edit for canSAS but I'll let other projects speak for themselves.

**Comment by prjemian** [comment]
You'd think it would be easy to create an account to make this edit but the security question they ask (`The Archive Team IRC channel is on what IRC network?`) will not accept the [answer](https://www.archiveteam.org/index.php?title=IRC_Channel).

**Comment by prjemian** [comment]
BTW: CIF is listed under [Chemical](http://fileformats.archiveteam.org/wiki/Scientific_Data_formats#Chemical)

**Comment by prjemian** [comment]
[Done](http://fileformats.archiveteam.org/wiki/NeXus)
