### ISSUE TITLE
contributed vs application definitions

### ISSUE THREAD

**Issue by RealPolitiX** [nexusformat/definitions#775]
I have a few questions on contributed and application definitions
1. What's the procedure to submit a new contributed definition for a new type of experiment? Say if we want to write an xml file, is there code available to parser it to make sure the syntax is correct?
2. Will contributed definitions ever become application definitions?
3. If people want to amend or extend existing application or contributed definitions, whom should they communicate with?
4. Does NIAC release example files for each application or contributed definition?

**Comment by prjemian** [comment]
1.b. `xmllint --noout --schema nxdl.xsd base_classes/NXentry.nxdl.xml` will validate NXentry when current working directory is root of the definitions tree

There are other ways but this is most straightforward.

**Comment by prjemian** [comment]
1.a. fork the definitions repository, add the new files, make a pull request - then the questions start :)

> contributed definitions include propositions from the community for NeXus base classes or application definitions

**Comment by prjemian** [comment]
2. after at least a year of incubation, if at all

>  Consider the contributed definitions as either in incubation or a special case not for general use.

-- https://manual.nexusformat.org/classes/index.html

**Comment by prjemian** [comment]
Ratification (acceptance) of a new base class or application definition requires a vote of the full NIAC.

-- https://manual.nexusformat.org/niac.html

**Comment by prjemian** [comment]
3. make a new issue: https://github.com/nexusformat/definitions/issues/new and state your ideas

**Comment by prjemian** [comment]
4. NeXus has an example data file repository that is edited occasionally.  See https://github.com/nexusformat/exampledata for what is available.  No one yet has taken the mission to ensure there is at least one example for every base class or application.  That is a laudable goal.  (To my knowledge, I don't even know what fraction of the base classes are used in the example data.)

**Comment by prjemian** [comment]
Does that help answer your questions?

**Comment by prjemian** [comment]
Here is an example of a request for change in the NXsas definition: https://github.com/nexusformat/definitions/issues/523

**Comment by prjemian** [comment]
NXDL validation example: https://github.com/nexusformat/definitions/blob/2dc081ee4265eebf80a953080a2ed275c1799a21/utils/test_nxdl.py#L13-L14

**Comment by prjemian** [comment]
Looks like `definitions/utils/test_nxdl.py` will validate ALL NXDL files when called as it is from https://github.com/nexusformat/definitions/blob/e11f332e471aae0f120f8a5ad74b16b2ff595ee3/Makefile#L65 (that's part of our continuous integration process)

**Comment by RealPolitiX** [comment]
Thanks a lot @prjemian, these are very timely and illustrative information.

**Comment by prjemian** [comment]
Seems that we've answered your questions.  Closing now.
