### ISSUE TITLE
NXmx: offset attributes should be NX_NUMBER

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#782]
While looking through the definitions for the use cases of the `offset` attribute, discovered that various uses of `@offset` in [NXmx](https://manual.nexusformat.org/classes/applications/NXmx.html#index-44) default to `NX_CHAR`.  This appears inconsistent with the documentation.  Looks as if it should be a number and not text.

Should all instances of the `offset` attribute in MXmx be `NX_NUMBER`?
Same for the `vector` attributes?

**Comment by PeterC-DLS** [comment]
Those are transformation field attributes and should be numbers as defined by [here](https://manual.nexusformat.org/design.html#coordinate-transformation-field-and-attributes)

**Comment by yayahjb** [comment]
I agree. -- Herbert

**Comment by prjemian** [comment]
@yayahjb - Can you add this to PR #793?

**Comment by prjemian** [comment]
Fixed in #793
