### ISSUE TITLE
NXstxm: missing rank value in dimensions specification

### ISSUE THREAD

**Issue by RussBerg** [nexusformat/definitions#787]
The dimensions spec provides a dim section without specifying first **rank**.
`<dimensions> ` should be `<dimensions rank="1">` in the following:
```
    <dimensions>
        <doc> Detector data should be presented with the first dimension corresponding to the
                    scan point and subsequent dimensions corresponding to the output of the detector.
                    Detectors that provide more than one value per scan point should have
                    a data array of rank 1+d, where d is the dimensions of the array provided per
                    scan point. For example, an area detector should have an NXdetector data array
                    of 3 dimensions, with the first being the set of scan points and the latter 
                    two being the x- and y- extent of the detector 
        </doc>
        <dim index="1" value="NumP" />
    </dimensions>
```

**Comment by benajamin** [comment]
I'm not sure your proposed fix is correct. As the doc section states, the array should have a rank of at least 1. the rank will be 1 if a point detector is being used (1 value per scan point), but it would be rank 3 if a 2D detector is being recorded. I think we will need to define a new symbol in order to specify this correctly.

`<symbol name="RankDetector"><doc>rank of data array provided by the detector for a single measurement</doc></symbol>`
and then
`<dimensions rank="1+RankDetector">`

(Assuming that arithmatic is allowed in the tag parameter values.)

**Comment by prjemian** [comment]
The nxdl.xsd states:

						The ``value`` attribute is used by NXDL and also by
						the NeXus data file validation tools to associate and coordinate the
						same array length across multiple fields in a group.

So no hard & fast rule about the content except to check with validation tools to see if this matches what they expect.  How does the NXDL use this value?

**Comment by RussBerg** [comment]
it does look like the documentation says that expressions are supported:

from **_1.3.3.4. Step 3: Describe this map in a NXDL file_**
  _The meaning of the name attribute is intuitive, the type can be looked up in the relevant base class definition. A field definition can optionally contain a doc element which contains a description of the data item. The dimensions entry specifies the dimensions of the data set. The size attribute in the dimensions tag sets the rank of the data, in this example: rank="1". In the dimensions group there must be rank dim fields. Each dim tag holds two attributes: index determines to which dimension this tag belongs, the 1 means the first dimension. The value attribute then describes the size of the dimension. These can be plain integers, variables, such as in the example ndet **or even expressions like tof+1.**_

So it would appear that Ben's  solution works.

**Comment by benajamin** [comment]
Yes, explaining the situation in a doc string is all we can do because the XML doesn't give us the power to describe an unknown number of dimensions.

**Comment by RussBerg** [comment]
so a possible doc string adjustment could be the NOTE below:

                  <dimensions rank="1+rankDetector">
                    <doc>Detector data should be presented with the first dimension corresponding to the
                    scan point and subsequent dimensions corresponding to the output of the detector.
                    Detectors that provide more than one value per scan point should have
                    a data array of rank 1+d, where d is the dimensions of the array provided per
                    scan point. For example, an area detector should have an NXdetector data array
                    of 3 dimensions, with the first being the set of scan points and the latter 
                    two being the x- and y- extent of the detector.
                        NOTE: For each dimension > 1 there must exist a dim section such as:
                            <dim index="(dimension index value)" value="(size of dim)" />
                    </doc>
                    <dim index="1" value="nP" />
                  </dimensions>
