### ISSUE TITLE
Missing @creator_version in NXroot

### ISSUE THREAD

**Issue by vasole** [nexusformat/definitions#789]
Following the approach already in use in NXroot, we would like to be able to add the field ``@creator_version (optional)`` to complement the already existing ``@creator (optional)``.

That would allow a more universal separation of creator and creator_version because I guess each facility is already writing the version as part of the creator but without any consensus.

If this proposal is not accepted, please consider it than as a heads up of somebody already using that attribute.

**Comment by prjemian** [comment]
Merge is pending on [NIAC2020 vote](https://github.com/nexusformat/NIAC/issues/51#issuecomment-707349309) approving this change.
