### ISSUE TITLE
Inconsistent field naming

### ISSUE THREAD

**Issue by kalcutter** [nexusformat/definitions#791]
There seems to be an inconsistency how fields are named. For example: `beam_center_x` vs. `x_pixel_size`. I think having `_x` as a suffix (like `beam_center_x`) would be preferable. What is the proper way to get this change considered?

**Comment by prjemian** [comment]
@kalcutter: Thanks for the question.  This is the proper place to raise the question.  As I recall, the NIAC has discussed this previously and decided that to tolerate the inconsistency for compatibility with existing data files.  (Readers that expect these fields would need to be modified to handle multiple variations.  While this instance seems quite easy to accommodate, other design aspects pose substantial special-case code, such as finding the default NXdata group to plot).

That said, one way is to preserve the existing name (`x_pixel_size`) but mark it as deprecated with documentation describing the suggested replacement.  This would keep older data files valid while providing a more-consistent naming style.  Here is an example of a deprecated field:  https://github.com/nexusformat/definitions/blob/30bab9896bbec81966541c776de35c0becb61f34/base_classes/NXdetector.nxdl.xml#L53-L54

A pull request would be helpful.

**Comment by prjemian** [comment]
Note: https://github.com/nexusformat/definitions/blob/66d70f4d2fb53b85becc136052e8b12ecdc069b7/nxdl.xsd#L143-L158

**Comment by kalcutter** [comment]
Thanks for the clarification. I think deprecation makes sense in this case. Another broader question I have is: why are `x` and `y` prefixes and suffixes used at all? I think it would be more consistent to represent these things as multi-dimensional datasets like is done for `data_origin` and `data_size` from `NXdetector_module` (also consider `NXtransformations` and many other examples). I can make a PR for these changes if there is consensus on how I should proceed.

**Comment by benajamin** [comment]
Proposal is to recommend that such names be written with the dimension info coming last (e.g. beam_center_x). This does not include changing any existing names - just making a recommendation for the creation of new names.
- thumbs up to accept
- thumbs down to reject
- any other emoji to abstain

**Comment by prjemian** [comment]
At NIAC2020, we discussed this and decided to leave the existing cases *as-is* but to make a recommendation for the future to put the modifying term last rather than first (e.g., some_term_x, some_term_y).  We also discussed whether to be explicit (separate x and y) or make a list such as (x, y) that matches the dimensionality of the data described.  That is a separate discussion.

**Comment by prjemian** [comment]
The recommendation would go into the design chapter.

**Comment by prjemian** [comment]
Specifically, the change would be added to the `datarules` page under the [*Naming Conventions*](https://github.com/nexusformat/NIAC/issues/51#issuecomment-707349309) section.

**Comment by kalcutter** [comment]
Would it not be preferable to deprecate and introduce consistent field names in time for the upcoming "gold" standard given all the other changes? Our software produces a significant number of HDF5 Nexus files with NXdetector. We are happy to make these changes if the community feels this would be better.

**Comment by benajamin** [comment]
@kalcutter 
Deprecating fields to name them more consistently would affect _everybody_ and so we shouldn't do it without plenty of consideration. Nobody pushed the idea that consistent names was worth the hassle of going through such changes.
