### ISSUE TITLE
Can we take NIAC votes on GitHub?

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#795]
It was proposed that we use a new-ish feature to take a user poll on GitHub.  https://github.com/evenchange4/gh-polls-bot

**Comment by prjemian** [comment]
No response to my previous question (that came from one of our telcos).  https://stackoverflow.com/questions/62683421/how-to-install-user-feedback-polls-for-github-issues

**Comment by prjemian** [comment]
@vasole suggests using the standard GitHub emoji responses (thumb up or down) to any issue comment.  @benajamin points out that any person can vote more than once with different votes.

**Comment by prjemian** [comment]
@yayahjb suggests  collecting a poll using a Google doc.

**Comment by prjemian** [comment]
@vasole looked at the Chicago-style voting mentioned above and noticed that only the most recent vote from a user was retained when the page was refreshed.

**Comment by prjemian** [comment]
We should pay attention to who has voted (given an emoji) to ensure they are allowed to vote.  Once a vote is collected, we should add a comment about the result (in case someone adds/removes/changes and emoji after the voting results registered).

**Comment by vasole** [comment]
Just to record that if by mistake somebody has given the wrong vote, (s)he can erase the vote by clicking again on the same emoji. 

A record of the result of the poll at the deadline has indeed to be added as a comment to avoid evolution of the poll with tme.
