### ISSUE TITLE
Attribute Mask and Normalisation

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#814]
Per [NIAC2018](https://www.nexusformat.org/NIAC2018Minutes.html) approved vote, 

> `DATASETNAME_mask` as a general way to specify a mask. We use the conventions as described for `NXdetector/pixel_mask` with the option to use less that 32 bit.

**Comment by prjemian** [comment]
How (where) do we apply this?  Is it a change to the XML Schema (`nxdl.xsd`) or must this be added to every base class?

**Comment by prjemian** [comment]
This belongs in the list of reserved suffixes.

**Comment by benajamin** [comment]
> How (where) do we apply this? Is it a change to the XML Schema (`nxdl.xsd`) or must this be added to every base class?

That's a very good question and I will need to do some research.
