### ISSUE TITLE
DOC: ! LaTeX Error: Too deeply nested.

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#828]
When building the documentation, this error is reported by the pdflatex build.

It means that we have requested more than six levels of a latex ``/begin{quote}`` (or other) block.  The issue could be with how we:

1. extract the rst from the NXDL files
1. format specific documentation (indentation) in the NXDL files
1. format the rst file for each NXDL

We need better code to flag the first two of these conditions.  It is not obvious what code produces this error.  It is obvious it is coming from the documentation of more than just any one specific NXDL.

Despite the error, a PDF is generated and looks fine.

There is a note in the `Makefile` acknowledging this has been known for a long time.

**Comment by PeterC-DLS** [comment]
There is an issue with the `rubric` directives within indented sections in reSText. In the generated LaTeX, each indentation level starts a new `quote` environment. This leads to a `\begin{quote}`/`\end{quote}` pair having a `\subsubsection*`. Seems a bit dodgy to me but I don't think this causes LaTex any problem!

**Comment by PeterC-DLS** [comment]
#844 fixes this
