### ISSUE TITLE
NXroot attributes and a word of caution

### ISSUE THREAD

**Issue by vasole** [nexusformat/definitions#836]
This is just a heads up concerning the number of mandatory attributes of  NXgroup.

HDF5 allows to track the creation order of items in the file. However, unless dedicated compilation flags have been set when building HDF5, that will not work if the number of attributes on a group is 8 or more.

NeXus aware software can sort multiple NXentries by using the appropriate NXentry fields, but other software may present not so friendly ordering.

This issue is just to remind about really thinking twice about if an NXroot attribute should be mandatory or not.

**Comment by vasole** [comment]
A more detailed description of the reasons can be found in 

https://github.com/h5py/h5py/issues/1641

**Comment by mkoennecke** [comment]
I have just pushed a commit which causes nxvalidate to warn only when these recommended attributes are missing.

**Comment by prjemian** [comment]
None of the attributes in [NXroot](https://manual.nexusformat.org/classes/base_classes/NXroot.html) are mandatory at this time.  All content is marked optional.

**Comment by vasole** [comment]
From my side the message has been passed. I close the issue.
