### ISSUE TITLE
inconsistent documentation group @axes attribute

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#851]
As reported by @vasole in https://github.com/nexusformat/NIAC/issues/76, the documentation of the group (not field) `axes` attribute is inconsistent between the [rules](https://manual.nexusformat.org/rules.html?highlight=axes) and [NXdata](https://github.com/nexusformat/definitions/blob/1afe941a1e9d95522619e971ac23464b2b610675/base_classes/NXdata.nxdl.xml#L99).

This is a consistency issue between content in `manual/source/rules.rst`, `base_classes/NXdata.nxdl.xml`, and `nxdl.xsd`.

* `rules.rst` uses:

  - https://github.com/nexusformat/definitions/blob/1afe941a1e9d95522619e971ac23464b2b610675/manual/source/examples/hierarchy-processed.txt#L11
  - https://github.com/nexusformat/definitions/blob/1afe941a1e9d95522619e971ac23464b2b610675/manual/source/examples/hierarchy-raw.txt#L12

* NXdata

  - https://github.com/nexusformat/definitions/blob/1afe941a1e9d95522619e971ac23464b2b610675/base_classes/NXdata.nxdl.xml#L99
  - https://github.com/nexusformat/definitions/blob/1afe941a1e9d95522619e971ac23464b2b610675/base_classes/NXdata.nxdl.xml#L138

* nxdl.xsd

  - The [comment cited above](https://github.com/nexusformat/NIAC/issues/76#issuecomment-714304106) applies to the `axes` attribute of a *field*.  The documentation should be clarified to this distinction.
  - https://github.com/nexusformat/definitions/blob/1afe941a1e9d95522619e971ac23464b2b610675/nxdl.xsd#L688-L707

**Comment by prjemian** [comment]
I will resolve all of these references to be consistent with _with the actual layout in the file as it is described in NXdata_.

**Comment by prjemian** [comment]
As @vasole noted:

In [`rules`](https://manual.nexusformat.org/rules.html?highlight=axes):
> the ``@axes`` attribute is presented as a single string with spaces separating each axis:

> That is in discrepancy with the correct form detailed under NXdata:
> ![image](https://user-images.githubusercontent.com/5636251/96840463-c75f9e80-144a-11eb-96e2-8e1a5b7f37d2.png)

In NXdata, that correct form is described "_as a string list_" (see line 213 below): https://github.com/nexusformat/definitions/blob/1afe941a1e9d95522619e971ac23464b2b610675/base_classes/NXdata.nxdl.xml#L211-L220

**Comment by prjemian** [comment]
We should note that when there is only one item in the string array, that it is acceptable to list just the string itself.  Agree?

**Comment by prjemian** [comment]
Commit bf109e8 belongs to this issue.  Also the note that when there is only one item in the string array, that it is acceptable to list just the string itself. Agree?

**Comment by vasole** [comment]
Yes, I agree. The only place where it was made clear since the beginning that a string list is expected even if there is only one item is with auxiliary_signals.
