### ISSUE TITLE
Clarify documentation of field @axes attribute

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#852]
Documentation of the (deprecated) `@axes` attribute for a *field* is confusing **every** time I look at it.  Needs to make sure this structure:

```
    group/
        field/
            @axes
```

is deprecated and this should be used instead:

```
    group/
        @axes
        field/
            @axes
```

from :
> https://manual.nexusformat.org/nxdl_desc.html?highlight=interpretation#axes
> 
> where one can find:
> 
> ![image](https://user-images.githubusercontent.com/5636251/96841407-10fcb900-144c-11eb-9544-25978c5ea0e9.png)

_Originally posted by @vasole in https://github.com/nexusformat/NIAC/issues/76#issuecomment-714304106_

**Comment by prjemian** [comment]
Identified as part of https://github.com/nexusformat/NIAC/issues/76 and is related to #851.

**Comment by prjemian** [comment]
We should note that when there is only one item in the string array, that it is acceptable to list just the string itself. Agree?

**Comment by benajamin** [comment]
When would you expect to see only a single item in an `axes`? What kind of plot could that be?

**Comment by prjemian** [comment]
1-D data. Suppose you have four fields: a, b, c, & d. You are told the
default 1-D plot is d(b).  So you specify signal="d" and axes="b". The
other two fields are just that, other fields.
