### ISSUE TITLE
Technical demonstration of terminology anchors

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#855]
Per https://github.com/nexusformat/NIAC/issues/73, add HTML anchors for every defined term in the manual.

**Comment by benajamin** [comment]
@hgoerzig  asks:
> How can we proceed here? I think it is just an html thing. When the html is generated from the nxdl file there has to be an anchor created.
In order to get here:
https://manual.nexusformat.org/classes/base_classes/NXmonochromator.html#energy
instead of:
`<strong>energy</strong>`
it has to be:
`<strong id="energy">energy</strong>`
>
> This would have to be done for all fields and attributes. Are there exceptions e.g. for field and attributes that have semantically the same meaning as the `@default` attribute that is in almost every base class.

The html describing the base classes is all generated by scripts that interpret the NXDL description files (see https://github.com/nexusformat/definitions/tree/master/base_classes). I think the NXDL description files need to have the PID added to them and the html-generation scripts need to be extended to read the PID info and add the appropriate tags. 

@prjemian can you point to where the appropriate script resides?

**Comment by prjemian** [comment]
The file to edit is [`definitions/utils/nxdl2rst.py`](https://github.com/nexusformat/definitions/blob/master/utils/nxdl2rst.py) but the process is trickier than a simple edit of the file.  The `nxdl2rst.py` is in the middle of the processing chain.

```
NXDL --[1]--> rst --[2]--> (html, tex --[3]--> pdf)
```

* [1] `nxdl2rst.py`
* [2] sphinx
* [3] pdflatex

We need to figure out how to mark these so that Sphinx will add the `id=` kwarg.

**Comment by prjemian** [comment]
One of the challenges is that *the easy way* is to use reST [reference labels](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html?highlight=anchor#role-ref) (such as `.. _energy:`) that are global throughout the complete set of documentation.  Obviously, we can't do that since we'd get multiple instances of certain popular fields like `energy`.  Sphinx generates a build error when that happens.

To continue along this patter, we'd need to make the label unique to the instance, which diverges from the original goal.

**Comment by prjemian** [comment]
Would an anchor in the format of {class}-{field} be acceptable?  Such as `NXmonochromator-energy`  That might not be unique in a definition since a class could include a subclass definition, both using the same term.  Then {class}-{group-{group}-{group}-{field} might represent a worst case example.

**Comment by prjemian** [comment]
Follow this question posted to Sphinx group: https://groups.google.com/g/sphinx-users/c/OXb-cQcvnJE

**Comment by hgoerzig** [comment]
NXmonochromator-energy this definitely is acceptable. If a class contains a subclass you mean something like NXmonochromator-geometry? In this case it could be kept simple:  {class}-{group|field}. Just what is visible in one html page without making an other click should be referenced as the group normally is another class. NXinsertion_device-geometry and NXmonochromator-geometry are two different things. They are both NXgeometry. This sub-class relation could be described in an ontology. Or if some creates a JSON-Schema form they both could import the form of NXgeometry. But these are modelling efforts that can be done somewhere else or in an other step. For now it is just important to unambiguously reference terms used in a class. In case a JSON_Schema or ontology has been created it can be made clear what it is about and that the terms used come from NeXus and what is meant by them.

**Comment by prjemian** [comment]
Following [Sphinx documentation](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-glossary), here is an example Sphinx (restructured text) source:

```reST
.. _NXbaseclass2:

NXbaseclass2
============

NXbaseclass2 is an example.

.. glossary::

    NXbaseclass2/data (*group*) : data
    NXbaseclass2/data (*field*) : data
    NXbaseclass2/energy (*field*) : energy
    NXbaseclass2/thickness (*field*) : thickness
        A description/definition of this glossary entry.
```

----

This is the raw HTML generated by Sphinx from the reST source:

```html
  <div class="section" id="nxbaseclass2">
<span id="id1"></span><h1>NXbaseclass2<a class="headerlink" href="#nxbaseclass2" title="Permalink to this headline">¶</a></h1>
<p>NXbaseclass2 is an example.</p>
<dl class="glossary simple">
<dt id="term-NXbaseclass2-data-group">NXbaseclass2/data (<em>group</em>)</dt><dt id="term-NXbaseclass2-data-field">NXbaseclass2/data (<em>field</em>)</dt><dt id="term-NXbaseclass2-energy-field">NXbaseclass2/energy (<em>field</em>)</dt><dt id="term-NXbaseclass2-thickness-field">NXbaseclass2/thickness (<em>field</em>)</dt><dd><p>A description/definition of this glossary entry.</p>
</dd>
</dl>
</div>
```

So the HTML `id` tags *in this example* are:

```
term-NXbaseclass2-data-group
term-NXbaseclass2-data-field
term-NXbaseclass2-energy-field
term-NXbaseclass2-thickness-field
```

These reST tags can be referenced from any page in the documentation (note that the `*` symbols are omitted):

```
:term:`NXbaseclass2/data (group)`
:term:`NXbaseclass2/data (field)`
:term:`NXbaseclass2/energy (field)`
:term:`NXbaseclass2/thickness (field)`
```

HTML page view:
![page2](https://user-images.githubusercontent.com/2279984/103445301-eabb7c80-4c37-11eb-87f0-c66a70ba7cde.png)

A copy of this page was created to illustrate how the *energy* and *data* entries are identified individually:

HTML index view:
![demo](https://user-images.githubusercontent.com/2279984/103445304-f313b780-4c37-11eb-9dc4-909be8a007db.png)

**Comment by prjemian** [comment]
While this looks nice for a simple example as above, this shows rough edges when applied to actual application definitions with layered groups and very long names.  To keep each entry unambiguous, the full path name must be used on the left side of the `:`, making the format of each application definition longer.  For example:

![Clipboard01](https://user-images.githubusercontent.com/2279984/103464262-f1a9c400-4cf7-11eb-989d-a9b622ca7ed0.png)

Also, the long name will appear in full in an index entry, causing line overruns for the longer entries, especially in the PDF version of the manual.

**Comment by prjemian** [comment]
Rather than continue this route using the [Sphinx `glossary` directive](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#glossary), will look into writing a custom Sphinx [custom extension](https://www.sphinx-doc.org/en/master/extdev/index.html?highlight=custom%20role) to provide the desired HTML anchors, without disrupting the existing formatting of the manual.

See also: https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#hyperlink-targets

**Comment by prjemian** [comment]
Ah, far simpler to just define a *unique* ["internal hyperlink target"](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#hyperlink-targets).  Some content **must** appear after the target for the HTML anchor `id` to be created.  Example:

```
.. glossary::

    /NXbaseclass2/data/data (*field*) : /
        .. _NXbaseclass2-data-data-field:
        
        Anchor ``id`` provided if there is content following the
        hyperlink target.

        Words, words, words

.. glossary::

    /NXbaseclass2/data/errors (*field*) : /
        .. _NXbaseclass2-data-errors-field:
```

In the HTML, Sphinx will create `id="nxbaseclass2-data-data-field"` (all lower case) but **not** `id="nxbaseclass2-data-errors-field"`.

The `glossary` structure is not needed to use these internal hyperlink targets.

**Comment by prjemian** [comment]
With the new plans, the *internal hyperlink targets* (in the view from NXmx above) are:

```
.. _/NXmx/ENTRY/INSTRUMENT/DETECTOR_GROUP/group_names-field:
.. _/NXmx/ENTRY/INSTRUMENT/DETECTOR_GROUP/group_index-field:
.. _/NXmx/ENTRY/INSTRUMENT/DETECTOR_GROUP/group_parent-field:
```

and the HTML anchors are:

```
id="nxmx-entry-instrument-detector-group-group-names-field"
id="nxmx-entry-instrument-detector-group-group-index-field"
id="nxmx-entry-instrument-detector-group-group-parent-field"
```

**Comment by prjemian** [comment]
The pattern (in Python) for the rst link target is:

```python
{parent_path}{sep}{name}-{nxtype}
```

where `sep="@"` for `nxtype="attribute"` and `sep="/"` for others (field, group, link).

The HTML anchor replaces `/` and `@` with `-` and converts all text to lower case.

**Comment by prjemian** [comment]
This study reveals that NXaperture has two anonymous NXgeometry groups.  Since the default name of `GEOMETRY` will be used for each, this generates an error from Sphinx while building the manual since there will be duplicate hyperlink targets.  Same situation for NXcanSAS and NXdata.
