### ISSUE TITLE
[NXdetector] Bug on documentation layout?

### ISSUE THREAD

**Issue by vasole** [nexusformat/definitions#865]
We would like to put a sort of timestamp on a per frame basis. Looking at the information concerning NXdetector it seems the proper place is start_time[np] and end_time[np]. However, as it is presented, it has to be inside an NXdata named efficiency where a dataset efficiency is mandatory....

https://manual.nexusformat.org/classes/base_classes/NXdetector.html#nxdetector

Is that a documentation layout bug and start_time, end_time, and real_time should be **outside** the efficiency NXdata group?

**Comment by prjemian** [comment]
Those fields are related to the _calibration_ of the detector.  Perhaps you need a `frame_timestamp` array?  This addition to NXdetector would match well with similar information provided in EPICS AreaDetector support, that provides a timestamp for each frame in a sequence.  Someone have a better name for this?

**Comment by prjemian** [comment]
Maybe what I proposed already exists as either `NXdetector/start_time` and `NXdetector/end_time`.  The value here is a float, relative to the ISO8601 time given in the field's `@start` attribute.

**Comment by vasole** [comment]
> Maybe what I proposed already exists as either NXdetector/start_time and NXdetector/end_time. The value here is a float,
> relative to the ISO8601 time given in the field's `@start` attribute.

That is what I want, but I think there is a bug in the documentation layout. Currently it appears as NXdetector/efficiency/start_time and NXdetecto/efficiency/end_time

**Comment by prjemian** [comment]
I see now.  The indentation of these lines: https://github.com/nexusformat/definitions/blob/9781e138a2d9d773db16c8966d00450fd8fcf683/base_classes/NXdetector.nxdl.xml#L428-L441 suggests they were intended, as you say, to be outside the `efficiency` group.  But they are specified in the NXDL _inside_ that group, as the line numbers show:

https://github.com/nexusformat/definitions/blob/9781e138a2d9d773db16c8966d00450fd8fcf683/base_classes/NXdetector.nxdl.xml#L372

https://github.com/nexusformat/definitions/blob/9781e138a2d9d773db16c8966d00450fd8fcf683/base_classes/NXdetector.nxdl.xml#L455

So it is not a formatting error but perhaps a typo in the placement of these two fields?

**Comment by vasole** [comment]
Yes, there is something weird. If efficiency is changing at the start and the end of a frame basically one does not know what to do with the data anyways 🥇

**Comment by prjemian** [comment]
@PeterC-DLS : If this is a typo, as I suspect, can we get a fix for this into the 2010.10 release?

**Comment by prjemian** [comment]
@vasole : Good catch!  Many eyes have passed over this detail.  Added to 2020.10 milestone.

**Comment by PeterC-DLS** [comment]
> @PeterC-DLS : If this is a typo, as I suspect, can we get a fix for this into the 2010.10 release?

Sure, I'm waiting on the remaining ticket...
