### ISSUE TITLE
Some links are not complete as hyperlinks

### ISSUE THREAD

**Issue by JunCEEE** [nexusformat/definitions#882]
Hello,

Just found these links didn't fully function on this [page](https://manual.nexusformat.org/classes/applications/NXmx.html). An extra space seems to be the cause of the problem.

https://github.com/nexusformat/definitions/blob/96ebd852e03016490e9ab4087ce02ad683945a54/applications/NXmx.nxdl.xml#L193-L197

https://github.com/nexusformat/definitions/blob/96ebd852e03016490e9ab4087ce02ad683945a54/applications/NXmx.nxdl.xml#L860-L863

**Comment by prjemian** [comment]
@JunCEEE : Thanks for pointing this out!
