### ISSUE TITLE
invalid link targets

### ISSUE THREAD

**Issue by RussBerg** [nexusformat/definitions#906]
### NXtofsingle:
the link target for **detector_number** does not point to a valid location in the definition:
```
        <link name="detector_number" target="/NXentry/NXinstrument/NXdetector/detector_number"></link>
```

### NXtas
spelling mistake in link target
```
     <link name="ef" target="/NXentry/NXinstrument/analyzer:NXcrystal/ef"/>
```
should be **analyser** as defined earlier in definition

### NXreftof
link target **time_binning** does not point to a valid location in the definition:
```
     <link name="time_binning" target="/NXentry/NXinstrument/NXdetector/time_binning"></link>
```

**Comment by RussBerg** [comment]
@benajamin in a situation like this (NXtofsingle, NXreftof) do we typically just remove the link from the definition or notify the contributor that there is an error that requires their input, or both?

**Comment by benajamin** [comment]
A simple spelling mistake or other bug that doesn't change the clearly intended meaning can be simply fixed. If the meaning is at all unclear or if a change conflict with existing files, then we need to consult the contributors and might need a NIAC vote. In practice, I recommend making a separate pull request for each issue that demonstrates what you think is the appropriate solution and then request the previous contributors to review it.

**Comment by RussBerg** [comment]
Closing this issue as it was broken out into individual issues #907 #908 and #909
