### ISSUE TITLE
NXreftof: link target time_binning does not point to a valid location in the definition:

### ISSUE THREAD

**Issue by RussBerg** [nexusformat/definitions#908]
The original contributor needs to update the definition to resolve the issue, options are either remove the link or add a **time_binning** field in the /NXentry/NXinstrument/NXdetector group.

     <link name="time_binning" target="/NXentry/NXinstrument/NXdetector/time_binning"></link>

**Comment by RussBerg** [comment]
Hi @mkoennecke this is another one you added I think at the same time as NXtas that has the same issue of a non existent field, I would suggest creating the field but i do not know the details it should contain therefore I need your input, thx

**Comment by mkoennecke** [comment]
This came about by switching to time_of_flight from time_binning. There is now a branch which fixes this. Someone please merge.

**Comment by prjemian** [comment]
This work appears to have been completed:  https://github.com/nexusformat/definitions/blob/6aa17a42fe28758136869854c6ed3d2b662c8730/applications/NXreftof.nxdl.xml#L70-L79
