### ISSUE TITLE
NXtas: spelling mistake in link target or group name

### ISSUE THREAD

**Issue by RussBerg** [nexusformat/definitions#909]
There is a conflict in the definition that is either an incorrect **ef** link to an NXcrystal group called **analyzer** or, the group that that link points to is incorrectly named as **analyser**. The original contributor needs to update the definition to resolve the issue by adjusting the spelling of the group or link target so that they are consistent.

The link reads as:

```
     <link name="ef" target="/NXentry/NXinstrument/analyzer:NXcrystal/ef"/>
```
The group it points to reads as:

```
     <group type="NXcrystal" name="analyser">
```

**Comment by RussBerg** [comment]
Hey @mkoennecke it looks like you were the original contributor of this definition, can  you give me some guidance as to which spelling you would like to use for both, thx

**Comment by mkoennecke** [comment]
This comes down to english versus american spelling. I fixed it in english spelling. Someone else please merge or complain.

**Comment by RussBerg** [comment]
fixed
