### ISSUE TITLE
Add geometry information to NXbeam

### ISSUE THREAD

**Issue by PeterC-DLS** [nexusformat/definitions#925]
NeXus has a [default coordinate frame](https://manual.nexusformat.org/design.html#nexus-geometry): its origin is at the centre of the scattering volume in the sample with the beam direction along positive `z` and gravity along negative `y`.

For diffraction and scattering experiments, there are many choices of coordinate frame: for example, the 'You' geometry in [diffcalc](https://diffcalc.readthedocs.io/en/latest/youmanual.html#introduction) or the six-circle diffractometer in [PyMCA](https://github.com/vasole/pymca/blob/master/PyMca5/PyMcaPhysics/SixCircle.py).

Adding a `direction` field to NXbeam will allow the `q` vector to be computed for any pixel on a detector from a properly configured (conforming to the `NXmx` application definition) `NXdetector` group  for any other choice of coordinate frame subject to the `NXdetector_module` group having consistent `vector` attributes in its `fast_pixel_direction`, `slow_pixel_direction`, and `module_offset` fields.

**Comment by PeterC-DLS** [comment]
Added to NIAC agenda in nexusformat/NIAC#115

**Comment by benajamin** [comment]
Looks good to us, we look forward to a pull request (we spied on the branch)

**Comment by PeterC-DLS** [comment]
The PR is #927
