### ISSUE TITLE
What unit type to use for "counts"?

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#932]
NeXus does not have a unit type that matches `counts`.  (number of photons, neutrons, or other counting events)

* What do people use?
* Should we add `NX_COUNTS`?

**Comment by prjemian** [comment]
`NX_PULSES` seems like a good fit but the documentation is specific to clocks.

**Comment by benajamin** [comment]
I second that we should add `NX_COUNT` (singular!). I think that `NX_PULSES` should also be deprecated as `NX_COUNT` would fit in a more general way.

**Comment by prjemian** [comment]
suggested description: *quantity of item(s)*

**Comment by prjemian** [comment]
This can _only_ be an integer quantity.  Thus `NX_INT`, not `NX_NUMBER`.
