### ISSUE TITLE
Allow regions of interest to be recorded

### ISSUE THREAD

**Issue by PeterC-DLS** [nexusformat/definitions#944]
In investigating #939, it became apparent that the sentence from [NXdetector](https://github.com/nexusformat/definitions/blob/493adbeaa6a66f24b15c0882ca4c6594b0692f5f/base_classes/NXdetector.nxdl.xml#L774):
> Use one or more instances of the NXdetector_module group to declare regions of interest or some other subdivision of a detector.

does not make sense as intended as a `NXdetector_module` specifies how a subset of a detector's data array maps to a physical rectangle with given size and orientation. A region of interest would specify a region of a detectors's data array and optionally associate some data derived from it.

To this end, a new NeXus base class is proposed as a child (or one of several children) to an `NXdetector` group:

1. @NX_class = NXregion
2. @type = "rectangular" (initially sole allowed value, other values could be proposed at later date)
3. start = starting position in data array
4. count = number of blocks or items in hyperslab selection
5. (stride) = optional striding used to downsample data (if omitted then use array of ones)
6. (block) = optional binning used to downsample data (if omitted then use array of ones)
7. (scale) = optional scaling of binned data  (if omitted then use arrays of ones)
8. (downsampled_data:NXdata)/ = optional group containing data sliced/downsampled from parent group’s data
9. (region_statistics:NXdata))/ = optional group containing any statistics derived from the region in parent group’s data
                                                 such as sum, minimum, maximum, mean, mode, median, rms, variance, etc. Where more than one
                                                 statistical dataset is written (specified with @signal) then add @auxiliary_signals listing the others.

Note, the fields for the rectangular region specifiers follow HDF5’s dataspace hyperslab parameters

**Comment by PeterC-DLS** [comment]
Final draft looks like this:
![NXregion](https://user-images.githubusercontent.com/1381719/146429994-6714bd02-ded2-4c89-968b-d2f15a913c37.png)

**Comment by benajamin** [comment]
The idea looks good, but some examples would be valuable to see more clearly the use-cases you are considering. It would also be good to allow a mask to define the ROI.
