### ISSUE TITLE
Allow NXdata dimension variables to contain a list of strings

### ISSUE THREAD

**Issue by benajamin** [nexusformat/definitions#945]
[NXdata](https://manual.nexusformat.org/classes/base_classes/NXdata.html) groups contain a multidimensional data array with the @axes attribute pointing to fields within the group that hold lists of values to be used as labels for the corresponding dimensions of the dataset. Currently, the values of these "variable" datasets are restricted to NX_NUMBER. I propose that this be relaxed to allow a list of strings, with the number of list items being equal to the size of the corresponding dimension of the main data array (the one that @signal points to).
This proposal is motivated by Dectris, who would like to present data recorded by some of their detectors in terms of "channels". They would like one axis of the dataset to be labelled as "channel" and to label slices of the data array with strings like "low threshold", "high threshold" and "difference".
partly fixes #940

**Comment by prjemian** [comment]
This needs a branch and pull request since the NIAC has already approved.

**Comment by prjemian** [comment]
The `NX_NUMBER` data type defines a list of the possible data types that could be considered as a number. https://github.com/nexusformat/definitions/blob/01093ec1899a303dddb8d92721723ae0a7378fb3/nxdlTypes.xsd#L515-L525

We could define a new data type that is a union of `NX_NUMBER` and `NX_CHAR`
