### ISSUE TITLE
Drop support for Python < 3.7

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#952]
Since Python support for version 2.7 was [ended](https://www.python.org/dev/peps/pep-0373/) at the start of 2020, and support for Python 3 versions up to 3.6 [ends](https://www.python.org/dev/peps/pep-0494/) at the end of this year, it is time for the NeXus definitions to drop its support for Python < 3.7.  (See #946, for example.)

The processes that publish the documentation should be revised.  The continuous integration workflow tests for these Python versions at this time: https://github.com/nexusformat/definitions/blob/493adbeaa6a66f24b15c0882ca4c6594b0692f5f/.github/workflows/syntax-checks.yml#L11

**Comment by PeterC-DLS** [comment]
`six` is still used in some of the code so perhaps we can remove the use in them

**Comment by prjemian** [comment]
At today's telco, we agreed that this issue should continue, to drop support for Python versions <3.7.

**Comment by prjemian** [comment]
See issue #953 (& PR #955) about the documentation publishing process.

**Comment by prjemian** [comment]
Much of this work was completed in PR #951.  For this issue , examine the repo for any remaining references.
