### ISSUE TITLE
NXarpes pass_energy should be a float

### ISSUE THREAD

**Issue by uwehergenhahn** [nexusformat/definitions#970]
The NXarpes application definition introduces fields NXinstrument:analyser:entrance_slit_size and NXinstrument:analyser:pass_energy. Currently no type definition is given, therefore they are defined as NX_CHAR by default. Both properties however clearly expect a numeric entry, therefore they should be defined as NX_NUMBER or NX_FLOAT.

**Comment by zjttoefs** [comment]
You're correct, Uwe!
Pull request created.

**Comment by uwehergenhahn** [comment]
Thanks. Adding to that, time_per_channel also should bea number.

**Comment by zjttoefs** [comment]
Yup, my pull request has that covered!
