### ISSUE TITLE
NeXus Constructor and other utilities

### ISSUE THREAD

**Issue by benajamin** [nexusformat/definitions#972]
@mkoennecke just told me about [NeXus Constructor](https://github.com/ess-dmsc/nexus-constructor), which I am very eager to play with. I feel that it should be listed in the [manual](https://manual.nexusformat.org/utilities.html). It doesn't seem to fit well with the existing categories, so I'll make a new one - maybe "Geometry".

Should we also list @RussBerg script for creating empty NeXus files from the NXDL definitions? Would it count as "validation", or need a new category? If anyone knows of a NeXus utility not already listed on the manual utilities page, then please speak up!

**Comment by zjttoefs** [comment]
The constructor is being refactored as we speak - you can see the repo is relatively busy.
So if you want to play: don't be shy to report issues.

In the next month we should be able to have all core functionality (back) in place and be able produce the screenshots. That would be good timing for and addition to the manual.

**Comment by RussBerg** [comment]
Although nxdl_to_hdf5.py started out as something to only generate hdf files from nxdl it was a short trip to get it to also generate python scripts for both h5py and nexusformat, so it may make more sense to just mention it in multiple existing categories rather than place it under a new one.
