### ISSUE TITLE
BUG: display of example units is confusing

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#979]
When additional information is specified with a NeXus unit category, such as `NX_DIMENSIONLESS`: https://github.com/nexusformat/definitions/blob/5649a991793ff3f8a0555a0d3a0df5f7b2c7fc01/nxdlTypes.xsd#L146-L155

the examples appear as appended to the last text with a comma prefix added.

![Clipboard03](https://user-images.githubusercontent.com/2279984/152658086-e6126f9f-a955-4274-9aec-04d172faf8c5.png)

Too confusing when additional text is added, such as the proposed `NX_ARBITRARY_UNITS` (#921).

**Comment by prjemian** [comment]
Any documentation text _after_ the `example` elements, such as https://github.com/nexusformat/definitions/blob/5649a991793ff3f8a0555a0d3a0df5f7b2c7fc01/nxdlTypes.xsd#L151

will not be rendered.

Suggest that the examples be presented on a new line.

**Comment by prjemian** [comment]
Also repair the inconsistent indentation, as shown above.

**Comment by RussBerg** [comment]
in the process of making the changes for this I came across an issue where it looks like there is a 27 character limit on a name attribute? 
https://github.com/nexusformat/definitions/blob/2bb99a43e5aa6a10e098d2e233d42993b40f7988/nxdlTypes.xsd#L312
when the documentation is rendered it puts the **Y::** on a new line of its own

![image](https://user-images.githubusercontent.com/4698891/173924165-7768c096-157c-4d43-b94b-eeb46531c51f.png)

If i shorten it to 27 characters everything is fine, I have been looking and can't see where this constraint is coming from, 
@prjemian any ideas?

**Comment by prjemian** [comment]
Some rendering issue.  The online manual page has a different line break at that point.
![Clipboard01](https://user-images.githubusercontent.com/2279984/173926342-ae27da38-a742-4c31-b63f-d6f514379558.png)

So I'm suspecting the sphinx theme is the problem here, with a definition list.

**Comment by prjemian** [comment]
Why two colons?

**Comment by prjemian** [comment]
I just rebuilt the documentation with the [furo](https://github.com/pradyunsg/furo) theme.  Here's a view:
![Clipboard01](https://user-images.githubusercontent.com/2279984/173930018-61367919-03d5-49f7-9e2d-edcea8dd05cf.png)

Need to explore what configurations can be applied to our current theme ([`sphinxdoc`](https://www.sphinx-doc.org/en/master/usage/theming.html)).

**Comment by RussBerg** [comment]
this theme problem with **NX_SCATTERING_LENGTH_DENSITY** should probably be handled in a separate issue

**Comment by prjemian** [comment]
Here is the HTML produced by Sphinx:

```html
<span id="index-40"></span><dl class="field-list simple" id="nx-scattering-length-density">
<dt class="field-odd">NX_SCATTERING_LENGTH_DENSITY</dt>
<dd class="field-odd"><p>units of scattering length density, example(s): <code class="docutils literal notranslate"><span class="pre">m/m^3</span></code></p>
</dd>
</dl>
```

The `sphinxdoc` theme displays this with CSS formatting.  The horizontal size of the window is important but also the theme has a maximum content width it imposes if the window is very wide.

Internally, a reST definition list is converted into a `field-list` as described by the Sphinx CSS.

The sphinxdoc theme inserts some `.css` files into the `_static` directory when building the html documentation.  One of them, `basic.css` has this fragment that controls the fractional width of the _name_ part of the `field-list` to no more than 30% of the available column width:

```css
dl.field-list {
    display: grid;
    grid-template-columns: fit-content(30%) auto;
}
```

This is the code that breaks the long names onto new lines.
