### ISSUE TITLE
nxdlTypes.xsd: Check the xs:restriction as noted

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#983]
Right!  What about these?  Same correction?

https://github.com/nexusformat/definitions/blob/99fb0e0ee50e57ed049566ff16f3159a083ddf3c/nxdlTypes.xsd#L259-L268

https://github.com/nexusformat/definitions/blob/99fb0e0ee50e57ed049566ff16f3159a083ddf3c/nxdlTypes.xsd#L290-L297

https://github.com/nexusformat/definitions/blob/99fb0e0ee50e57ed049566ff16f3159a083ddf3c/nxdlTypes.xsd#L343-L352

_Originally posted by @prjemian in https://github.com/nexusformat/definitions/pull/981#discussion_r801897367_

**Comment by benajamin** [comment]
@prjemian Same correction as what?

**Comment by prjemian** [comment]
> @prjemian Same correction as what?

Quoting the previous comment in #981:

> Not string as all units attributes are strings?

Referring to this line: https://github.com/nexusformat/definitions/blob/821682e3436cb9f98047b27da5126beb150e7d11/nxdlTypes.xsd#L123

**Comment by prjemian** [comment]
That is, the value for the units (type) of `NX_COUNT` should be text, not number, as are all the other units types.
