### ISSUE TITLE
NXmx: Why is the `short_name` attribute of `instrument/name` required? 

### ISSUE THREAD

**Issue by soph-dec** [nexusformat/definitions#985]
As the title indicates, I am wondering why [short_name](https://manual.nexusformat.org/classes/applications/NXmx.html?nxmx-entry-source-name-short-name-attribute#nxmx-entry-instrument-name-short-name-attribute) is not optional. The [same attribute](https://manual.nexusformat.org/classes/applications/NXmx.html?nxmx-entry-source-name-short-name-attribute#nxmx-entry-source-name-short-name-attribute) for `source/name` is optional, could it be that the `optional="true"` was simply forgotten for the attribute of `instrument/name`?

**Comment by phyy-nx** [comment]
Looks like a bug (discussed in NIAC).  short_name for instrument should changed to optional.  I'll put together a PR.  Thanks!

**Comment by soph-dec** [comment]
Thank you!
