### ISSUE TITLE
NXmx total_flux

### ISSUE THREAD

**Issue by lucagelisio** [nexusformat/definitions#986]
The quantity **total_flux** is currently defined as flux incident on beam plane in _photons per second_.
For pulsed light sources, like free electron lasers, the temporal profile of each pulse is rarely reliably known.
It would be therefore desirable and more accurate to express **total_flux** in photons.

Would it be possible to have either photons/second or photons as unit of measurement for **total_flux**?

**Comment by yayahjb** [comment]
total_flux was added to deal with the flux in photons/s/cm^2 summed over
the beam area in cm^2, which
is why it is in photons/s and it is not a good idea to change
dimensionality by a change in units.  For the
case in which temporal profiles are not known, I would suggest we add a new
suffix

    _integrated for the time integral of any existing tag

 and two new definitions:

    flux_integrated in photons/cm^2
and
    total_flux_integrated in photons

for the time integrals of flux and total_flux respectively.

**Comment by lucagelisio** [comment]
Thanks a lot Herbert, I like your proposal.
**total_flux** is a required entry, could this become recommended, or alternatively require this one or its integrated version?

**Comment by phyy-nx** [comment]
Discussion from NIAC telco today: what we need is a way to specify that the user must supply one of total_flux, flux_integrated, or total_flux_integrated.  There doesn't seem to be an easy way to write that specification using NXDL, so it's recommended this issue be brought up in the next NIAC meeting in early March 2022.

**Comment by benajamin** [comment]
I think that it could be accomplished by requiring a "pointer" field be present whose value is the name of the flux measure being provided. An existing example is the `signal` attribute for [NXdata](https://manual.nexusformat.org/classes/base_classes/NXdata.html).

**Comment by phyy-nx** [comment]
Feedback from Spring NIAC 2022: using an [NXmonitor](https://manual.nexusformat.org/classes/base_classes/NXmonitor.html#nxmonitor) class may be better here.  See [NXstxm](https://manual.nexusformat.org/classes/applications/NXstxm.html#nxstxm-entry-control-group) for example.  (This comment is meant as a springboard for more discussion here).

**Comment by lucagelisio** [comment]
This sounds sensible to me!

**Comment by benajamin** [comment]
XML has a [choice element](https://www.w3schools.com/xml/el_choice.asp) that requires exactly one object from a set be present. It would need to be used in the NXDL schema to define a tag that you could then use in NXmx.
