### ISSUE TITLE
Tool suggestion in the tutorial

### ISSUE THREAD

**Issue by benajamin** [nexusformat/definitions#989]
originally raised by @BalazsBago in https://github.com/nexusformat/NIAC/issues/87

> https://manual.nexusformat.org/applying-nexus.html
> It would be nice to have some suggestions to tools to create NeXus files (i.e.: NeXpy)

**Comment by woutdenolf** [comment]
@BalazsBago we document already a tool: h5py

In #1060 I added a reference the the NeXpy documentation.
